### ISSUE TITLE
Codegen Database View

### ISSUE THREAD

**Issue by ericschmall** [slick/slick#1022]
Hi,

is there a possibility to generate code from database views? If there is, could someone push me in the right direction? If not, will this be a feature in the future?

Thanks,
Eric

**Comment by JeremiasIsnardy** [comment]
I'm facing the same problem.
Is there any way to get the views with slick 3.0.0 ?

The method getTables isn't available anymore.

**Comment by szeiger** [comment]
@JeremiasIsnardy The method is now called `defaultTables`

**Comment by JeremiasIsnardy** [comment]
Yes, I'm aware of that. Unfortunately defaultTables does not list any database views.

The method getTables on the other hand did this.

**Comment by cvogt** [comment]
MTable.getTables

is your friend.

http://slick.typesafe.com/doc/3.0.0/api/index.html#slick.jdbc.meta.MTable$

Also see

https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/driver/PostgresDriver.scala#L104

Chris

On 05.05.15 09:50, JeremiasIsnardy wrote:
> I'm facing the same problem.
> Is there any way to get the views with slick 3.0.0 ?
> 
> The method getTables isn't available anymore.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/slick/slick/issues/1022#issuecomment-99083393>.
> 

-- 
Jan Christopher Vogt
Scala Ninja at x.ai
Scala Slick OSS developer
NYC

**Comment by JeremiasIsnardy** [comment]
Ah, ok. Thanks.

In case someone else is facing this problem, instead of using defaultTables I used:
slick.jdbc.meta.MTable.getTables(None, None, None, Some(Seq("VIEW","TABLE")))

**Comment by bravegag** [comment]
Hello, is there a complete example somewhere? I'm using Slick 3.0.3 and have had no luck. I posted a question here http://stackoverflow.com/questions/32756629/how-to-use-slick-code-generator-to-include-database-views-as-well
