### ISSUE TITLE
Can't extend class `Table`

### ISSUE THREAD

**Issue by tminglei** [slick/slick#1028]
Hi @szeiger / @cvogt ,

I'm trying to add postgis topo support to `slick-pg` ([#108](https://github.com/tminglei/slick-pg/issues/108)).

To implement that, I have to resolve a problem firstly: supporting pg composite's field access.
(http://www.postgresql.org/docs/9.3/static/rowtypes.html#AEN7383)

To generate parentheses wrapped codes for pg composite's field accessing, I realized that I should use a special `Symbol` to represent composite column's name in the toNode method of `Column`, which seems imply that I should extend the class `Table` and override its column method, then I can recognize it in generating sql phase.

But I found some methods `createTableDDLBuilder` and `createColumnDDLBuilder` were already binded to original `Table`, and my extended `Table` would cause conflicts.

**Do you have any suggestions?**

_BTW, I can't also extend `FieldSymbol`, since it's a case class. But in many places that access table columns' symbols, it was hard-coded to `FieldSymbol`._

Thanks for your nice help!
Minglei Tu

**Comment by cvogt** [comment]
I suppose this is one of the cases, where you need to open a PR against slick that changes things in order to get your stuff to work.

**Comment by szeiger** [comment]
At first glance I'd say extending FieldSymbol would be the right way to go. It's not final, so you should be able to do this. This will ensure that your symbols are correctly recognized as single columns in the query compiler. You could use a non-standard SymbolNamer to create the correctly quoted identifiers for these fields.

**Comment by tminglei** [comment]
Hi @cvogt / @szeiger, thanks for your nice guide!
I'll try it and keep you updated.

**Comment by nafg** [comment]
You can extend case classes. You just can't (or shouldn't) make one case
class extend another case class.
