### ISSUE TITLE
Cannot access java.sql.Statement options.

### ISSUE THREAD

**Issue by mweiden** [slick/slick#1038]
Given that objects implementing the interface `java.sql.Statement` nor methods that wrap this interface are exposed to the users of the Slick API, several parameters that affect query execution are not available.

An example of this is the Statement's `query timeout` parameter. This makes working around certain issues difficult, such as the one below:

http://forums.mysql.com/read.php?39,599209,599223#msg-599223

As I understand it, this is currently impossible as prepared statements exist only in the scope of this function:

https://github.com/slick/slick/blob/20273109ab984fea7c5a50170dd09985c635bd18/src/main/scala/scala/slick/jdbc/StatementInvoker.scala#L32-L76

These options could be passed into the invoker or stored in the session.

**Comment by cvogt** [comment]
I think better access to the underlying JDBC layer becomes increasingly asked for. @szeiger you suggested that this could be looked at again with the new API. So I assigned it to 3.1.0 for now.

**Comment by mweiden** [comment]
Thanks @cvogt

**Comment by mweiden** [comment]
Does anyone have any ideas regarding this exception? I forked the repository and `preparedStatement.setQueryTimeout(0)` (unlimited timeout) prior to it's execution as described in the thread posted above ^^, but still see the following

```
! com.mysql.jdbc.exceptions.jdbc4.MySQLQueryInterruptedException: Query execution was interrupted
!       at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
!       at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
!       at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
!       at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
!       at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
!       at com.mysql.jdbc.Util.getInstance(Util.java:386)
!       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1078)
!       at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4237)
!       at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2190)
!       at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2046)
!       at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3543)
!       at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:491)
!       at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3245)
!       at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2413)
!       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2836)
!       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2834)
!       at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2156)
!       at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1375)
!       at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
!       at org.apache.commons.dbcp.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:172)
!       at scala.slick.jdbc.StatementInvoker.results(StatementInvoker.scala:39)
!       at scala.slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22)
!       at scala.slick.jdbc.Invoker$class.foreach(Invoker.scala:64)
!       at scala.slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16)
!       at scala.slick.jdbc.Invoker$class.firstOption(Invoker.scala:29)
!       at scala.slick.jdbc.StatementInvoker.firstOption(StatementInvoker.scala:16)
!       at scala.slick.jdbc.Invoker$class.first(Invoker.scala:36)
!       at scala.slick.jdbc.StatementInvoker.first(StatementInvoker.scala:16)
...
```

**Comment by szeiger** [comment]
Connection parameters can be set easily with the new API as long as you don't mind pinning a session, e.g.:

    def withSchema[E <: Effect, R, S <: NoStream](s: String, a: EffectfulAction[E, R, S]) =
      SimpleJdbcAction { ctx =>
        val c = ctx.session.conn
        val old = c.getSchema
        c.setSchema(s)
      }.flatMap { old =>
        a.andFinally(SimpleJdbcAction(_.session.conn.setSchema(old))
      }.withPinnedSession

Statement parameters are trickier because they have to be handled directly in the DatabaseContext to support proper nesting (https://github.com/slick/slick/blob/master/src/main/scala/scala/slick/jdbc/JdbcBackend.scala#L428-455). Maybe we should add a pair of init / cleanup functions to StatementParameters. Nesting couldn't support any optimization in this case (we'd have to concatenate all the nested functions) but it should provide the ability to add arbitrary customizations.

**Comment by cvogt** [comment]
Would init/cleanup allow to catch the exception when the timeout times out? How about being able to provide a decorator function to the one using the preparedstatement instead?

**Comment by szeiger** [comment]
Timeouts have to be handled with `cleanUp` (or `andFinally`). A decorator would have to install and remove custom parameters for each statement separately. init/cleanup functions only need to run once per decorated Action.

**Comment by szeiger** [comment]
Forget what I said about the decorator, I think it should work.

**Comment by cvogt** [comment]
a325f5e looks great. A test case using something like query timout would help demonstrate the usage. I think a lot of people will be happy about this.

**Comment by hvesalai** [comment]
Related to #809, we would need a way to set the fetchsize per request, so it would vary. Does this method allow you to set the statement parameters for each statement separately, or is it like the commit message says, the same for all?

**Comment by cvogt** [comment]
@szeiger How about an Action decorator that sets Statement parameters only for the contained actions?

**Comment by hvesalai** [comment]
We use this code at the moment
```scala
  def createBatchInvoker[U](n: Node, param: Any, size: Int)(implicit session: Session): driver.QueryInvoker[U] = {
    require(!session.conn.getAutoCommit, "AutoCommit must be turned of when you use batch. Use session.conn.setAutoCommit or session.withTransaction")
    new driver.QueryInvoker[U](n, param) {
      override def setParam(st: java.sql.PreparedStatement): Unit = {
        super.setParam(st)
        st.setFetchSize(size)
      }
    }
  }

  def batch[U, C[_]](q: Query[_,U, C], size: Int)(implicit session: Session) =
    createBatchInvoker[U](driver.queryCompiler.run(q.toNode).tree, (), size)

  def batch[RU, C[_]](c: RunnableCompiled[_ <: Query[_, _, C], C[RU]], size: Int)(implicit session: Session) =
    createBatchInvoker[RU](c.compiledQuery, c.param, size)
```

**Comment by szeiger** [comment]
Well, it applies to whatever you decorate. Except in special cases like DDL statements or emulated insertOrUpdate Actions, this means down to the individual statement level.

**Comment by cvogt** [comment]
Test cases demonstrating these use cases would be good.

**Comment by szeiger** [comment]
Usage is exactly the same as for the other statement parameters (see JdbcMiscTest), it's just not easily tested because you cannot observe these changes directly in a testable way.

**Comment by mustajarvi** [comment]
Just wanted to leave a short example for other Slick 3 postgres users having OOM issues with streaming result sets. 

```scala
val q = coffees.result
DB.stream(q.transactionally.withStatementParameters(fetchSize = 2000)).foreach(println)
```
