### ISSUE TITLE
.delete does not work for JdbcProfile

### ISSUE THREAD

**Issue by cvogt** [slick/slick#1040]
```
import scala.slick.driver.JdbcProfile

trait DBComponent {

  val profile: JdbcProfile

  import profile.simple._

  def dbObject(): Database
}

trait QueryExecutor { this: DBComponent =>

  import profile.simple._

  def execute[T <: Rep[_], F, C[_]](query: Query[T, F, C]): List[F] =    dbObject.withSession { implicit session: Session => query.list }

  def executeUpdate[T <: Rep[_], F, C[_]](query: Query[T, F, C], value: F): Int = dbObject.withSession { implicit session: Session => query.update(value) }

  def executeInsert[T <: Rep[_], F, C[_]](query: Query[T, F, C], value: F): Int = dbObject.withSession { implicit session: Session => query.insert(value) }

  def executeDelete[T <: Rep[_], F, C[_]](query: Query[T, F, C]): Int = dbObject.withSession { implicit session: Session => query.delete }*/
  //getting error => delete is not a member of QueryExecutor.this.profile.simple.Query[T,F,C]
}
```

And `queryToDeleteInvoker(query).delete` leads to `QueryExecutor.this.profile.simple.Query[T,F,C] [error] (which expands to) scala.slick.lifted.Query[T,F,C] [error] required: scala.slick.lifted.Query[QueryExecutor.this.profile.Table[_], _, ?] `

See http://stackoverflow.com/questions/27730397/how-to-write-generic-query-executor-method-for-delete?noredirect=1#comment44148425_27730397

**Comment by szeiger** [comment]
Well, the error message makes it pretty clear what's wrong. `queryToDeleteInvoker` requires a Query[Table[_], _, _], not just a Query[Rep[_], _, _]. This is not a bug.

The new API will have the same restriction but you would probably abstract over Actions instead of Queries where this won't be an issue.

**Comment by cvogt** [comment]
Good point :)

**Comment by satendrakumar06** [comment]
thanks @szeiger and @cvogt

It is working fine with Table[_].
 It working fine for single  table. When join mutliple table. I did not work.
Is any way do this ?

 ` def findEmpAndDeptByEmpId(id: Int) = execute {
    empTableQuery.filter(_.id === id) join deptTableQuery on (_.deptId === _.id)
  }`

Idea is do not want to write 'dbObject.withSession { implicit =>}' again and again.I want to write in a single place for all kind of query.Is this make sense ?
or any other better way ?

 See full example.
`import scala.slick.driver.JdbcProfile`

`trait DBComponent {

  val profile: JdbcProfile

  import profile.simple._

  def dbObject(): Database
}

trait QueryExecutor { this: DBComponent =>

  import profile.simple._

  def execute[T <: Rep[_], F, C[_]](query: Query[T, F, C]): List[F] = dbObject.withSession { implicit session: Session => query.list }

  def executeUpdate[T <: Table[_], F, C[_]](query: Query[T, F, C], value: F): Int = dbObject.withSession { implicit session: Session => query.update(value) }

  def executeInsert[T <: Table[_], F, C[_]](query: Query[T, F, C], value: F): Int = dbObject.withSession { implicit session: Session => query.insert(value) }

  def executeDelete[T <: Table[_], F, C[_]](query: Query[T, F, C]): Int = dbObject.withSession { implicit session: Session => query.delete }

}

trait EmployeeRepository extends DepartmentRepository { this: DBComponent with QueryExecutor =>

  import profile.simple._

  class EmpTable(tag: Tag) extends Table[Emp](tag, "emp") {
    def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
    def deptId = column[Int]("dept_id")
    def name = column[String]("name")
    val dept = foreignKey("emp_dept", deptId, deptTableQuery)(_.id)
    def * = (id, name, deptId) <> (Emp.tupled, Emp.unapply)

  }

  val empTableQuery = TableQuery[EmpTable]

  def create(emp: Emp) = executeInsert(empTableQuery, emp)

  def update(emp: Emp) = executeUpdate(empTableQuery, emp)

  def delete(id: Int) = executeDelete { empTableQuery.filter(_.id === id) }

  def findById(id: Int) = execute { empTableQuery.filter(_.id === id) }

  def findEmpAndDeptByEmpId(id: Int) = execute {
    empTableQuery.filter(_.id === id) join deptTableQuery on (_.deptId === _.id)
  }

}

trait DepartmentRepository { this: DBComponent with QueryExecutor =>

  import profile.simple._

  class DeptTable(tag: Tag) extends Table[Dept](tag, "emp") {
    def id = column[Int]("id", O.PrimaryKey, O.AutoInc)
    def name = column[String]("name")
    def * = (id, name) <> (Dept.tupled, Dept.unapply)
  }

  val deptTableQuery = TableQuery[DeptTable]

}`

`case class Emp(id: Int, name: String, deptId: Int)`
`case class Dept(id: Int, name: String)`

**Comment by cvogt** [comment]
it is a good approach to not write session everywhere and keep Queries as long as possible. After that you can currently return a function from Session to result or use an implicit session argument list. However this will change very soon. Slick 3 in a few weeks will offer a new way that gets rid of session entirely. Check out my Scala eXchange 2014 talk https://skillsmatter.com/skillscasts/5969-upcoming-in-slick-2-2

Also see https://github.com/slick/slick/issues/684 regarding the requested support for deleting joined queries.

**Comment by satendrakumar06** [comment]
@cvogt  I already watched Scala eXchange 2014 talks. Slick 3 is awesome. Slick 2.1 has been deployed on production  so I need remove duplicate code and some query optimization.
