### ISSUE TITLE
None value in query produces "= null" sql which is not compatible with postgresql, should be "is null"

### ISSUE THREAD

**Issue by jessebentz** [slick/slick#1050]
http://www.postgresql.org/docs/9.4/static/functions-comparison.html

**Comment by szeiger** [comment]
All operators that can abstract over Option and non-Option types implicitly operate in an Option context, so `foo === None` (assuming foo is an Option) is really `foo.flatMap(a => None.flatMap(b => a == b))`, which always valuates to `None`. Producing `= null` in SQL is consistent with this.

**Comment by cvogt** [comment]
also see https://github.com/slick/slick/issues/757
