### ISSUE TITLE
unslick() doesn't clear interval when autoplay: true and slider syncing

### ISSUE THREAD

**Issue by alpracka** [slick/slick#1066]
Hi, I don't know *slick* much yet but it seems to me unslick() doesn't clear interval properly when instances are synced. The code below runs every time when HTML is refreshed via AJAX. After few times of this refresh, the $('.carousel_due') will start rapidly change its slides (looks like the previously set intervals are still active).

``` javascript
// This part of JS is fired each time when DOM is refreshed via AJAX
$('.carousel_uno, .carousel_due').unslick();

$('.carousel_uno').slick({
  autoplay: true,
  asNavFor: '.carousel_due',
  swipe: false,
  arrows: true
});

$('.carousel_due').slick({
  asNavFor: '.carousel_uno',
  fade: true,
  swipe: false,
  dots: true
});
```

**Comment by szeiger** [comment]
I think you're looking for https://github.com/kenwheeler/slick

**Comment by alpracka** [comment]
Ahh sorry :grin:
