### ISSUE TITLE
codegen: allow preserving column names' letter case

### ISSUE THREAD

**Issue by matanster** [slick/slick#1071]
Allow preserving the letter case of column names, on auto-generation, rather than lowercase them. 

Relevant scenario: 

1. You define your database schema, with a tool like MySQL Workbench, where you have most control.
1. You use camel case for column names in the database, as you are going to access the data with slick.
2. You then "slick codegen" out of the ready database.
2. you may well do this several times while evolving your application, each time plugging the auto-generated code into your scala app, as is.
3. But slick lowercases column names, so they are no longer suitable to appear as variable names in your scala code (assuming column names are not made up of a single word each). 
4. Thus you are forced to either manually fix the generated slick code, or to use underscores as word separators for your column names in the first place, which, leaves you off with underscores in your scala code.

Suggestion: e.g. an option of the codegen process, whether to change (lowercase) column names, or leave them as is. When left as is, slick field names in scala code and database column names, are then the same. Or, allow supplying a custom function for transforming names, rather than lower-casing them.

Rationale being, when using slick, it is plausible to have column names identical to their slick-exposed variable/field names, rather than preserve old school SQL tradition of different names in database v.s. code... This streamlines database development towards the functional flavour.

**Comment by cvogt** [comment]
Already supported with a custom code generator: http://slick.typesafe.com/doc/2.1.0/code-generation.html#customization
