### ISSUE TITLE
Go to Source broken for FreeMarker generated sources

### ISSUE THREAD

**Issue by cvogt** [slick/slick#1074]
Try to got to _Source_ on
http://slick.typesafe.com/doc/3.0.0-M1/api/index.html#scala.slick.jdbc.GetResult$

It leads to a 404 page, because it has the src_managed directory in the path and the actual .scala file doesn't exist. Our best bet is probably to direct to the freemarker file. Not sure that's easily possible. An alternative would be pointing to the place where the .scala file would have been and placing a stub there pointing to the .fm file

The responsible line in the build file is https://github.com/slick/slick/blob/3.0.0-M1/project/Build.scala#L110

@szeiger @VladUreche any idea?

**Comment by VladUreche** [comment]
> Our best bet is probably to direct to the freemarker file.

What do you mean? How about doing a simple `sed` call to remove all the `src_managed` links?

**Comment by cvogt** [comment]
@VladUreche Genius. Done: https://github.com/slick/doc/pull/1

On the other hand the proper fix would probably be to use different scalacOptions for managed sources. Not sure if that can be done. @jsuereth ?

**Comment by VladUreche** [comment]
@cvogt, good point. If sbt would be able to notify scaladoc about generated sources, it would be easy to skip source links for them. @jsuereth, would that be possible?

**Comment by cvogt** [comment]
@VladUreche That doesn't help. I WANT to link to something. It is just pointing to the wrong thing. Postprocessing the html is better than having the links at all

**Comment by szeiger** [comment]
It would be nicer if we could add this as an automatic post-processing step in `makeSite`, maybe as part of the improved build (cc @rfranco)

**Comment by cvogt** [comment]
I agree, let's merge the fix and script for now though to get a fix and a means to reproduce it in. We can kill it once it reached the build.

**Comment by nafg** [comment]
Fixed by aad5c98a5f6bf9e989708ef280319eb4cb3e33f5
