### ISSUE TITLE
Don't break the ModelBuilder api

### ISSUE THREAD

**Issue by cvogt** [slick/slick#1075]
This is the argument raised here: https://github.com/slick/slick/pull/1048

The recently merged changed api of the ModelBuilder is less regular, more verbose and slightly less powerful than the old one. The old model was consistent, beautifully regular, simple and proven. Why break the interface and change it?
- The old one had a clear Structure. The elements of the ModelBuilder exactly matched the structure of the Model and the code generator. Now they don't.
- Names are more verbose now. I can see your point thinking that TableBuilder may be easier to understand than Table. But I doubt it makes a big difference. Not calling them Builder makes the interface almost identical with the code generator, which is a big win. I never found confusion about this in the community with the code generator which has been around over a year. It is clear from the context which makes the new names redundant and unnecessarily verbose. Besides, every class and every method in the ModelBuilder contributes to building the model. Calling some of them builders is even inconsistent from some point of view. Finally, calling the factory methods createX and the class X is inconsistent with usual Scala code where the factory is the apply method of the companion, which has the same name as the class. I know we do that internally in the drivers, but haven't done that for external code so far.
- Not only names are more verbose, also one has to pass through all arguments now when overriding the TableBuilder, etc. Before they came from the context. More unnecessary work, more breakage in user code if we change the api.
- One thing that isn't possible without hackery anymore now is extending the interfaces of TableBuilder, ColumnBuilder etc. in a way that is visible through out the ModelBuilder, because it doesn't follow the virtual subclass pattern anymore.

I liked the old api, let's bring it back :). I think the new one is a step back. Let's revert that. The internals should of course use the new DBIO.

**Comment by szeiger** [comment]
If you have a PR, there's still time to merge it

**Comment by cvogt** [comment]
I'll see what I can do in the next few days.
