### ISSUE TITLE
3.0 - Force action to run in a session

### ISSUE THREAD

**Issue by n3ziniuka5** [slick/slick#1084]
I am trying our the 3.0.0-M1 API.
Is there a way to run an action in a certain session? I am aware that you can combine actions and those will run in a session, but that may be hard to achieve in certain cases.
I am using specs2 for testing and I am trying to create a transaction before each test and then rollback that transaction. I am using `Around` wrapper fro that
````
db.withTransaction { implicit session =>
  try {
    testCase
  } finally {
    session.rollback()
  }
}
````

Then in my testcase I have calls to methods that accept implicit session and create actions and run them with `db.run`. However, there is no way to tell the action to run in that implicitly passed session which means that all of the actions in my test case are always committed.

**Comment by szeiger** [comment]
You could do this with a mock `Database` that wraps all Actions in a transaction.

**Comment by n3ziniuka5** [comment]
I don't really want any mocks as I am integration testing my controllers.

Also, the new api dictates architecture too much in my opinion. Lets say you want to execute an action that depends on the result of the previous one, and you want them both in the same transaction. You could do this very easily with the old api, but now you will have to think how to properly chain the actions instead of having a simple `if()` and then calling an appropriate method.
The new db.run and db.stream are really cool, but I think you took out something very important in the process. Having db.runInSession or db.streamInSession that accepts an implict session might be enough.

Also, how do you manually rollback the transaction in `transactionally` combinator without throwing an exception?

**Comment by szeiger** [comment]
> I don't really want any mocks as I am integration testing my controllers.

You can wrap a real Database and only add the automatic rollback on top.

> Also, the new api dictates architecture too much in my opinion. Lets say you want to execute an action that depends on the result of the previous one, and you want them both in the same transaction.

Switching to an asynchronous API was a strategic decision. It does make your code more complicated because you have to cps-transform everything. It doesn't make much of a difference whether you do this with `Future` or `DBIO`, the basic combinators are the same (at least the pure functional subset). You can't do it asynchronously and still enforce sequencing of DBIO actions with imperative code.

> You could do this very easily with the old api, but now you will have to think how to properly chain the actions instead of having a simple if() and then calling an appropriate method.

You can still use the same design for calling a method depending on a previous database result, except you now have to thread it through DBIO.

    // Old:
    def f(implicit session): Boolean
    def g(implicit session): Unit
    if(f) g

    // New:
    def f: DBIO[Boolean]
    def g: DBIO[Unit]
    f.flatMap(b => if(b) g else DBIO.successful(()))

It can get more complicated for shared state and lazy initialization but making I/O explicit can actually improve your application design.

> I may want to do some low-level jdbc in the same session as well.

    SimpleDBIO(_.connection.someJdbcCall)

> Also, how do you manually rollback the transaction in transactionally combinator without throwing an exception?

You don't actually have to throw an Exception, it's enough to create one and fail the action with it. You can then reify and handle the failure outside the transaction boundary:

    a.flatMap(r => DBIO.failed(new MyException(r))).transactionally.asTry.map {
      case Failure(MyException(r)) => r
      case Failure(t) => throw t
      case Success(r) => r
    }

**Comment by n3ziniuka5** [comment]
I got it working. I think the only real issue here is the lack of examples and documentation, but that is acceptable given the stage of the release.

Thanks

**Comment by xevix** [comment]
Thanks much for the above explanation of `DBIO.failed` to achieve a rollback.

This was some time ago, and the documentation on how to trigger a Rollback seems to be missing in 3.1, with only a passing mention to `transactionally`. http://slick.typesafe.com/doc/3.1.0/dbio.html?highlight=transactionally

The 2.1.0 docs had a great explanation of how to use transactions and issue rollbacks. http://slick.typesafe.com/doc/2.1.0/connection.html?highlight=rollback#transactions

Can I make a request for documentation of this, or perhaps help to add it myself elsewhere? I make this note here as it's one of the top search results for `DBIO.failed`, itself not mentioned at all in the Slick docs from what I can tell, but I'd be glad to take it to a separate issue.

Thanks!

**Comment by szeiger** [comment]
@xevix PRs for documentation improvements are always welcome. Some things are just too obvious when you designed a component yourself so it's easy to forget to document them.

**Comment by xevix** [comment]
@szeiger I'd love to. This may be a bit meta, but should I also add a tidbit in the Sphinx docs about how to build Sphinx docs? I figured it out from http://doc.akka.io/docs/akka/snapshot/dev/documentation.html#Installing_Sphinx_on_OS_X .

**Comment by cvogt** [comment]
Linking to those docs is probably better than copying them :)

**Comment by xevix** [comment]
@cvogt Hah, indeed. At most, I'll point out the build command and the location of `index.html`, and link to Akka for the rest.
