### ISSUE TITLE
Slick 3.0 Transaction blocks

### ISSUE THREAD

**Issue by mohittt8** [slick/slick#1093]
I am moving to Slick 3 and I am facing some issues using transactions.
This used to work in Slick 2.1
 ```  
db.withTransaction { implicit session =>
     	val id = Users.returning(_.id) += User( ...)
       	Addresses ++= Seq(UserAddress(id, ...) , UserAddress(id, ...))
        id
 }
```
This used to run both the queries inside transaction and id of the last inserted user was returned

In slick 3.0.0-RC1, I tried to do
 ```  
db.run({
	val userId = Users.returning(_.id) += User( ...)
	userId flatMap(id => Addresses ++= Seq(UserAddress(id, ...) , UserAddress(id, ...)))
       userId
}.transactionally)
 ```  

However, in this case, only the first query runs. A new record for user gets inserted but there is no record for user addresses. If I remove the userId as the last statement, it works fine but I don't the get Id back. I am not sure whether it is a bug or I am missing something.

P.S - Awesome work on Slick 3. It's way faster than Slick 2.1 on high concurrency.

**Comment by szeiger** [comment]
You create a `userId` action and run it in the end. Remember that Slick 3.0 uses pure functional, monadic I/O without side effects (outside of db.run / db.stream). The `userId flatMap...` line *creates* a new action but you never *run* this action, you only run `userId`. You have to build up a single action to run like this:
```
db.run((for {
    id <- Users.returning(_.id) += User( ...)
    _ <- Addresses ++= Seq(UserAddress(id, ...) , UserAddress(id, ...)))
} yield id).transactionally)
```

**Comment by kops513** [comment]
Hi,
  I get error while inserting the sequence of Object using for-loop. I am new to slick, please help me figure out this problem.

 def saveClosing(transactionGrossCommissionPlan: TransactionGrossCommissionPlan, deductions: Seq[TransactionDeduction], transactionAssociateFinancial: Seq[(TransactionAssociateFinancial, Option[Seq[TransactionAssociateDeduction]])])(implicit request: RequestContext) = {
  
    val transactionId = transactionGrossCommissionPlan.transactionId
    val result = (for {
      _ <- f.query.filter(_._id === transactionGrossCommissionPlan._id.get).update(transactionGrossCommissionPlan)
      _ <- transactionDeductionRepository.query.filter(_.transactionId === transactionId).delete
      _ <- transactionDeductionRepository.query ++= deductions.map(t => t.copy(_id = Some(uuid)))
      _ <- transactionAssociateFinanceRepository.query.filter(_.transactionId === transactionId).delete
      _ <- for (t <- transactionAssociateFinancial) {
        val transactionAssociateDeduction = t._2
        transactionAssociateFinanceRepository.query += t._1
        transactionAssociateDeduction match {
          case Some(s) => for (transAssociateDeduction <- s) {
            val r = transAssociateDeduction.copy(associateFinanceId = Some(transactionAssociateId))
            val jsObj = writer2.writes(r).as[JsObject]
            val entityVal = Json.fromJson(newMetaData(setId(jsObj)))(reader2).get
            val t = transAssDeductionRepository.query.returning(transAssDeductionRepository.query.map(_._id)) += entityVal
          }
        }
      }
    } yield (Right("Close saved successfully"))).transactionally

       f.db.run(result)
}

I get  error while inserting seq of transactionAssociateFinancial

**Comment by cvogt** [comment]
please provide error message and reopen. Minimized example would help, too.

**Comment by cvogt** [comment]
@kops513 see above

**Comment by kops513** [comment]
I took reference from (http://slick.typesafe.com/doc/3.0.0/dbio.html#transactions-and-pinned-sessions)   and it worked for me :)
Here is my latest code 

def saveClosing(transactionGrossCommissionPlan: TransactionGrossCommissionPlan, deductions: Seq[TransactionDeduction], transactionAssociateFinancial: Seq[(TransactionAssociateFinancial, Option[Seq[TransactionAssociateDeduction]])])(implicit request: RequestContext) = {
       val transactionId = transactionGrossCommissionPlan.transactionId
      val result = (for {
        _ <- f.query.filter(_._id === transactionGrossCommissionPlan._id.get).update(transactionGrossCommissionPlan)
        _ <- transactionDeductionRepository.query.filter(_.transactionId === transactionId).delete
        _ <- transactionDeductionRepository.query ++= deductions.map(t => t.copy(_id = Some(uuid)))
        _ <- transactionAssociateFinanceRepository.query.filter(_.transactionId === transactionId).delete
        _ <- DBIO.seq(transactionAssociateFinancial.map { t =>
          val transactionAssociateDeduction = t._2
          val r = transactionAssociateFinanceRepository.query += t._1
          transactionAssociateDeduction match {
            case Some(s) => DBIO.seq(s.map { transAssociateDeduction =>
              val r = transAssociateDeduction.copy(associateFinanceId = Some(transactionId))
              val jsObj = writer2.writes(r).as[JsObject]
              val entityVal = Json.fromJson(newMetaData(setId(jsObj)))(reader2).get
              val t = transAssDeductionRepository.query += entityVal
              t
            }: _*)
            case None => r

          }
        }: _*)
      } yield (Right("Close saved successfully"))).transactionally

      val t = f.db.run(result)
}

But I did not understand DBIO.seq(_.map():_*)  . What _*  does in DBIO.seq ?

**Comment by julienrf** [comment]
See http://www.scala-lang.org/files/archive/spec/2.11/04-basic-declarations-and-definitions.html#repeated-parameters

**Comment by quidproquo** [comment]
Is it possible to have transactional tests/specs? I was used to running specs in a transaction block to avoid writing to the database (using a rollback). How can this be achieved? I've seen no examples of this.

**Comment by szeiger** [comment]
@quidproquo You'll need *some* sort of runner for your tests, so it should be easy to integrate such a feature. Cause a failure to abort the transaction, then reify it to distinguish it from a real error (as shown in https://github.com/slick/slick/issues/1084#issuecomment-74503777). You could add it to Testkit with a few lines of code. We don't do this because it doesn't provide enough isolation (with the extreme case being Oracle, where all DML statements are not transactional)
