### ISSUE TITLE
Nested session/transaction support

### ISSUE THREAD

**Issue by hanfeisun** [slick/slick#1094]
I have `obj1Repository.save()` and `obj2Repository.save()`, both have their method body wrapped in `DB withTranscation {implicit session => }`.. 

Then, `obj1Repository.save()` is going to be used within `obj2Repository.save()`'s transaction scope. However, I am not sure if nested transaction is supported in Slick (not found in the official document).. Also, I saw that nested transaction in Slick may lead to bugs from this page: https://github.com/tim-group/scalaquery_nested 

I was wondering whether nested session/transaction is available to use in Slick currently... Thanks.

**Comment by szeiger** [comment]
If you want to share a transaction, use session.withTransaction, not database.withTransaction. withTransaction blocks on a session can be nested, in which case only the outermost one will create a real database transaction.
