### ISSUE TITLE
3.0.0 RC1 upraded an Imports using Derby

### ISSUE THREAD

**Issue by oogifu** [slick/slick#1101]
Hello,

After the upgrade to RC1, I have the following:

value Implicit in trait JdbcProfile is deprecated: Use 'api' instead of 'simple' or 'Implicit' to import the new API

My new import is now

import slick.driver.DerbyDriver.Implicit._
import slick.driver.DerbyDriver.api.{ Database, Table, Tag, TableQuery }

from the old:

import slick.driver.DerbyDriver.simple._

But I still have that warning

What should be the new imports?

Thanks

**Comment by skibi** [comment]
Hello

You need to remove `import slick.driver.DerbyDriver.Implicit._` (it's also `Deprecated`)
and use `import slick.driver.DerbyDriver.api._`

**Comment by oogifu** [comment]
Thanks. This works partially. Have I missed a migration guide?
This used to work:

def allCustomers: List[DbClient] = {
    val q = scaleClients.map(client => (client.scid, client.name))
    val r = db.withSession { implicit session => q.run}
    r.map(t => DbClient(t._1, t._2))
  }

Now I have this

Description	Resource	Path	Location	Type
value run is not a member of slick.lifted.Query[(slick.lifted.Rep[String], slick.lifted.Rep[String], slick.lifted.Rep[Double], slick.lifted.Rep[Double], slick.lifted.Rep[Int]),(String, String, Double, Double, Int),Seq]

**Comment by oogifu** [comment]
After a closer look at the documentation, the transition path is to do:

    val q = scaleClients.map(client => (client.scid, client.name))
    val r = db.run(q.result)
    val c = Await.result(r, Duration.Inf)
    c.map(t => DbClient(t._1, t._2)).toList

Correct? is this the new way from now on?

**Comment by szeiger** [comment]
Well, not await()ing at all would be the new way, but yes, this is what you would do for migrating.
