### ISSUE TITLE
headOption Throws SQL Syntax Error on MySQL Environment

### ISSUE THREAD

**Issue by cailhuiris** [slick/slick#1105]
I have used Slick-3.0-RC1 Library and tried to make some example for educational purpose. when I try to run test code, I headed to this error. I Thought This would be a bug.

```
val db = Database.forConfig("default")
val password = Crypto.sign("1234")
val query = Users.filter(u => u.userid === "test" && u.password === password).result.headOption
db.run(query).onComplete {
    case Success(user) => println(user)
    case Failure(e) => println(e)
}
```

In the above code, head method works well, but headOption method Throws MySQL SyntaxError as below:

![2015-03-22 1 53 07](https://cloud.githubusercontent.com/assets/2603286/6768098/d715a5d0-d09a-11e4-83c8-b7713902dc3f.png)

**Comment by szeiger** [comment]
This SQL statement is not generated by Slick. Maybe a connection init string in the pool configuration?
