### ISSUE TITLE
slick driver config property for DatabaseConfig.forConfig confusing

### ISSUE THREAD

**Issue by aappddeevv** [slick/slick#1107]
3.0.0 RC1

The DatabaseConfig object takes a driver property which specifies the slick driver. But the underlying default implementation also looks for a driver property which is the class of the jdbc driver. This is confusing especially since the nested object documentation is linked in the DatabaseConfig documentation. 

Suggest modifying documentation in DatabaseConfig to recognize that driver is used both by this configuration object and potentially differently in some of the nested objects.

**Comment by szeiger** [comment]
The name "driver" causes a lot of confusion. We should consider abandoning the distinction between "driver" and "profile" (and only using the latter) or changing it to "dialect" (as used by Hibernate, for example)

**Comment by cvogt** [comment]
I like dialect :)
