### ISSUE TITLE
DatabaseConfig.forConfig path bug 3.0.0 RC1

### ISSUE THREAD

**Issue by aappddeevv** [slick/slick#1108]
In `DatabaseConfig.forConfig`, passing in an empty path is suppose to use the "toplevel" values in the config, however, the following line does not do that:

```scala
lazy val db: P#Backend#Database =
        driver.backend.createDatabase(root, (if(path.isEmpty) "" else path + ".") + "db")
```

This line always uses the db level contrary to the documentation. Here's a fix (I think):

```scala
lazy val db: P#Backend#Database =
        driver.backend.createDatabase(root, (if(path.isEmpty) "" else path + ".db"))
```

**Comment by szeiger** [comment]
This works as intended. The top level or path is where the `driver` and `db` keys are expected.
