### ISSUE TITLE
Tests no run in master branch

### ISSUE THREAD

**Issue by tminglei** [slick/slick#1112]
Hi @szeiger / @cvogt,

After received issue tminglei/slick-pg#142 from @mackler, I did some testing on `slick`, and seems `slick` tests had same problem.

I updated a test case in `com.typesafe.slick.testkit.tests.JdbcMiscTest`:
```scala
  def testOverrideStatements = {
    class T(tag: Tag) extends Table[Int](tag, u"t") {
      def id = column[Int]("a")
      def * = id
    }
    val t = TableQuery[T]

    val a1 = t.filter(_.id === 1)
    val a2 = t.filter(_.id === 2)

    seq(
      t.schema.create,
      t ++= Seq(1, 2, 3),
      a1.result.map(_ shouldBe Seq(3)),   // changed `Seq(1)` to `Seq(3)`
      a1.result.overrideStatements(a2.result.statements).map(_ shouldBe Seq(2)),
      a1.result.head.map(_ shouldBe 1),
      a1.result.head.overrideStatements(a2.result.head.statements).map(_ shouldBe 2)
    )
  }
```

And here's the execute result:
```
> testOnly com.typesafe.slick.testkit.tests.JdbcMiscTest
[info] Compiling 1 Scala source to /myspace/workspace/slick/slick-testkit/target/scala-2.10/test-classes...
[info] Passed: Total 0, Failed 0, Errors 0, Passed 0
[info] No tests to run for testkit/test:testOnly
[success] Total time: 3 s, completed Mar 25, 2015 9:10:55 PM
```

_Is `.result` not working as expected?_

**Comment by szeiger** [comment]
You're not actually running the test. JdbcMiscTest is a Testkit test, not a JUnit test. sbt only sees the JUnit tests (e.g. `slick.test.driver.PostgresTest`), which then use the Testkit runner to run the Testkit tests. Use something like `test-only -- *JdbcMiscTest*` to run it.

**Comment by tminglei** [comment]
Yes, you're right. _Thanks!_
