### ISSUE TITLE
Monomorphic types failing to work in 3.0.0-RC3

### ISSUE THREAD

**Issue by markehammons** [slick/slick#1127]
I'm trying to transition a small slick 2.1 codebase to 3.0.0-RC3, but I've hit a roadblock when it comes to using monomorphic case classes. All the ones that I created and worked in 2.1 fail to compile with some variation of:

```
No matching Shape found.
Slick does not know how to map the given types.
Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
Required level: scala.slick.lifted.FlatShapeLevel
Source type: (scala.slick.lifted.Rep[Int], scala.slick.lifted.Rep[Int])
Unpacked type: (Int, Int)
Packed type: (scala.slick.lifted.Rep[Int], scala.slick.lifted.Rep[Int])
implicit object TestShape extends CaseClassShape(LTestData.tupled, TestData.tupled)
```
That one's from a test definition I wrote as such

```scala
  case class TestData(a: Int, b: Int)
  case class LTestData(a: Rep[Int], b: Rep[Int])

  implicit object TestShape extends CaseClassShape(LTestData.tupled, TestData.tupled)
```
I have no idea what's going on, but by all rights the above example follows the tutorials on monomorphic case classes, and it still doesn't compile in my project.  

https://github.com/markehammons/Webserver is every single bit of my code. The problematic shape classes are in src/main/scala/org/bioemergences/slicktables/ in the shapes and liftedShapes directories. I haven't updated a majority of the code to use 3.0, because it doesn't seem worth it till I pass this roadblock, but MicroscopeData and TestData should both be able to compile and aren't.

**Comment by szeiger** [comment]
Primitive types are provided by the driver. Without importing a driver API (e.g. in https://github.com/markehammons/Webserver/blob/master/src/main/scala/org/bioemergences/slicktables/liftedShapes/Implicits.scala) you can't get a Shape.

**Comment by markehammons** [comment]
Could you add this info to the documentation for monomorphic case classes here: http://slick.typesafe.com/doc/3.0.0-RC3/userdefined.html#monomorphic-case-classes?  None of the examples makes it anyway clear that it's necessary to import this and it certainly wasn't necessary to import this in 2.1.

**Comment by szeiger** [comment]
See http://slick.typesafe.com/doc/3.0.0-RC3/upgrade.html#column-type for the new TypedType requirement.

**Comment by cvogt** [comment]
How about we just import a driver in the code sample here: http://slick.typesafe.com/doc/3.0.0-RC3/userdefined.html#monomorphic-case-classes ? That makes it intuitively clear.

**Comment by szeiger** [comment]
It has nothing to do with monomorphic case classes in particular. Pretty much everything you do with the lifted embedding needs a driver API import.

**Comment by cvogt** [comment]
Maybe the Shape error message should tell people that they shouldn't forget to import a driver then? The fact that they do is not intuitive. Telling people can lower the learning curve which is already pretty steep.

**Comment by slessans** [comment]
+1 for adding to the shape error message.

I had the same issue and it was due to the fact that I switched to a custom database driver and failed to import it into one of my files so the implicits weren't present. The custom driver is a subtype of the old one so this basically failed silently. it would have taken me days to find this issue if it werent for this thread.
