### ISSUE TITLE
selectStatement is not available  in  slick.driver.PostgresDriver.api._  import, 

### ISSUE THREAD

**Issue by vmskarthik** [slick/slick#1128]
I am using Slick 3.0.0-RC3
When I try to get select statement from Query, like ( TableQuery[Entity].selectStatement), It gives error as,    value selectStatement is not a member of slick.lifted.TableQuery[Entity].

But when I change the import  from, "slick.driver.PostgresDriver.api._"   to "slick.driver.PostgresDriver.simple._", It works, with deprecation warning. 

What could be the issue ?

**Comment by szeiger** [comment]
Use `.result.statements` in 3.0
