### ISSUE TITLE
Slick 3.0 DDL generates unacceptable MySQL SQL for String types with primary keys

### ISSUE THREAD

**Issue by eswenson1** [slick/slick#1129]
When Slick 3.0 generates the schema for a table definition of a String field designated as a primary key, such as with this:

  def name: Rep[String] = column[String]("COF_NAME", O.PrimaryKey)

the schema generation fails with the error:

com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'COF_NAME' used in key specification without a key length

This is because MySQL does not allow TEXT or BLOB columns to have primary keys > 768 bytes in the INNODB database engine. This error manifests itself with the helllo-slick-3.0 example, when the H2 database is changed to MySQL. 

Other than explicitly providing a O.DBType("varchar(255)") or similar attribute in the column definition isn't there something better that could be done in the MySQL slick driver so that users don't run into this error when trying out MySQL with Slick?

**Comment by szeiger** [comment]
This is mentioned in the migration guide: http://slick.typesafe.com/doc/3.0.0-RC3/upgrade.html#default-string-types
