### ISSUE TITLE
Database config does not load the "numThreads" and "queueSize" settings correctly

### ISSUE THREAD

**Issue by bbdimitriu** [slick/slick#1139]
This issue affects v3.0.0.
The *Database.forConfig("mydbconfig")* method loads the "numThreads" and "queueSize" values from the root level configuration instead of the node with the given DB configuration name (e.g. "mydbconfig").

**Comment by lucamolteni** [comment]
+1

**Comment by luoq** [comment]
+1

**Comment by szeiger** [comment]
Fixed by #1229
