### ISSUE TITLE
3.0.0: constant warning on application startup: validationTimeout is greater than connectionTimeout, setting validationTimeout to connectionTimeout

### ISSUE THREAD

**Issue by aparamonov** [slick/slick#1140]
This issue is reproduced on default settings using HikariCP 2.3.7.
The problem that default connectionTimeout is 30 seconds, and default validationTimeout is 5 seconds in HikariCP. But slick sets default connectionTimeout to 1 second that fails the check in https://github.com/brettwooldridge/HikariCP/blob/2.3.x/hikaricp-common/src/main/java/com/zaxxer/hikari/AbstractHikariConfig.java#L802 and doesn't set validationTimeout.

**Comment by easel** [comment]
Workaround is to force connection timeout to 5 seconds, something like this:

slick.dbs.default.db.connectionTimeout=5 seconds

**Comment by easel** [comment]
Also, this seems to be specific to newer versions of HikariCP. The version 2.3.0 that you get when building slick doesn't appear to exhibit the error or have the validationTimeout setting.

**Comment by easel** [comment]
PR #1140 brings the HikariCP version in line with play-slick and adds a configuration setting with a  default for the validationTimeout.

**Comment by aparamonov** [comment]
thank you!
