### ISSUE TITLE
DDL generation failed scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving <$anon: >

### ISSUE THREAD

**Issue by angeloh** [slick/slick#1142]
I am using Play 2.3 with dependencies:
"org.specs2" %% "specs2-core" % "3.5-scalaz-7.0.6" % "test",
"org.specs2" %% "specs2-junit" % "3.5-scalaz-7.0.6" % "test",
"com.typesafe.play" %% "play-slick" % "0.8.1"

The Evolution is on. But when I run a test case, it throws this error:

[error] scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving <$anon: >
[error]
[error] STACKTRACE
[error] scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1476)
[error] scala.reflect.internal.Symbols$Symbol$$anonfun$info$3.apply(Symbols.scala:1474)
[error] scala.Function0$class.apply$mcV$sp(Function0.scala:40)
[error] scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] scala.reflect.internal.Symbols$Symbol.lock(Symbols.scala:533)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1474)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$coreLookup$1(JavaMirrors.scala:987)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$lookupClass$1(JavaMirrors.scala:993)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:1010)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:39)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScala(JavaMirrors.scala:1080)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$targToScala$1(JavaMirrors.scala:1067)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$targsToScala$1.apply(JavaMirrors.scala:1069)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$targsToScala$1.apply(JavaMirrors.scala:1069)
[error] scala.collection.immutable.List.map(List.scala:273)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.targsToScala(JavaMirrors.scala:1069)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScala(JavaMirrors.scala:1088)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply$mcV$sp(JavaMirrors.scala:754)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply(JavaMirrors.scala:745)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply(JavaMirrors.scala:745)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.completeRest(JavaMirrors.scala:745)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$LazyPolyType.complete(JavaMirrors.scala:793)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$coreLookup$1(JavaMirrors.scala:987)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$lookupClass$1(JavaMirrors.scala:993)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:1010)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:39)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScala(JavaMirrors.scala:1080)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$targToScala$1(JavaMirrors.scala:1067)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$targsToScala$1.apply(JavaMirrors.scala:1069)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$targsToScala$1.apply(JavaMirrors.scala:1069)
[error] scala.collection.immutable.List.map(List.scala:273)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.targsToScala(JavaMirrors.scala:1069)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.typeToScala(JavaMirrors.scala:1088)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply$mcV$sp(JavaMirrors.scala:754)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply(JavaMirrors.scala:745)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply(JavaMirrors.scala:745)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.completeRest(JavaMirrors.scala:745)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.complete(JavaMirrors.scala:741)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$coreLookup$1(JavaMirrors.scala:987)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$lookupClass$1(JavaMirrors.scala:993)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$classToScala1(JavaMirrors.scala:1010)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$classToScala$1.apply(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:39)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:975)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.sOwner(JavaMirrors.scala:844)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$jclassAsScala1(JavaMirrors.scala:1107)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$scala$reflect$runtime$JavaMirrors$JavaMirror$$jclassAsScala$1.apply(JavaMirrors.scala:1104)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$scala$reflect$runtime$JavaMirrors$JavaMirror$$jclassAsScala$1.apply(JavaMirrors.scala:1104)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$$anonfun$toScala$1.apply(JavaMirrors.scala:97)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache$$anonfun$toScala$1.apply(TwoWayCaches.scala:39)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:34)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:95)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$jclassAsScala(JavaMirrors.scala:1104)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1$$anonfun$apply$mcV$sp$2.apply(JavaMirrors.scala:771)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1$$anonfun$apply$mcV$sp$2.apply(JavaMirrors.scala:770)
[error] scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
[error] scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply$mcV$sp(JavaMirrors.scala:770)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply(JavaMirrors.scala:745)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter$$anonfun$completeRest$1.apply(JavaMirrors.scala:745)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.completeRest(JavaMirrors.scala:745)
[error] scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.complete(JavaMirrors.scala:741)
[error] scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1488)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$info$1.apply(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.info(SynchronizedSymbols.scala:127)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.info(SynchronizedSymbols.scala:168)
[error] scala.reflect.internal.Symbols$SymbolContextApiImpl.typeSignature(Symbols.scala:150)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$typeSignature(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$typeSignature$1.apply(SynchronizedSymbols.scala:129)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anonfun$typeSignature$1.apply(SynchronizedSymbols.scala:129)
[error] scala.reflect.runtime.Gil$class.gilSynchronized(Gil.scala:19)
[error] scala.reflect.runtime.JavaUniverse.gilSynchronized(JavaUniverse.scala:16)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:123)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.gilSynchronizedIfNotThreadsafe(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$class.typeSignature(SynchronizedSymbols.scala:129)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.typeSignature(SynchronizedSymbols.scala:168)
[error] scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$8.typeSignature(SynchronizedSymbols.scala:168)
[error] play.api.db.slick.ddl.TableScanner$.play$api$db$slick$ddl$TableScanner$$classToDDL(TableScanner.scala:77)
[error] play.api.db.slick.ddl.TableScanner$$anonfun$9$$anonfun$12.apply(TableScanner.scala:150)
[error] play.api.db.slick.ddl.TableScanner$$anonfun$9$$anonfun$12.apply(TableScanner.scala:150)
[error] scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
[error] scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
[error] scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:322)
[error] scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
[error] scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:978)
[error] scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
[error] scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] play.api.db.slick.ddl.TableScanner$$anonfun$9.apply(TableScanner.scala:149)
[error] play.api.db.slick.ddl.TableScanner$$anonfun$9.apply(TableScanner.scala:137)
[error] scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
[error] scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:252)
[error] scala.collection.immutable.Set$Set4.foreach(Set.scala:181)
[error] scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:252)
[error] scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
[error] play.api.db.slick.ddl.TableScanner$.reflectAllDDLMethods(TableScanner.scala:137)
[error] play.api.db.slick.plugin.SlickDDLPlugin.evolutionScript(SlickDDLPlugin.scala:50)
[error] play.api.db.slick.plugin.SlickDDLPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply(SlickDDLPlugin.scala:32)
[error] play.api.db.slick.plugin.SlickDDLPlugin$$anonfun$onStart$1$$anonfun$apply$1.apply(SlickDDLPlugin.scala:24)
[error] scala.collection.immutable.Set$Set1.foreach(Set.scala:79)
[error] play.api.db.slick.plugin.SlickDDLPlugin$$anonfun$onStart$1.apply(SlickDDLPlugin.scala:24)
[error] play.api.db.slick.plugin.SlickDDLPlugin$$anonfun$onStart$1.apply(SlickDDLPlugin.scala:23)
[error] scala.Option.foreach(Option.scala:257)
[error] play.api.db.slick.plugin.SlickDDLPlugin.onStart(SlickDDLPlugin.scala:23)
[error] play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
[error] play.api.Play$$anonfun$start$1$$anonfun$apply$mcV$sp$1.apply(Play.scala:91)
[error] scala.collection.immutable.List.foreach(List.scala:381)
[error] play.api.Play$$anonfun$start$1.apply$mcV$sp(Play.scala:91)
[error] play.api.Play$$anonfun$start$1.apply(Play.scala:91)
[error] play.api.Play$$anonfun$start$1.apply(Play.scala:91)
[error] play.utils.Threads$.withContextClassLoader(Threads.scala:21)
[error] play.api.Play$.start(Play.scala:90)
[error] play.api.test.PlayRunners$class.running(Helpers.scala:48)
[error] play.api.test.Helpers$.running(Helpers.scala:403)
[error] play.api.test.WithApplication.around(Specs.scala:23)
[error] org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15)
[error] org.specs2.mutable.Around$$anonfun$delayedInit$1.apply(Around.scala:15)
[error] org.specs2.execute.ResultExecution$class.effectively(ResultExecution.scala:41)
[error] org.specs2.execute.ResultExecution$.effectively(ResultExecution.scala:120)
[error] org.specs2.mutable.Around$class.delayedInit(Around.scala:15)
[error] play.api.test.WithApplication.delayedInit(Specs.scala:20)
[error] sql.google.GoogleUserSpec$$anonfun$2$$anonfun$apply$2$$anon$1.(GoogleUserSpec.scala:19)
[error] sql.google.GoogleUserSpec$$anonfun$2$$anonfun$apply$2.apply(GoogleUserSpec.scala:19)
[error] sql.google.GoogleUserSpec$$anonfun$2$$anonfun$apply$2.apply(GoogleUserSpec.scala:19)
[error] org.specs2.matcher.Scope$$anon$3$$anonfun$asResult$1.apply(ThrownExpectations.scala:139)
[error] org.specs2.matcher.Scope$$anon$3$$anonfun$asResult$1.apply(ThrownExpectations.scala:139)
[error] org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error] org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error] org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error] org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error] org.specs2.matcher.Scope$$anon$3.asResult(ThrownExpectations.scala:139)
[error] org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error] org.specs2.main.CommandLineAsResult$$anon$1.asResult(CommandLineAsResult.scala:17)
[error] org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error] org.specs2.main.CommandLineAsResult$$anonfun$apply$1.apply(CommandLineAsResult.scala:21)
[error] org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error] org.specs2.specification.dsl.mutable.ExampleDsl1$BlockExample$$anonfun$$greater$greater$1.apply(ExampleDsl.scala:39)
[error] org.specs2.specification.core.Execution$$anonfun$withEnv$1$$anonfun$apply$3.apply(Execution.scala:120)
[error] org.specs2.execute.ResultExecution$class.execute(ResultExecution.scala:25)
[error] org.specs2.execute.ResultExecution$.execute(ResultExecution.scala:120)
[error] org.specs2.execute.Result$$anon$10.asResult(Result.scala:230)
[error] org.specs2.execute.AsResult$.apply(AsResult.scala:25)
[error] org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error] org.specs2.specification.core.Execution$$anonfun$withEnv$1.apply(Execution.scala:120)
[error] org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error] org.specs2.specification.core.Execution$$anonfun$execute$2$$anonfun$apply$2.apply(Execution.scala:70)
[error] org.specs2.specification.core.Execution.setResult(Execution.scala:76)
[error] org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error] org.specs2.specification.core.Execution$$anonfun$execute$2.apply(Execution.scala:70)
[error] scala.Option.fold(Option.scala:158)
[error] org.specs2.specification.core.Execution.execute(Execution.scala:70)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:132)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1$$anonfun$apply$6.apply(Executor.scala:130)
[error] org.specs2.specification.core.Fragment.updateExecution(Fragment.scala:44)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:130)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$executeFragment$1.apply(Executor.scala:129)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.executedFragment$lzycompute$1(Executor.scala:104)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1.org$specs2$specification$process$DefaultExecutor$class$$anonfun$$executedFragment$1(Executor.scala:104)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error] org.specs2.specification.process.DefaultExecutor$$anonfun$sequencedExecution$1$$anonfun$3.apply(Executor.scala:109)
[error] scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:201)
[error] scalaz.concurrent.Task$$anonfun$delay$1.apply(Task.scala:201)
[error] scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$3.apply(Task.scala:209)
[error] scalaz.concurrent.Task$$anonfun$suspend$1$$anonfun$3.apply(Task.scala:209)
[error] scalaz.concurrent.Task$.Try(Task.scala:295)
[error] scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:209)
[error] scalaz.concurrent.Task$$anonfun$suspend$1.apply(Task.scala:209)
[error] scalaz.concurrent.Future$class.step(Future.scala:112)
[error] scalaz.concurrent.Future$BindSuspend.step(Future.scala:200)
[error] scalaz.concurrent.Future$class.listen(Future.scala:77)
[error] scalaz.concurrent.Future$BindSuspend.listen(Future.scala:200)
[error] scalaz.concurrent.Future$$anon$1$$anonfun$gatherUnordered$2$$anonfun$apply$10.apply(Future.scala:274)
[error] scalaz.concurrent.Future$$anon$1$$anonfun$gatherUnordered$2$$anonfun$apply$10.apply(Future.scala:273)
[error] scala.collection.Iterator$class.foreach(Iterator.scala:750)
[error] scala.collection.AbstractIterator.foreach(Iterator.scala:1202)
[error] scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error] scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] scalaz.concurrent.Future$$anon$1$$anonfun$gatherUnordered$2.apply(Future.scala:273)
[error] scalaz.concurrent.Future$$anon$1$$anonfun$gatherUnordered$2.apply(Future.scala:269)
[error] scalaz.concurrent.Future$class.listen(Future.scala:81)
[error] scalaz.concurrent.Future$Suspend.listen(Future.scala:199)
[error] scalaz.concurrent.Future$class.runAsync(Future.scala:144)
[error] scalaz.concurrent.Future$Suspend.runAsync(Future.scala:199)
[error] scalaz.concurrent.Future$class.run(Future.scala:161)
[error] scalaz.concurrent.Future$Suspend.run(Future.scala:199)
[error] scalaz.concurrent.Task.attemptRun(Task.scala:103)
[error] org.specs2.control.ActionT$.fromTask(ActionT.scala:125)
[error] org.specs2.control.ActionTSupport$class.fromTask(ActionT.scala:188)
[error] org.specs2.control.package$Actions$.fromTask(package.scala:29)
[error] org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:47)
[error] org.specs2.reporter.Reporter$$anonfun$report$1.apply(Reporter.scala:37)
[error] org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error] org.specs2.runner.SbtRunner$$anonfun$specificationRun$1$$anonfun$2.apply(SbtRunner.scala:75)
[error] org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error] org.specs2.control.ActionT$$anonfun$flatMap$1$$anonfun$apply$2.apply(ActionT.scala:36)
[error] org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:20)
[error] org.specs2.control.StatusT$$anonfun$flatMap$1.apply(StatusT.scala:19)
[error] scalaz.WriterT$$anonfun$flatMap$1.apply(WriterT.scala:61)
[error] scalaz.WriterT$$anonfun$flatMap$1.apply(WriterT.scala:60)
[error] scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:63)
[error] scalaz.effect.IO$$anonfun$flatMap$1$$anonfun$apply$9.apply(IO.scala:62)
[error] scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$2.apply(Free.scala:72)
[error] scalaz.Free$$anonfun$flatMap$1$$anonfun$apply$2.apply(Free.scala:72)
[error] scalaz.Free.resume(Free.scala:80)
[error] scalaz.Free.go2$1(Free.scala:116)
[error] scalaz.Free.go(Free.scala:120)
[error] scalaz.Free.run(Free.scala:174)
[error] scalaz.effect.IO$class.unsafePerformIO(IO.scala:23)
[error] scalaz.effect.IOFunctions$$anon$5.unsafePerformIO(IO.scala:221)
[error] org.specs2.runner.SbtRunner$$anonfun$newTask$1$$anon$4.execute(SbtRunner.scala:40)
[error] sbt.ForkMain$Run$2.call(ForkMain.java:294)
[error] sbt.ForkMain$Run$2.call(ForkMain.java:284)
[error] java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
[error] java.util.concurrent.FutureTask.run(FutureTask.java:166)
[error] java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
[error] java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
[error] java.lang.Thread.run(Thread.java:724)
[error]

**Comment by szeiger** [comment]
Whatever this monstrosity of a stacktrace means, it's from play-slick, not from Slick itself, so you should open a ticket there.
