### ISSUE TITLE
upgrade.html didn't get indexed.

### ISSUE THREAD

**Issue by dwalend** [slick/slick#1144]
I searched for "headOption" using the search box on http://slick.typesafe.com/doc/3.0.0/ , after reading about it on http://slick.typesafe.com/doc/3.0.0/upgrade.html .

"Your search did not match any documents. Please make sure that all words are spelled correctly and that you've selected enough categories."

I've double-checked with a cut/paste. Could be the upgrade.html didn't get indexed.

Hope that helps,

Dave

**Comment by cvogt** [comment]
verified

**Comment by cvogt** [comment]
maybe it doesn't properly index code snippets or something

**Comment by szeiger** [comment]
It's the capitalization. "headoption" works, "headOption" does not. I tried some other search terms and results did not change with capitalization. No idea what's wrong, but it needs to be fixed in Sphinx.

**Comment by dwalend** [comment]
Thanks for running this to ground, szeiger.

**Comment by Sumith1896** [comment]
Unclear here.
Observations:
- Current master has only `3.0` to `3.1` in the `upgrade` section, which does not have `headOption` in the `html`. 
- Quick search on things like `compatibility policy` etc showed that `Upgrade` is indexed.

What exactly is the issue description, how do I reproduce?

**Comment by dwalend** [comment]
I searched for the term "headOption" last May, and didn't get any results. szeiger bracketed it to trouble with camel casing - he got results for "headoption" . Try searching for camel cased terms in that upgrade.html page.

(Also, it might be nice to keep the old upgrade instructions around. Not every project can keep pace with Slick's frequent releases.)

**Comment by trevorsibanda** [comment]
This is not an issue in 3.2.1 
Closing
