### ISSUE TITLE
Bug when I have the slider in the accordion with Display:none the slider doesn't initiate the image height

### ISSUE THREAD

**Issue by xtianus79** [slick/slick#1145]
So, looking for a solution but hard to find.  

We have figured out that it is the display none of the slider when the slider is in the accordion.  so what happens is that the slider height or image doesn't commence the correct height.  what happens is the image is basically hidden and the dots and arrows are left behind.  After the first slider is selected, via the dots or arrows, then it pops into place.  

Any help is appreciated.

**Comment by cvogt** [comment]
wrong project, this is slick the db library

**Comment by xtianus79** [comment]
sorry
