### ISSUE TITLE
Can't resolve symbol result in IDEA 14 CE

### ISSUE THREAD

**Issue by XuNeal** [slick/slick#1149]
I get "Can't resolve symbol result" error in idea,  but `sbt compile` ok

My source like this 
```
import slick.driver.PostgresDriver.api._
db.run(users.filter(_.email === email).result.headOption)
```

**Comment by yadavan88** [comment]
@XuNeal Try downloading the nightly build of scala plugin and install it in your IDEA. It will resolve the issue.

**Comment by XuNeal** [comment]
I update the scala plugin to 1.5, It works, Thanks.
