### ISSUE TITLE
Log query parameters

### ISSUE THREAD

**Issue by szeiger** [slick/slick#1150]
Statement logging doesn't show the actual parameters for PreparedStatements. We should add a separate logger to do this.

**Comment by fractal** [comment]
+1
This is super useful

**Comment by szeiger** [comment]
I'll take a stab at an implementation. It looks like a low-effort feature with a big impact on usability. I'm not sure how far we should go with creating a single statement that you can run standalone. For one, it's not the same to the database optimizer as the original statement with the bind variables, plus it only works when all types used by bind variables have a literal representation. This could at best be an optional feature, but at least the basic functionality of logging printable parameter values alongside the query shouldn't be hard to implement.

**Comment by soren-schmidt** [comment]
+1
Great to hear!

**Comment by mrpelle** [comment]
+1

**Comment by djx314** [comment]
@szeiger Here is a good choice. <https://github.com/jdbcdslog/jdbcdslog>
So I suggest that slick can make a different logger from this.
jdbcdslog log the sql without any ?, so I can't differentiate where is ? and where is literal. Slick can keep back the ? and tell us the index and the value for the ?.

**Comment by szeiger** [comment]
Yes, that's the idea, at least for a first version. I'm integrating it directly at the JDBC level, so it works for Lifted Embedding and Plain SQL alike. There's no additional "magic" like parsing back SQL statements, just separate logging of the parameters. If we also want "fake" SQL statements with the parameters embedded (is there demand for such a feature"), It could be implemented cleanly at a higher level by generating a 2nd statement in a modified code generator that ignores the `volatile` hints (and any errors that arise from not being able to do that).
