### ISSUE TITLE
Document insertOrUpdate in the documentation?

### ISSUE THREAD

**Issue by bjfletcher** [slick/slick#1154]
Is `insertOrUpdate` worth a mention in the main documentation?

Perhaps a sentence at the end of the [updating](http://slick.typesafe.com/doc/3.0.0/queries.html#updating) subsection?

Feel free to close this if it's deemed not worthy (am new here BTW).

**Comment by bjfletcher** [comment]
https://github.com/slick/slick/issues/6 has the discussion about this (then)  new feature.

(With thanks to Gábor Bakos on SO for the link.)

**Comment by i-schuetz** [comment]
+ 1

**Comment by trevorsibanda** [comment]
http://slick.lightbend.com/doc/3.2.1/queries.html
