### ISSUE TITLE
LeftJoin with empty columns

### ISSUE THREAD

**Issue by isn0gud** [slick/slick#1156]
I want to filter table y from table x
```scala
    val q = for {
      (x, y) <- xTable joinLeft yTable on (_.id === _.id) if (y.isEmpty)
    } yield (x.id, x.name)
```
compiles to 
```sql
select x2.x3, x2.x4 from (...columns of x...) x2 left outer join (....columns of y...) x32 on x2.x3 = x32.x31 where not (x32.x24 = 1);
```
This does not work since `not(xy = 1) ` does not match if the table is empty/has null rows.
Solutions?

**Comment by szeiger** [comment]
Looks like a problem with the way we desugar discriminator column checks. It should probably generate a "is not null" check instead of "= 1" to get ternary logic right.

Workaround: Use something like xTable.filterNot(_.id in yTable.map(_.id))

**Comment by isn0gud** [comment]
This workaround introduces a sub query which I want to avoid. I used the plain sql feature which works great. :+1:

**Comment by v6ak** [comment]
I changed `y.isEmpty` to `y.fold(true.asColumnOf[Boolean])(_ => false)`, which does the job correctly without a subquery.

However, it is weird that isEmpty is [defined in a very similar way](https://github.com/slick/slick/blob/3cd8617296d3d9d05cdf08b6bb4a776eb262ea21/slick/src/main/scala/slick/lifted/ExtensionMethods.scala#L217):

      def isEmpty: Rep[Boolean] = fold(LiteralColumn(true))(_ => LiteralColumn(false))

Maybe there is some optimizer bug, as I can't imagine how could be such SQL produced from that without AST postprocessing. Such optimizer bug might also affect something else.

But I understand that NULLs in SQL are tricky.
