### ISSUE TITLE
[Feature] Composable SQL Strings

### ISSUE THREAD

**Issue by schmitch** [slick/slick#1161]
Due to the nature of some SQL queries it will be a great addition to slick, to have composable SQL Strings, which means that you could now generate some where parts dynamically without loosing some security feature's of SQL interpolated strings.

With this feature it would now be possible to write a query like that without loosing sql injection prevention or other security features of slick:

Example:

```
def (username: Option[String], id: Option[Long]) = {
    val q0 = List()
    val q1 = if (username.isDefined) sql"username = $username" :: q0 else q0
    val q2 = if (id.isDefined) sql"id > $id" :: q1 else q1
   val where = sql"WHERE ${q2.mkstring(" AND ")}"
   db.run(sql"SELECT * FROM table #$where;".as[TableRow])
}
```

Another example would be an update or an insert which will add some rows on demand:

```
def (username: Option[String], id: Option[Long]) = {
val userQuery = if(username.isDefined) sql"username = $username" else sql""
val idQuery = if(id.isDefined) sql"id = $id" else sql""
db.run(sql"UPDATE table SET first_name = 'Mustermann', #$userQuery, #$idQuery")
}
```

This API would require significant input so I think for keeping backwards compatibility there would be need for some keywords, other than `sql""`. Also it should work to have a better api than just concat a List of queries with mkstring, so there would be the need for doing a `.and` or `.or` or when we look at the update part there is a comma in between.

Would be great to here some input on this. And espacially to have some input how to solve the most common problems with this feature, like dynamic SET parts of a update query or mixing dynamic with static parts and dynamic where filter.

**Comment by julienrf** [comment]
I doubt you will really get benefits here… you will want to add more and more feature to support more combinations in a typesafe way and you will end up with … the actual Slick lifted API.

**Comment by sedovalx** [comment]
Btw, is there a way (in Slick 3.0.0) to execute an sql from a String variable?

**Comment by cvogt** [comment]
I could see to simply support concatenation operators between partial queries created using sql"..." interpolation. That would still prevent injections. Syntax or type-safety guarantees are off anyways with plain SQL without using tsql.

@sedovalx you can use `StaticQuery.queryNA[Person]("SELECT * from person")` and friends: https://github.com/slick/slick/blob/e9ab33083bfa1ae642a93d4e52b4ac87b42dc917/slick/src/main/scala/slick/jdbc/StaticQuery.scala#L42

**Comment by cvogt** [comment]
@schmitch This one doesn't seem too hard to implement actually. The sql"..." results are stored in `SQLActionBuilder` https://github.com/slick/slick/blob/e9ab33083bfa1ae642a93d4e52b4ac87b42dc917/slick/src/main/scala/slick/jdbc/StaticQuery.scala#L193

I think you simply need to a write an extension method or two for SQLBuilder, that concatenate the contained values (SetParameters also just wraps a sequence).

**Comment by sedovalx** [comment]
@cvogt thanks for response! Is there a way to convert StaticQuery to DBIOAction? Or should I use deprecated methods like `db.withSession` and `query.list` as before?

**Comment by cvogt** [comment]
@szeiger can probably answer that

**Comment by btd** [comment]
@szeiger @cvogt i also would like to know answer. Thanks!

**Comment by beyonix** [comment]
@szeiger An answer would be greatly appreciated indeed! Thanks a lot in advance.

**Comment by TimothyKlim** [comment]
+1

**Comment by btd** [comment]
I came to such function:
```scala
import slick.jdbc.{SetParameter, SQLActionBuilder}

def sql[T](query: String)(p: T)(implicit f: SetParameter[T]) = {
  SQLActionBuilder(Seq(query), f.applied(p))
}
```
Working fine for me.

**Comment by szeiger** [comment]
This produces a DBIOAction. You can already do the same with the interpolators. A proper integration of Plain SQL subqueries into the Lifted Embedding would first of all require Plain SQL to use JdbcTypes.

**Comment by szeiger** [comment]
Blocked on #1263

**Comment by szeiger** [comment]
I just read the original ticket again and it is not what I thought it was. Integration of Plain SQL with the Lifted Embedding could be useful (and would indeed be blocked on #1263), but this ticket is about composition of Plain SQL queries. I don't see the need for new operators though, it should all be doable with interpolation.

**Comment by schmitch** [comment]
yes after reading these comments I think that there is really no need for new operators.
As said that was just a draft

**Comment by schmitch** [comment]
Currently I fixed it with SimpleDBIO query and PositionedParameters and PositionedResult class, however if I would know more about macro's I would tackle that, is there any good documentation around macro's?

**Comment by cvogt** [comment]
http://docs.scala-lang.org/overviews/macros/overview.html
https://github.com/scalamacros/macrology201 (<- follow link at the bottom)

**Comment by wpc009** [comment]
+1 for this. composition of plain sql could be useful if I just want to `update` some `none-null` field of some record, which field is `none-null` is not sure by the time of compilation. I can't find a way besides composition of plain sql.

**Comment by cvogt** [comment]
Quill has built in support for appending to the generated SQL. We may want to consider something along those lines. https://github.com/getquill/quill/blob/af2dc8373b92eb04731b49fb31cad03e87ff819d/README.md#infix

**Comment by schmitch** [comment]
I especially like that: https://github.com/getquill/quill#mirror-sources

**Comment by szeiger** [comment]
Workaround for composing queries in 3.1:

    def concat(a: SQLActionBuilder, b: SQLActionBuilder): SQLActionBuilder = {
      SQLActionBuilder(a.queryParts ++ b.queryParts, new SetParameter[Unit] {
        def apply(p: Unit, pp: PositionedParameters): Unit = {
          a.unitPConv.apply(p, pp)
          b.unitPConv.apply(p, pp)
        }
      })
    }

    val q3 = sql"select id from USERS where name = $foo"
    val s3 = q3.as[Int]
    val s3a = concat(q3, sql" and name = $foo").as[Int]

    s3.statements.head shouldBe "select id from USERS where name = ?"
    s3a.statements.head shouldBe "select id from USERS where name = ? and name = ?"

**Comment by wuservices** [comment]
@szeiger The workaround for composing here has been very useful! Is it possible to do something similar with `tsql`? I have a super long SELECT, then I compose with WHERE and also GROUP BY for certain queries, but it'd be nice to know if the types will explode before runtime.

**Comment by szeiger** [comment]
Another useful method:

```
    def values[T](xs: TraversableOnce[T])(implicit sp: SetParameter[T]): SQLActionBuilder = {
      var b = sql"("
      var first = true
      xs.foreach { x =>
        if(first) first = false
        else b = concat(b, sql",")
        b = concat(b, sql"$x")
      }
      concat(b, sql")")
    }
```

Use is as in:

```
concat(sql"select id from USERS where id in ", values(Seq(1,2))).as[Int]
```

**Comment by szeiger** [comment]
@wuservices there is no way to make this work with `tsql`. In order to perform the compile-time checking it needs to see the complete statement as a literal.

**Comment by wuservices** [comment]
Thanks for the info. I think just writing a test that runs the plain query to see if it doesn't error out,  will achieve similar pre-production-runtime confidence.

**Comment by raam86** [comment]
@szeiger this methods stacksoverflows on values as small a list of 1000 integers.

**Comment by raam86** [comment]
@szeiger `values` is a real nice function, however I encounter stackoverflow on large inputs.

this stackoverflows:
```
 val zz = concat(sql"select id from USERS where id in ", values((1 to 50000))).as[Int]
  db.run(zz)
```
It will only throw stackoverflow error when `new setParameter` is called, not when preparing the string so I think this example is ok:
```
val range = (1 to 50000)
  val q = s"(${range.map(_ => "?").mkString(",")})"
  val pstmt = db.source.createConnection().prepareStatement(s"select id from USERS where id in  $q")
  val iter = range.toIterator
  var acc = 1
  while(iter.hasNext){
    pstmt.setInt(acc, iter.next())
    acc = acc + 1
  }
  val it2 = pstmt.executeQuery()
```

The above code runs fine.

Is there a way to trampoline this code? Any other solution? 

Thanks,

**Comment by fkoehler** [comment]
Based on @szeiger'c comment above https://github.com/slick/slick/issues/1161#issuecomment-230741592 one can write the following implicit class:

```
trait SlickPlainSqlActionBuilderSyntax {

  implicit class SlickPlainSqlActionBuilderSyntax(a: SQLActionBuilder) {
    def ++(b: SQLActionBuilder): SQLActionBuilder = concat(a, b)

    private def concat(a: SQLActionBuilder, b: SQLActionBuilder): SQLActionBuilder = {
      SQLActionBuilder(a.queryParts ++ b.queryParts, new SetParameter[Unit] {
        def apply(p: Unit, pp: PositionedParameters): Unit = {
          a.unitPConv.apply(p, pp)
          b.unitPConv.apply(p, pp)
       }
      })
    }
  }

}
```

to express code like this when extending the trait:

```
val sqlActionBuilder = sql"SELECT * FROM " ++
                             sql"tableName WHERE id = $id1 " ++
                             sql"AND id2 = $id2"
```

**Comment by sakoht** [comment]
This is really helpful.  

One additional thing I need is to get access to the underlying parameter list.  I need a hash of the query that will vary reliably with its parameter values.

The only way I've found is to actually take the SQL and make a PreparedStatement and call `.unitPConv((), new PositionedParameters(dummyPreparedStatement))`, which leads to those lambdas being invoked, but then the statement handle is update to replace the `?` with the underlying values.   

Is there another way to get underneath the opaque lambdas?

**Comment by mykytamykhailenko** [comment]
Any updates on it? It seems that the newer version of Slick does not support concatenation of plain queries any more?
