### ISSUE TITLE
The connection attempt failed for batch insert

### ISSUE THREAD

**Issue by pganta** [slick/slick#1167]
We recently we upgraded to Slick 3.0. After upgrade we are getting below error while  inserting batch of 2000 records with 30 seconds intervals.  with older version we where able to insert 7000 records with 7-8 seconds intervals. Not sure what is causing below error. 

The connection attempt failed. at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:249) at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66) at org.postgresql.jdbc2.AbstractJdbc2Connection.(AbstractJdbc2Connection.java:127) at org.postgresql.jdbc3.AbstractJdbc3Connection.(AbstractJdbc3Connection.java:29) at org.postgresql.jdbc3g.AbstractJdbc3gConnection.(AbstractJdbc3gConnection.java:21) at org.postgresql.jdbc4.AbstractJdbc4Connection.(AbstractJdbc4Connection.java:41) at org.postgresql.jdbc4.Jdbc4Connection.(Jdbc4Connection.java:24) at org.postgresql.Driver.makeConnection(Driver.java:414) at org.postgresql.Driver.connect(Driver.java:282) at java.sql.DriverManager.getConnection(DriverManager.java:664) at java.sql.DriverManager.getConnection(DriverManager.java:208) at slick.jdbc.DriverJdbcDataSource.internalCreateConnection(JdbcDataSource.scala:98) at slick.jdbc.DriverJdbcDataSource.createConnection(JdbcDataSource.scala:94) at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:394) at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:394) at slick.jdbc.JdbcBackend$SessionDef$class.prepareStatement(JdbcBackend.scala:252) at slick.jdbc.JdbcBackend$BaseSession.prepareStatement(JdbcBackend.scala:386) at slick.jdbc.StatementInvoker.results(StatementInvoker.scala:33) at slick.jdbc.StatementInvoker.iteratorTo(StatementInvoker.scala:22) at slick.jdbc.Invoker$class.foreach(Invoker.scala:69) at slick.jdbc.StatementInvoker.foreach(StatementInvoker.scala:16) at slick.jdbc.StreamingInvokerAction$class.run(StreamingInvokerAction.scala:22) at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218) at slick.driver.JdbcActionComponent$QueryActionExtensionMethodsImpl$$anon$1.run(JdbcActionComponent.scala:218) at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.liftedTree1$1(DatabaseComponent.scala:231) at slick.backend.DatabaseComponent$DatabaseDef$$anon$2.run(DatabaseComponent.scala:231) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) at java.lang.Thread.run(Thread.java:745) Caused by: java.net.NoRouteToHostException: Cannot assign requested address at java.net.PlainSocketImpl.socketConnect(Native Method) at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345) at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) at java.net.Socket.connect(Socket.java:589) at org.postgresql.core.PGStream.(PGStream.java:61) at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:121)

**Comment by cvogt** [comment]
I doubt anyone can help you with this unless you provide a way to reproduce the problem.
