### ISSUE TITLE
Completely dynamic queries

### ISSUE THREAD

**Issue by strelec** [slick/slick#1176]
I am looking for a way to do completely dynamic queries -- that means read user input and produce a nice looking table, depending on the column types.

I have not found a way to make this possible via Slick.

```scala
val query = readString
db.run(query.as[Seq[Any]]).onComplete(println)
```

**Comment by nafg** [comment]
What sort of user input?

**Comment by strelec** [comment]
The SQL query to be performed.

**Comment by nafg** [comment]
From http://slick.typesafe.com/doc/3.0.0/sql.html#result-sets it looks like
it's just a matter of defining an appropriate GetResult
<http://slick.typesafe.com/doc/3.0.0/api/index.html#slick.jdbc.GetResult>,
which gives you a PositionedResult
<http://slick.typesafe.com/doc/3.0.0/api/index.html#slick.jdbc.PositionedResult>,
which should have everything you need.

**Comment by strelec** [comment]
I still don't know how to get Seq[Any] from an arbitrary SQL query.

**Comment by szeiger** [comment]
See #539
