### ISSUE TITLE
Implement "O.Unique" in BasicTableComponent

### ISSUE THREAD

**Issue by larvanitis** [slick/slick#118]
I am now starting using Slick and the most straightforward way of declaring uniqueness in my model seemed adding `O.Unique` to the relevant column.
This is missing and we have to use an index for this reason which is sub-optimal as solution IMHO.

I am opening this feature request after Stefan Zeiger's inducement in https://groups.google.com/d/msg/scalaquery/qtsXlD_pytE/judK0nkTSCEJ

**Comment by intracer** [comment]
Felt so natural but left behind :(

**Comment by cvogt** [comment]
@trevorsibanda mind checking if this is a low hanging fruit?

**Comment by cvogt** [comment]
Fixed in #1523
