### ISSUE TITLE
Codegen: Add a way to suspress the output of Table descriptions

### ISSUE THREAD

**Issue by schmitch** [slick/slick#1184]
Currently I'm using slick only with raw queries, since it's really amazing against RawJDBC when it comes to case class mapping through GetResult.
However inside of codegen there is no way to susspress table descriptions:
https://github.com/slick/slick/blob/master/slick-codegen/src/main/scala/slick/codegen/AbstractSourceCodeGenerator.scala

Currently It's only possible to susspress ```GetResult``` but not the other way.
However the other way would be great since that would keep my table file way more clean.

Currently there is an easy way to do that, however one problem remains which is not configurable.

I could change the definitions to:

```override def definitions = Seq[Def]( EntityType, PlainSqlMapper )```

However it will always still add def schema which contains the TableDefinitions.

Also not sure why codegen has the schema method to create the schema, makes no sense to generate code from sql and then sql from code...
Edit thats what I meant: https://github.com/slick/slick/blob/master/slick-codegen/src/main/scala/slick/codegen/AbstractSourceCodeGenerator.scala#L27-L37

that should definitly be configurable.

**Comment by cvogt** [comment]
people asked for the schema method in order to drop tables and recreate them

dont have time to look into suppressing tables right now. consider opening a PR if you have a fix in mind

**Comment by schmitch** [comment]
As said suppressing tables works really good, but I could not get rid of ```schema``` it's hardcoded.

There would be two ways to fix and I will creating a PR, however one would be checking if:

``` def definitions = Seq[Def]( EntityType, PlainSqlMapper, TableClass, TableValue )```

Contains TableClass and TableValues and if not it would just suppress the [ddl/schema](https://github.com/slick/slick/blob/master/slick-codegen/src/main/scala/slick/codegen/AbstractSourceCodeGenerator.scala#L27-L36).
Another way would be to define a setting like ```def hlistEnabled = columns.size > 22``` 
which is maybe called `def ddl: Boolean = true` and if it's false it will suppress [ddl/schema](https://github.com/slick/slick/blob/master/slick-codegen/src/main/scala/slick/codegen/AbstractSourceCodeGenerator.scala#L27-L36)

**Comment by cvogt** [comment]
understood. I suggest sticking to the naming scheme and calling it `ddlEnabled`.

**Comment by schmitch** [comment]
I created an initial PR on https://github.com/slick/slick/pull/1185 however I can't run testkit locally somehow, I need to check why it's failing.

**Comment by schmitch** [comment]
Fixed in https://github.com/slick/slick/commit/85df538db0ab6d6ff4b5598026396d0de0ff74d2
