### ISSUE TITLE
@StaticDatabaseConfig resolves fine in SBT but not ScalaIDE

### ISSUE THREAD

**Issue by saosebastiao** [slick/slick#1188]
I have been testing out the typed SQL, and everything is working fine when compiling in SBT, but when I try to use the ScalaIDE I get the following error

**Cannot load @StaticDatabaseConfig("file:src/main/resources/application.conf#tsql"): No configuration setting found for key 'tsql'**

My src/main/resources/application.conf:

	tsql {
		driver="slick.driver.PostgresDriver$"
	    dataSourceClass = "org.postgresql.ds.PGSimpleDataSource"
		db {
			driver="org.postgresql.Driver"
			url="jdbc:postgresql://localhost/tabster_local"
			user="test"
			password="test"
		}
	}

My Code:

    import slick.driver.JdbcProfile
    import scala.concurrent.{Future, Await}
    import scala.concurrent.ExecutionContext.Implicits.global
    import scala.concurrent.duration.Duration
    import slick.backend.{DatabaseConfig, StaticDatabaseConfig}
    
    
    
    @StaticDatabaseConfig("file:src/main/resources/application.conf#tsql")
    object QueryRunner extends App {
      val dc = DatabaseConfig.forAnnotation[JdbcProfile]
      import dc.driver.api._
      val x: DBIO[Seq[(String,String,String,Boolean,Boolean)]] = 
        tsql"""select user_id,password,nickname,is_verified,is_active
              from users"""
      val db = dc.db
      try {
        val a: DBIO[Unit] =
          x.map { s =>
            s.foreach(println)
          }
        val f: Future[Unit] = db.run(a)
        Await.result(f, Duration.Inf)
      } finally db.close
    }

Is there a way to make this work with the ScalaIDE?

**Comment by mielientiev** [comment]
I have the same problem with Intellij IDEA (Scala plugin). If specify full path - everything works fine

**Comment by szeiger** [comment]
This runs as part of the compiler, so paths are probably resolved relative to the Eclipse home dir. Maybe a resource: URL would work better (it doesn't in sbt, which is why we use file: in the examples). You should ask this question in a Scala IDE forum.
