### ISSUE TITLE
DBIO.sequence does not work with Option

### ISSUE THREAD

**Issue by julienrf** [slick/slick#1192]
You should either implement a `sequenceOption[A](maybeAction: Option[DBIO[A]]): DBIO[Option[A]]` method or embrace a `Traverse` typeclass as we can find in [scalaz](https://github.com/scalaz/scalaz/blob/scalaz-seven/core/src/main/scala/scalaz/Traverse.scala) or [cats](https://github.com/non/cats/blob/master/core/src/main/scala/cats/Traverse.scala).

**Comment by nafg** [comment]
You can do
maybeAction.fold(DBIO.successful(Option.empty[A]))(_.map(Some(_)))

**Comment by julienrf** [comment]
Yes I know but I think that could be useful to add it to slick.

**Comment by rfuerst87** [comment]
I'd like to take this a step further as @nafg's suggestion does not work for write queries. If for example `maybeAction` is of type `DBIOAction[Option[A], NoStream, Effect.All]` compiling fails with an error:

```
type mismatch;
[error]  found   : slick.dbio.DBIOAction[Some[A],slick.dbio.NoStream,slick.dbio.Effect.All]
[error]  required: slick.dbio.DBIOAction[Option[A],slick.dbio.NoStream,slick.dbio.Effect]
```

Would it be possible to cover this case as well?

**Comment by d2aborg** [comment]
You can solve the effect problem by typing your fold:

maybeAction.fold(DBIO.successful(Option.empty[A]): DBIOAction[Option[A], NoStream, Effect.Read])(_.map(Some(_)))

... but this is very ugly. It would be nice to have a proper sequence method.

**Comment by nafg** [comment]
+1

**Comment by cvogt** [comment]
`maybeAction.fold(DBIO.successful(Option.empty[A]))(_.map(Option(_)))`

may work as well

**Comment by rfuerst87** [comment]
Thx for all the suggestions. I worked around implementing a small maybe action trait:

```
def maybeAction[A, R](maybe: Option[A])(action: A => DBIO[R])(implicit ex: ExecutionContext) = {
    maybe match {
      case Some(a) => action(a).map(Some(_))
      case _ => DBIO.successful(Option.empty[R])
    }
 }
```

However, built in support for options would be a nice addition to slick IMHO.

**Comment by cvogt** [comment]
I'd be supportive of an addition to Slick here.

**Comment by Diagoras** [comment]
Hoping to have a PR open by the end of the day to resolve this issue.

**Comment by rfuerst87** [comment]
Ok, how about adding a `maybe` function to `DBIOAction` with a signature similar to the function I posted above? Of course with using `DBIOAction` type instead of `DBIO`. If nothing speaks against I'd be happy to create a PR.
