### ISSUE TITLE
Documentation links to edit page on Github don't work

### ISSUE THREAD

**Issue by i-schuetz** [slick/slick#1195]
The links in the documentation to edit the page on Github lead to urls like:

https://github.com/slick/slick/edit/master/src/sphinx/sql-to-slick.rst

but this results in 404. The correct url is:

https://github.com/slick/slick/edit/master/slick/src/sphinx/sql-to-slick.rst

I think the link is here:
https://github.com/slick/slick/blob/e9ab33083bfa1ae642a93d4e52b4ac87b42dc917/slick/src/sphinx/theme/layout.html#L22

Gave it a try to fix it myself, but I couldn't find anywhere the content of theme_github and pagename.

Edit:
I submitted a PR with a possible fix (without CLA, this is a PDF that apparently has to be printed and this is to much work only for this...). I don't know if it's correct, I have no experience with Sphinx and didn't test it. https://github.com/slick/slick/pull/1196

Thanks.

**Comment by szeiger** [comment]
Fixed by https://github.com/slick/slick/pull/1165
