### ISSUE TITLE
Slick extension for HP Vertica database

### ISSUE THREAD

**Issue by anandp504** [slick/slick#1228]
Hi,

We want to interface with the HP Vertica database using slick and noticed that Slick only supports the following databases. Can you please point me to writing a custom extension for Vertica or is there a plan to write an extension for Vertica?

Derby/JavaDB
H2
HSQLDB/HyperSQL
Microsoft Access
MySQL
PostgreSQL
SQLite
DB/2
Oracle
Microsoft SQL Server

@szeiger

**Comment by cvogt** [comment]
@anandp504 No plans for Vertica from our side. 

Look at one of the existing drivers, e.g. MySQL and port it to Vertica https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/driver/MySQLDriver.scala

I am closing this as out of scope here, but we welcome your efforts in adding Vertica support.
