### ISSUE TITLE
Slick produces invalid query in H2 with java.time.Instant mapping

### ISSUE THREAD

**Issue by bomgar** [slick/slick#1238]
A query created by slick does not quote the timestamp. The code that produces this error is here: https://gist.github.com/bomgar/f7e9837551cc852a6022

```sql
select s25."ID", s25."OCCURRED" from "TEST_TABLE" s25 where s25."OCCURRED" <= 1970-01-01T00:00:02.500Z order by s25."OCCURRED"
```

**Comment by szeiger** [comment]
Off the top of my head I'm not sure how the precedence rules work out that this is not a conflict:

```
  protected implicit val instantMappedColumnType: JdbcDriver#BaseColumnType[Instant] = MappedColumnType.base[Instant, Timestamp](
    d => instantToTimeStamp(d),
    d => timeStampToInstant(d)
  )

  protected implicit val instantDriverJdbcType: driver.DriverJdbcType[Instant] = new driver.DriverJdbcType[Instant]() {

    override def sqlType: Int = java.sql.Types.TIMESTAMP

    override def getValue(r: ResultSet, idx: Int): Instant = timeStampToInstant(r.getTimestamp(idx))

    override def setValue(v: Instant, p: PreparedStatement, idx: Int): Unit = p.setTimestamp(idx, instantToTimeStamp(v))

    override def updateValue(v: Instant, r: ResultSet, idx: Int): Unit = r.updateTimestamp(idx, instantToTimeStamp(v))
  }
```

But you have two definitions for Instant types, the first one mapping it to Timestamp. This *should* work properly with literals and we have tests to confirm this. Apparently the second definition get picked and this one simply doesn't implement `valueToSQLLiteral` (the default being `value.toString`), so it's not surprising that the behavior is wrong.

Please reopen if that is not the case.

**Comment by bomgar** [comment]
That solved my problem. Thank you.
