### ISSUE TITLE
Schema Code Generation with Some("""")

### ISSUE THREAD

**Issue by redsnow1992** [slick/slick#1250]
a mysql table with a field which default is set to `""`, in Generated Schema I got `Some("""")` in class define and column define. 
Can someone give me  a method to deal with it?

**Comment by cvogt** [comment]
You can use a customized code generator as described here: http://slick.typesafe.com/doc/3.0.2/code-generation.html#customization The references example hasn't been updated for Slick 3.x yet, but the interesting part is the sbt setup, which should be very similar.

You can probably just patch (extend and override some def) the code generator to fix your case at hand. The proper fix would be overriding a method in the model builder, that creates the model. The problem you have is very likely specific to the JDBC driver you are using for your backend. There is the generic JdbcModelBuilder in Slick, which each driver extends and customizes to patch up the specific JDBC-driver related peculiarities. Here is the MySQL one. https://github.com/slick/slick/blob/3a03e901bf972edba5a0fa89f9c785b33a6feeee/slick/src/main/scala/slick/driver/MySQLDriver.scala#L56 You can extend and override the one from your driver and use that to generate the model you throw into the code generator.

Slick is open source and we rely on community contributions to get rid of issues like this for everyone. Feel encouraged to submit a PR, that solves the issues for all of us :). Also if you happen to upgrade the example to 3.x, please share with the community. Thx!

If you hope for somebody else to pick this up, I am sure they could use more info, like the driver you used, the version of your DBMS, the SQL schema you are using, the exact slick version, etc

**Comment by redsnow1992** [comment]
Thx ahead!
I make the following change and solve it:
```scala
override def Column = new Column(_) {
  override def defaultCode = {
      case Some(v) => s"Some(${defaultCode(v)})"
      case s: String  => "\""+s.replaceAll("\"", """\\"""")+"\""  // change here
      case None      => s"None"
      ....
   }
}
```

**Comment by Sumith1896** [comment]
I'm taking this.

**Comment by trevorsibanda** [comment]
@redsnow1992 can you provide more info - which driver were you using ?

Can the same fix be applied to [https://github.com/slick/slick/blob/master/slick-codegen/src/main/scala/slick/codegen/AbstractSourceCodeGenerator.scala#L172](url) or is this specific to your particular driver.

`case s: String  => "\""+s.replaceAll("\"", """\\"""")+"\""  // change here`

**Comment by cvogt** [comment]
@trevorsibanda from the first comment I read that @redsnow1992 was using mysql. Sounds like a general, driver-independent problem to me though. The code generator seems to no not properly escape characters like `"` in default values. You could validate that with one of the in-memory databases. Adding a field with such a default value to https://github.com/slick/slick/blob/master/slick-testkit/src/codegen/scala/slick/test/codegen/GenerateRoundtripSources.scala may re-produce the problem.

**Comment by trevorsibanda** [comment]
@cvogt I ran the tests and it is a generic driver-independent issue.

Will be placing a PR escaping the characters.
