### ISSUE TITLE
Enable delete and fineBy when compiler read the drivers as two different driver.

### ISSUE THREAD

**Issue by djx314** [slick/slick#1253]
I have wrote a project for some reason <https://github.com/djx314/slick-archer/blob/master/src/main/scala/org/xarcher/slick/ArcherApi.scala> . But it's fail. First I want to implement a trait with all the implicit in driver.api._ and fix some problem. But final I find that the problem still exists, I think it's slick's problem.
There's two issues:
<https://github.com/strongtyped/active-slick/issues/26>
<https://github.com/playframework/play-slick/issues/249>
That's why I write the file above. But I find that the reason is that slick use trait and class by this like
```scala
TypeName.this.Table //Table is a Type
```
There are 3 place I find the problem.
<https://github.com/slick/slick/blob/3.1.0-M2/slick/src/main/scala/slick/profile/RelationalProfile.scala#L38>
<https://github.com/slick/slick/blob/3.1.0-M2/slick/src/main/scala/slick/profile/RelationalProfile.scala#L44>
<https://github.com/slick/slick/blob/3.1.0-M2/slick/src/main/scala/slick/driver/JdbcProfile.scala#L55>
So 5 fountions with Query or TableQuery are effected.
```scala
schema
create
drop
delete
findBy
```
When scala read the drivers as two different driver at the compelete time, the problem will happen(See the issues I provide above).
Some times we can define the driver as JdbcProfile to avoid this problem. But if I use slick-pg <https://github.com/tminglei/slick-pg> and so on, I must use a custom driver type to use some new data type(like jsonType). So now I can just trait, trait, and trait.
Now talk about the 5 functions. Because of codegen, I think "schema", "create", "drop" is unuseful. But "delete" and "findBy" is useful. Especially the "delete" function. So I think if "delete" and "findBy" can use dependent type like other implicits, The problem will fix.

**Comment by cvogt** [comment]
instead of describing the details, can you give us a way to reproduce the problem on our own? Nothing speaks more than observing the effect :)

**Comment by djx314** [comment]
Oh! I forgot this important thing.
<https://github.com/djx314/slick-issue/blob/master/src/main/scala/org/xarcher/slick/issue/Model.scala#L47>
Here's the code, the `delete2` method complete error. Hope for fix.

**Comment by szeiger** [comment]
Could the solution be to use the correct type ascription in client code? I ran into a similar problem with the code generator recently: https://github.com/slick/slick/commit/5ca0e5cbd9b91740ed9554d5078f8cfa8f0c89e3

**Comment by djx314** [comment]
Is it possible to change the implicit type param here
<https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/driver/JdbcProfile.scala#L55>
to like this ?
```scala
implicit def queryDeleteActionExtensionMethods[C[_]](q: slick.lifted.Query[_ <: slick.profile.RelationalTableComponent#Table[_], _, C]): DeleteActionExtensionMethods =
      createDeleteActionExtensionMethods(deleteCompiler.run(q.toNode).tree, ())
```
If it's possible, I think it's the best change to fix this. But I am afraid of that it will break slick's design.

**Comment by djx314** [comment]
https://github.com/djx314/slick/commit/b0910850ccad272706207246ac669dbad9a94393
Have a test with this, luckly that the delete implicit(def createDeleteActionExtensionMethods) doesn't need a specific Table type. It compile success, but I don't have the environment to test it. And schema, create, drop, findBy can't do like this because it need a specific type define in driver.
But I think just delete is need for use for runtime.
Schema, create, drop only use for dev environment.
But I don't know if this will bring other bugs to slick, just have a look.

**Comment by szeiger** [comment]
I think this should work. While the current path-dependent types can be considered correct, we cannot enforce this path-dependence in most places anyway (e.g. `.result` takes any `Query`, no matter where the tables come from), so it doesn't make much sense to enforce it only for `.delete` and .`findBy`.

**Comment by cvogt** [comment]
Also see this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scalaquery/JMnNfuPL8T4/-wo_GyX0JgAJ
The solution seems to be using `Table` instead of `AbstractTable`
