### ISSUE TITLE
slick 3.0. mapping custom fields from case class

### ISSUE THREAD

**Issue by initmax** [slick/slick#1270]
case class:

`     case class H(
    id: Option[Long] = None,
    idUser: Option[Long] = None,
    title: Option[String] = None,
    ...) `

slick table: 

    `class TH(tag: Tag) extends Table[H](tag, "H") {
    
      def id = column[Long]("ID", O.PrimaryKey, O.AutoInc)
    
      def idUser = column[Long]("ID_USER")
    
      foreignKey("USER_FK", idUser, TableQuery[TUser])(_.id, onUpdate = ForeignKeyAction.Restrict, onDelete = ForeignKeyAction.Cascade)
    
      def * = (id, idUser) <>( {
        case (id: Option[Long], idUser: Option[Long]) => H(id, idUser)
      }, { th: TH => Some((th.id, th.idUser)) })
    }`

 Got compilation error.

```
 Error:Play 2 Compiler:    def * = (id, idUser) <>( {
    Error:Play 2 Compiler:                             ^
    Error:Play 2 Compiler: 
       }, { hq: TH => Some((hq.id, hq.idUser)) })
                               ^
    No matching Shape found.
    Error:Play 2 Compiler:  Slick does not know how to map the given types.
    Error:Play 2 Compiler: 
     Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
       Required level: slick.lifted.FlatShapeLevel
          Source type: (slick.lifted.Rep[Long], slick.lifted.Rep[Long])
    Error:Play 2 Compiler: 
        Unpacked type: (slick.lifted.Rep[Long], slick.lifted.Rep[Long])
          Packed type: Any
       def * = (id, idUser) <>( {
    Error:Play 2 Compiler:                         ^
    Error:Play 2 Compiler: 
     (compile:compileIncremental) Compilation failed
     Total time: 9 s, completed Sep 3, 2015 11:58:13 AM
    
    Error:(88, -1) Play 2 Compiler: 
     missing parameter type for expanded function
     The argument types of an anonymous function must be fully known. (SLS 8.5)
     Expected type was: ? => ?
```
Could you please clarify how can I map properties in the correct way ?

**Comment by szeiger** [comment]
`The argument types of an anonymous function must be fully known` is key here. You need type annotations for those PartialFunctions.
