### ISSUE TITLE
Slick 3.0 transaction scope at a request level

### ISSUE THREAD

**Issue by hardvain** [slick/slick#1273]
I am using slick 3.0 in play 2 app. How to execute all the queries and inserts in slick with transaction at a request level? Consider the following pseudo code

```
object CoursesController extends Controller {
 
  def add = Action{ request =>
    val course: Course = Course(None,"name","subjects",200F,"standard")
    Await.result(db.run(courses += course),Duration.Inf)
    throw new Exception
    Ok(1.toString)
  }
}
```

Though I intentionally throw an exception, the entity is persisted in the DB. I would like to rollback all db actions run inside an play action method when there is an exception at any point till the response is successful. How to achieve this?

**Comment by szeiger** [comment]
Never use Await in a Play app. Thread everything through DBIO. Maybe some extra convenience could be added to play-slick to make this simpler. Might be worthwhile opening a ticket there.

**Comment by schmitch** [comment]
Maybe an example code would help. Ie the following will work @hardvain 

```
  def add = Action.async{ request =>
    val course: Course = Course(None,"name","subjects",200F,"standard")
    db.run((for { data <- courses += course; _ = throw new Exception} yield  data).transactionally)
    Ok(1.toString)
  }
```

Currently this is not documented very good especially not when you want to add future calls like database insert, webservice call, database insert in a transaction. (DBIO.from, is undocumented aswell)

**Comment by hardvain** [comment]
@szeiger I used await just for example purposes. Even without a blocking call using await, I am having the same problem. The entity gets persisted even after the exception.

@schmitch This will work if the 3rd line is the only line where I interact with the DB. But what if I call another method after that and it also interacts with the db. How will I include all db interactions under on transaction? Ideally I want to specify the transaction scope at a play request level only once and have slick handle all db interactions inside that request in that transaction. So that if there is an exception at any point in the request life cycle, I ll have all my changes rolled back. Is this possible? Am I missing anything?

**Comment by hardvain** [comment]
To give an example, 
```
def add = Action { request =>
    val course: Course = Course(None, "name", "subjects", 200F, "standard")
    db.run((courses += course).transactionally)
    someMethod()
    Ok(1.toString)
  }
def someMethod(): Unit = db.run((courses.delete).transactionally)

```

In the above snippet, if there is an exception inside `someMethod()` I want the changes by `db.run((courses += course).transactionally)` to also be rolled back.
