### ISSUE TITLE
Slick2/3: setAutoCommit can fail at end of transaction, swallowing the real error

### ISSUE THREAD

**Issue by slorber** [slick/slick#1279]
At the end of a transaction, calling `conn.setAutoCommit(true)` can fail.

![autocommit](https://cloud.githubusercontent.com/assets/749374/9767395/4ded7c5a-571e-11e5-818b-044829fe1b04.png)

We use this transaction in a temporary SQL import (obviously unsafe so it will not ship once in production).

It is very probable that some data had a problem and could not be inserted, or the connection timed out or something similar. I suspect a rollback to have occured.

The problem is that the exception thrown by the finally block swallows the exception that should probably normally be thrown.

I suggest wrapping the `setAutoCommit(true)` in a try/catch block, and eventually make use of this JDK7 method: `Throwable.addSuppressed(ex)`

In Slick 2 the code was:

```scala
def withTransaction[T](f: => T): T = if(inTransaction) f else {
      conn.setAutoCommit(false)
      inTransaction = true
      try {
        var done = false
        try {
          doRollback = false
          val res = f
          if(doRollback) conn.rollback()
          else conn.commit()
          done = true
          res
        } finally if(!done) conn.rollback()
      } finally {
        conn.setAutoCommit(true)
        inTransaction = false
      }
    }
```

In Slick 3:

```scala
def withTransaction[T](f: => T): T = if(isInTransaction) f else {
      startInTransaction
      try {
        var done = false
        try {
          doRollback = false
          val res = f
          if(doRollback) conn.rollback()
          else conn.commit()
          done = true
          res
        } finally if(!done) conn.rollback()
      } finally endInTransaction()
    }

    private[slick] def startInTransaction: Unit = {
      if(!isInTransaction) conn.setAutoCommit(false)
      inTransactionally += 1
    }

    private[slick] def endInTransaction(f: => Unit): Unit = {
      inTransactionally -= 1
      if(!isInTransaction) try f finally conn.setAutoCommit(true)
    }
```

**Comment by szeiger** [comment]
I checked the code paths in the new API and it looks OK there. Have you tried doing this with DBIOActions? As far as I can see the only place where the method is still used in 3.1 is the client-side upsert emulation. I think we should change that to use DBIO composition, too, and remove `withTransaction` entirely.

**Comment by szeiger** [comment]
Ah, that won't work. insertOrUpdate needs to return a DriverAction, so it has to perform the transaction handling internally.

**Comment by slorber** [comment]
@szeiger actually I'm still only on Slick 2, just took a quick look at Slick3 to check if the bug may already be corrected, but I don't know Slick 3 API yet

**Comment by szeiger** [comment]
You mentioned imports, so if you have something like `DBIO.seq(t += data1, t += data2, ...).transactionally`, that should indeed work in 3.0. It only fails for upserts or if you use `withTransaction` manually (which is deprecated in 3.0 and removed in 3.1).

**Comment by slorber** [comment]
Ok i did not know about that deprecation btw i thought it was still used.
