### ISSUE TITLE
check if stream consumer results in Future

### ISSUE THREAD

**Issue by gaydenko** [slick/slick#1286]
I guess it would be handy to check if `f(t)` here

https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/backend/DatabasePublisher.scala#L48

is already `Future[_]`. Everybody is reactive now, even a consumer :)

**Comment by gaydenko** [comment]
Probably I must to say a couple of words to motivate suggested change. The thing is, at the case consumer supplies `f()` returning `Future[_]` we have got false `Future` completion. It results in too early request to the next stream element. At the stream completion we immediately get finished stream and it can be a sign to terminate the program. But we still have uncompleted `Future`s! To summarize, with current code we lose data.

(P.S. I have describe real life use case)

**Comment by szeiger** [comment]
Hm, I'd argue that DatabasePublisher.foreach works as specified and is just not the right tool for more advanced use cases. It's mostly meant for sample/tutorial code and debugging (`myPublisher.foreach(println)`). For more advanced stream traversal we already have Akka streams and it is not a goal of Slick to provide a separate implementation.

**Comment by gaydenko** [comment]
@szeiger , Akka streams documentation emphasize few times reactive stream API is an implementation details and says user must use Source, Flow, Sink instead of Publisher, Processor, Subscriber, if I understand well. So, in terms of official Akka API there isn't relation with Slick yet. Probably I have missed something obvious, haven't I?

**Comment by szeiger** [comment]
It's just `Source(publisher)` to use it with Akka Streams. See https://github.com/typesafehub/slick-akka-webinar/blob/master/src/main/scala/EtlDemo.scala for an example. Calling Reactive Streams an implementation detail is IMHO misleading. It's a low-level interop protocol with the purpose of allowing streams to propagate through different libraries, i.e. getting a `Publisher` from one and consuming it with another, in the case of Akka Streams by wrapping it in a `Source`.

**Comment by gaydenko** [comment]
> It's just Source(publisher)

Aha, OK, I see. `Future` flattening would permit to avoid Akka streams using at all at many use cases, I guess. But to be a pedant, you are right, source creation is that relation with Slick I have missed. So, closing the issue. If I understand correctly, `foreach` implementation will be kept intact, so, am forced to use Akka streams.

> Calling Reactive Streams an implementation detail is IMHO misleading

Yes, it's really named so in "Design Principles behind Akka Streams" chapter :) But I don't see how this naming guess low reactive streams API's value in general.

**Comment by szeiger** [comment]
I suppose it can be called an implementation detail in the sense that end users should treat a `Publisher` as a black box. The goal is not that they should never see a `Publisher` at all (this is very much required for interop) but that they use higher-level abstractions like Akka Streams to do anything useful with it. End users should not have to call any methods or implement any interfaces defined by the Reactive Streams API.

**Comment by gaydenko** [comment]
It's nice treatment :)

**Comment by joprice** [comment]
I ran into this same issue and after reading this post, ended up copying the `foreach` method into a new implicit class, renaming it `foreachF`, modified it to take a function that returns `Future`, and change this line to not wrap the function call in a future.  https://github.com/slick/slick/blob/408f2e55aa0a7553a445c83b7ee5ef159f805694/slick/src/main/scala/slick/basic/DatabasePublisher.scala#L49

This allows me to sequence the async processing correctly, one after the other. Do you see any problems with that?
