### ISSUE TITLE
When reaching end of carousel, slick doesn't cycle images

### ISSUE THREAD

**Issue by Anruin** [slick/slick#1291]
Greetings, I've got issue with slider that goes beyond the main content (960px) by width.

Issue is that when I'm scrolling images, and reaching end, it shows only last and first one in the cycle, and doesn't show next images after first.

So I see only last and first image, and only after I scroll again, suddenly rest of images appear after first one.

Here is my setup:
```javascript
$slider.slick({
	infinite: true,
	variableWidth: true,
	arrows: true,
	prevArrow: null,
	draggable: false
});
```

I have tried to change slides to scroll, and slides to show, but on different screen sizes they lead to bad behavior, when it skips slides.

Here is the page with slider: http://mag.verstak.ru/index_en.html

Is there any solution for my case? Thanks.

**Comment by cvogt** [comment]
wrong project, this is slick the scala db library

**Comment by Anruin** [comment]
Yeah, sorry, just spotted.
