### ISSUE TITLE
Add strip margin functionality to SQL-interpolated strings

### ISSUE THREAD

**Issue by mwegrz** [slick/slick#1309]
When using standard string interpolation on multiline strings in Scala one can delimit margins by beginning all lines after the first with the pipe symbol (or other, arbitrary char) and then get the margin stripped with `stripMargin` methods. Similar methods are missing on SQL-interpolated strings in Slick. Striping margins would allow one to build a nicely formatted query as in the following example:

``` scala
val id = 1
val query1 = sql"""select 1,
                  |       2
                  |from test
                  |where id = $id""".stripMargin
val query2 = sql"""select 1,
                  !       2
                  !from test
                  !where id = $id""".stripMargin('!')
```

**Comment by cvogt** [comment]
See #1311 for some more motivation

**Comment by cvogt** [comment]
merged

**Comment by feoktant** [comment]
Could this be also implemented for `sqlu`?
