### ISSUE TITLE
add DBIOAction.flatten

### ISSUE THREAD

**Issue by hepin1989** [slick/slick#1329]
like ```flatten```.

**Comment by cvogt** [comment]
should be easy to implement using flatMap. how about a PR :)?

**Comment by hepin1989** [comment]
@cvogt yes,but If it have one would be nice in sometime.
Future in scala 2.12 add flatten too:)

**Comment by cvogt** [comment]
@hepin1989 don't fully understand. Yes flatten would be nice. I was proposing you implement it :).

**Comment by hepin1989** [comment]
@cvogt I think this one could be closed.

**Comment by szeiger** [comment]
Fixed by #1331
