### ISSUE TITLE
add sbt-scalariform to project's plugin

### ISSUE THREAD

**Issue by hepin1989** [slick/slick#1332]
By this way ,the form will be the same for all the PR and the whole project I think.

**Comment by cvogt** [comment]
@szeiger We have tried and had rather good experience with scalariform at @xdotai with the right, liberal settings. So this may be worth a thought. Git blame disrupting though.

Low priority in my eyes, though

**Comment by SethTisue** [comment]
scalariform is pretty dead these days.

adding Scalafix would be a possibility. if a new lead maintainer steps up, they could decide to add it. given the current maintenance status (#2183), I think the downside (wiping out the `git blame` history)
exceeds any upside
