### ISSUE TITLE
3.1 regression bug when yielding Rep.None and a Table

### ISSUE THREAD

**Issue by timgautier** [slick/slick#1345]
It appears that when a query yields both a table and a Rep.None an `Unreachable reference` exception is thrown. I've verified that this worked in 3.0.

For example given a table `t` that has an `id` column this query will not work:

    for {
      c <- t
    } yield (c, Rep.None[Int])

But this query will:

    for {
      c <- t
    } yield (c.id, Rep.None[Int])

The culprit appears to be the `ExpandTables` phase of the compiler. If a star expansion isn't required, the resulting tree has a `LiteralNode` of `None`, but if star expansion is required by the query, the `LiteralNode` is expanded to an `OptionFold` of which the `OptionApply` contains an invalid `Ref`.

I've written a simple test that exposes the bug. I'll submit that as a pull request.

**Comment by szeiger** [comment]
The problem seems to be that `expandSums`, which would correctly rewrite this code, never runs because `assignUniqueSymbols` initially determines that the AST contains no nested Options even though `expandTables` creates a nested Option at a later point.
