### ISSUE TITLE
Getting Shape not found error while using for comprehension with combination of Tuple and HList

### ISSUE THREAD

**Issue by nimeshjivani** [slick/slick#1359]
I am using slick 3.1.0. I am trying to use for comprehension like below:
```
for{
  a <- T.A
  b <- T.B if b.xyz === a.abc
} yield a.x1 :: a.x2 :: a.x3 ... :: a.x20 :: b.x1 :: b.x2 :: .. :: b.x20
```
Here T.A and T.B both are mapped using Tuple but the table in which i want to insert is mapped using HList.

Then using this HList for insert into table using forceInsertQuery but it is throwing error of No matching Shape found on for comprehension of b (Line 3 of code). If I start using Tuple and insert only to few columns, it is compiling successfully.

**Comment by cvogt** [comment]
If you want somebody to look at it, this needs a better description. Like the full error message. A full code sample to reproduce the problem. Ideally a small github project that can be cloned to show the error.

**Comment by nimeshjivani** [comment]
I managed to find my mistake. This was happening because of confusion between HList from slick and scala package.
