### ISSUE TITLE
slick 3.1 multi inner join problem

### ISSUE THREAD

**Issue by bthibault** [slick/slick#1361]
```scala
val q1 = tutorialsteps
        .joinLeft(phoneScreenImages)
        .on((tutorialsteps, phoneScreenImages) => {tutorialsteps.screentypefk === phoneScreenImages.screentypefk && phoneScreenImages.phonefk === phonefk})
        .joinLeft(buttonScreenImages)
        .on((tutorialsteps, buttonScreenImages) => { buttonScreenImages.buttontypefk === tutorialsteps._1.buttontypefk && buttonScreenImages.phonefk === phonefk})
        .filter(_._1._1.tutorialfk === id)
````

```sql
select x2.`screentypefk`, x3.x4, x5.`ButtonTypeFK`, x3.x6, x2.`outputOrder`, x2.`tutorialfk`, x5.`PhoneFK`, x5.`ButtonXSize`, x5.`ButtonYSize`, x5.`ButtonXUpperLeft`, x3.x7, x3.x8, x5.`PK`, x3.x9, x2.`orientation`, x2.`image_location`, x5.`PhoneScreenFK`, x3.x10, x3.x11, x2.`animation_JSON`, x5.`ButtonYUpperLeft`, x2.`step`, x3.x12, x2.`buttontypefk`, x2.`image_file`, x3.x13 from `tutorialsteps` x2 left join (select 1 as x12, `ImageLocation` as x4, `ScreenXSize` as x6, `ScreenYSize` as x8, `PK` as x10, `PhoneFK` as x11, `ScreenYUpperLeft` as x7, `ScreenXUpperLeft` as x13, `ScreenTypeFK` as x9 from `phonescreenimage`) x3 on (x2.`screentypefk` = x3.x9) and (x3.x11 = 2127) left join `buttonscreenimage` x5 on (x5.`ButtonTypeFK` = x2.`buttontypefk`) and (x5.`PhoneFK` = 2127) where x2.`tutorialfk` = xxx
````

Attaching screen shot output of debug mode, where it lists column x14, x15 ... that doesn't translate to anything I can reference in slick 

![screen-shot-2015-11-13-at-1 56 31-pm](https://cloud.githubusercontent.com/assets/2286106/11183264/6cb06aba-8c36-11e5-9a95-44dbeff19e55.png)

**Comment by bthibault** [comment]
using mysql ... i've seen multiple issues related to inner join in older versions, so i'm not exactly sure where this falls.

**Comment by szeiger** [comment]
Please provide a test case (e.g. a patch for JoinTest) to demonstrate the problem. From the description it's not clear to me what the issue is. It doesn't seem to be illegal SQL or the known mult-join regression (which only affects performance), and the structure of the generated statement looks correct.

PS: `-Dslick.sqlIndent=true` makes the statements much more readable.

**Comment by bthibault** [comment]
closing this. was able to resolve with help on gitter
