### ISSUE TITLE
Slick Case If Then construct creating invalid sql query

### ISSUE THREAD

**Issue by nimeshjivani** [slick/slick#1364]
version: 3.1.0
I have been using Case If .. Then.. Else construct to add case when in sql

Balance Table information:
balanceType: Rep[String]
source: Rep[Option[String]]
code: Rep[String]
name: Rep[Option[String]]

```
val query = Tables.Balance.map(x=> (x.balanceType, Case.If(x.balanceType === "A").Then(x.source)(OptionMapper2.getOptionMapper2OO, H2Driver.api.stringColumnType).Else(x.code.?))).result
println(query.statements.mkString(","))
```

Sql being generated:
select "BALANCE_TYPE", (case when ("BALANCE_TYPE" = 'A') then "SOURCE" else (1, "CODE") end) from "SCH"."BALANCE"

This doesn't look like a correct SQL in else part of case when construct.

If I use Rep[Option[String]] field instead in Else case then:
```
val query = Tables.Balance.map(x=> (x.balanceType, Case.If(x.balanceType === "A").Then(x.source)(OptionMapper2.getOptionMapper2OO, H2Driver.api.stringColumnType).Else(x.name))).result
println(query.statements.mkString(","))
```
In this case it is correctly generating sql:
select "BALANCE_TYPE", (case when ("BALANCE_TYPE" = 'A') then "SOURCE" else "NAME" end) from "SCH"."BALANCE"

Even strange thing- if i just change the sequence of If Else in first query as follow:
```
val query = Tables.Balance.map(x=> (x.balanceType, Case.If(x.balanceType === "A").Then(xs.code.?)(OptionMapper2.getOptionMapper2OO, H2Driver.api.stringColumnType).Else(x.source))).result
println(query.statements.mkString(","))
```
Then it is throwing run time exception:
Caused by: slick.SlickException: No type for symbol _1 found in Option[String']

**Comment by szeiger** [comment]
Another issue: Ambiguous implicits when mixing Option and non-Option results:
```
[error] /Users/szeiger/code/slick/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/RelationalMiscTest.scala:110: ambiguous implicit values:
[error]  both method getOptionMapper2TO in object OptionMapper2 of type [B1, B2, BR](implicit evidence$2: slick.ast.BaseTypedType[B2])slick.lifted.OptionMapper2[B1,B2,BR,B1,Option[B2],Option[BR]]
[error]  and method getOptionMapper2OO in object OptionMapper2 of type [B1, B2, BR](implicit evidence$4: slick.ast.BaseTypedType[B2])slick.lifted.OptionMapper2[B1,B2,BR,Option[B1],Option[B2],Option[BR]]
[error]  match expected type slick.lifted.OptionMapper2[B,B,B,Option[Int],Option[Int],Option[Int]]
[error]       q4a = t1s.map { t1 => Case.If(t1.a < 3) Then t1.b Else t1.a }
[error]                                               ^
```

**Comment by cvogt** [comment]
@nimeshjivani please check if this fixes your issue. if not please re-open.   (Easiest way to check is a checkout of slick and publish-local. You may want to adjust the version number to -SNAPSHOT, otherwise your local cache may overshadow the version released to maven. )
