### ISSUE TITLE
MySQL creating schemas is not generating an acceptable SQL

### ISSUE THREAD

**Issue by pnakibar** [slick/slick#1376]
Hi,
I'm trying to connect to a MySQL database, and the the TableQuery[T].schema.create is generating a not acceptable DDL.

_I'm trying in an example_

``` scala
class Suppliers(tag: Tag)
  extends Table[(Int, String, String, String, String, String)](tag, "suppliers") {

  // This is the primary key column:
  def id: Rep[Int] = column[Int]("sup_id", O.PrimaryKey)
  def name: Rep[String] = column[String]("sup_name")
  def street: Rep[String] = column[String]("street")
  def city: Rep[String] = column[String]("city")
  def state: Rep[String] = column[String]("state")
  def zip: Rep[String] = column[String]("zip")

  // Every table needs a * projection with the same type as the table's type parameter
  def * : ProvenShape[(Int, String, String, String, String, String)] =
    (id, name, street, city, state, zip)
}
```

When I use the _TableQuery[Suppliers].schema.create.statements_ I can see that the generated SQL is this:

``` sql
create table `suppliers` (`sup_id` INTEGER NOT NULL PRIMARY KEY,`sup_name` VARCHAR NOT NULL,`street` VARCHAR NOT NULL,`city` VARCHAR NOT NULL,`state` VARCHAR NOT NULL,`zip` VARCHAR NOT NULL)
```

The problem is at the **VARCHAR** that doesn't have a size, like **VARCHAR(64)**.

If I run the _{...}.schema.create_ accordingly, I get a:

> MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NOT NULL,`street` VARCHAR NOT NULL,`city` VARCHAR NOT NULL,`state` VARCHAR NOT N' at line 1

Is there any workaround for this problem?

**Comment by xavier-fernandez** [comment]
Good morning @pnakibar,

You can add 'O.Lenght(Int)' as a column constraint, just after the column name declaration.

You can also declare any other constraints between that parenthesis. 

For example:

```scala
class SuppliersTable(tag: Tag) extends Table[(Int, String)](tag, "suppliers") {

  // This is the primary key column:
  def id: Rep[Int] = column[Int]("sup_id", O.PrimaryKey, O.AutoInc)
  def name: Rep[String] = column[String]("sup_name", O.Lenght(64), NotNull)

  // Every table needs a * projection with the same type as the table's type parameter
  def * : ProvenShape[(Int, String)] = (id.?, name) <> (Supplier.tupled, Supplier.unapply)
}

case class Supplier (id : Option[Int], name : String)
```
