### ISSUE TITLE
Multiple DAO operation in one transaction synchronously, use slick 3.0

### ISSUE THREAD

**Issue by ans76** [slick/slick#1404]
I'm confused about how to make multiple dao operation in one transaction, I find example like this:

```
def doSomething(???) = (for {
  _ <- userDao.add(???) 
  _ <- addressDao.doSomething(???)
} yield()).transactionally
```

it looks handy, but I want `userDao.add` returned value like id or something, use return value do some special process, for example `hash(userDao.add)` as `addressDao.doSomething` arguments.

enterily possible:

```
def doSomething(???) = (for {
  _ <- userDao.add(???)  // return id
// hash (id) or something else
  _ <- addressDao.doSomething(hash(id))
} yield()).transactionally
```

I'm not sure is the structure correct, or it's need whole different way to do it, please tell me)

Thanks

**Comment by djx314** [comment]
This is not an issue, you can look for the document on <http://slick.typesafe.com>
In my option, DBIO likes Future.
And here's the insert document.
<http://slick.typesafe.com/doc/3.1.1/queries.html#inserting>

**Comment by margussipria** [comment]
There is google group where you would have probably got faster answer (https://groups.google.com/forum/#!forum/scalaquery)... and maybe you have. In this case if add is returning id then you should just capture it `id <- userDao.add(???)  // return id` and not use `_` for ignoring return values.
