### ISSUE TITLE
afterChange event is being fired on Chrome Android when touching the slide and scrolling down.

### ISSUE THREAD

**Issue by marb19** [slick/slick#1418]
Hey, I am building a site that requires to load specific content depending on the current slide. It is working nicely but found an issue while working with Android devices and Chrome.

I am refreshing the content by doing a jquery load every time the afterChange event is fired. The thing is that the event is fired in Android Chrome when you touch the slider and scroll down, even if you didn't change slide.

**Comment by cvogt** [comment]
wrong project. this is the scala database library
