### ISSUE TITLE
JdbcModelBuilder issue causes CodeGen for MySQL to not supply schema names

### ISSUE THREAD

**Issue by chadjaros** [slick/slick#1419]
The model being extracted by driver.createModel for a mysql database is incorrectly setting the schema name in the table metadata name. The schema name is being set into the `catalog` field, and `None` is being set into the `schema` field.

This causes the code generator to omit the schema name in the generated Table classes in the Tables.scala files.

**Comment by chadjaros** [comment]
I was able to get things to write properly by massaging the model metadata using the code below:

    def fixName(name: QualifiedName): QualifiedName = {
        name.copy(schema = name.catalog, catalog = name.schema)
    }

    def fixFk(fk: m.ForeignKey): m.ForeignKey = {
        fk.copy(
            referencedTable = fixName(fk.referencedTable),
            referencedColumns = fk.referencedColumns.map(fixColumn),
            referencingTable = fixName(fk.referencingTable),
            referencingColumns = fk.referencingColumns.map(fixColumn)
        )
    }

    def fixColumn(col: m.Column): m.Column = {
        col.copy(table = fixName(col.table))
    }

    def fixTable(table: m.Table): m.Table = {
        val newName = fixName(table.name)
        table.copy(
            name = newName,
            columns = table.columns.map(_.copy(table = newName)),
            primaryKey = table.primaryKey.map(pk => pk.copy(table = newName, columns = pk.columns.map(fixColumn))),
            foreignKeys = table.foreignKeys.map(fixFk),
            indices = table.indices.map(idx => idx.copy(table = newName, columns = idx.columns.map(fixColumn)))
        )
    }

    def fixSchema(model: m.Model): m.Model = {
        m.Model(model.tables.map(fixTable))
    }

Obviously not a long term solution

**Comment by trevorsibanda** [comment]
@chadjaros  @cvogt  I'd like to work on this.

I'm not fully understanding, could you give me some more info on how to recreate the bug. 

Sample code would be ideal thanks

**Comment by chadjaros** [comment]
When I create tables in a MySQL schema, a bug in the code generator prevents the schema name from being properly added into the generated Dao code.

    CREATE TABLE IF NOT EXISTS my_schema.my_table (
        col_1              VARCHAR(36)  NOT NULL,
        col_2           VARCHAR(190),
   
        CONSTRAINT user_pk PRIMARY KEY (col_1),
    );

The bug in the code generator sets "my_schema" as the  `catalog` property in all `QualifiedName` instances throughout, rather than as the `schema` property.

The generated code is: 

    class MyTable(_tableTag: Tag) extends Table[MyTableRow](_tableTag, None, "my_table") {

where it should include the schema in the table declaration:

    class MyTable(_tableTag: Tag) extends Table[MyTableRow](_tableTag, Some("my_schema"), "my_table") {

A workaround is listed above to correct the metadata, but another option is to have all tables in a single schema, and to set that schema as default in your connection string.

This connection string should in theory work to access tables in multiple schema, but it doesn't work at all:

    jdbc:mysql://mysql.docker:3306/

Adding the default schema allows access to tables in a single schema, but precludes access to tables in any other schema:

     jdbc:mysql://mysql.docker:3306/my_schema

**Comment by cvogt** [comment]
fixed in #1528

**Comment by edmondo1984** [comment]
Why would you want the schema to be included in the table generated code? Not to be able to run your code towards a different schema in a different environment? We have two QA setup, they share the same mySQL so we created two databases, myDb1-qa and myDb-qa2, but we generated the classes against myDb1 and they do not work anymore
