### ISSUE TITLE
GSOC 2016 Official Scala Website

### ISSUE THREAD

**Issue by manishbisht** [slick/slick#1423]
Hello Everyone,

I want to make some contributions on Scala. So I have one idea can we make the official website of the GSOC 2016 like on the domain gsoc16.scala-lang.org or the other domain you like. On that page all the details related to mentors and ideas will be put there and we can write there some useful tips for the students to get selected in GSOC 2016.
It will be very useful for the students and also we as the Scala contributor have some place where all the details of the mentor and students can be kept.

Hope you all will like this.

Thanks :)

**Comment by cvogt** [comment]
In the past we have always simply had one page on scala-lang.org

http://scala-lang.org/gsoc/2016.html

It would probably be good to link there from http://scala-lang.org/community/

but apart from that I don't see what needs to be done. I doubt there would be a lot of interest or time dedicated by any Scala dev on such a project. There are more pressing issues generally. Also this is probably a Scala topic, not a slick topic. So I am closing this here.

**Comment by cvogt** [comment]
If you have concrete idea how to improve the content via PR that is of course welcome. In the last years we had more decent applicants than slots, so it worked out.

If you think something is a really good idea... go ahead and build it, but be ready that you will be the strongest believer of your vision and need to pull it through despite other people's suspicions or lack of support.

**Comment by schmitch** [comment]
Wouldn't it be more suitable to deprecate the code-gen and force projects around macro's?

**Comment by cvogt** [comment]
@schmitch I don't think so. codegen is much easier to understand and extend and has no real disadvantage. Why would you want macros?
