### ISSUE TITLE
q.take(n) ++ q produces invalid query

### ISSUE THREAD

**Issue by ahihi** [slick/slick#1424]
Minimal example for Slick 3.1.1:

``` scala
import slick.driver.PostgresDriver.api._
import slick.jdbc.JdbcBackend.Database

import scala.concurrent.Await
import scala.concurrent.duration.Duration

case class Foo(id: Int)

class Foos(tag: Tag) extends Table[Foo](tag, "foos") {
  def id = column[Int]("id", O.PrimaryKey, O.AutoInc)

  def * = id <> (Foo.apply, Foo.unapply)
}

object TestRun extends App {
  val foos = TableQuery[Foos]

  val db = Database.forURL("jdbc:postgresql://localhost/test?user=test")

  /*Await.result(
    db.run(foos.schema.create),
    Duration.Inf
  )*/

  val query = foos.take(1) ++ foos

  val result = Await.result(
    db.run(query.result),
    Duration.Inf
  )

  println(result)
}
```

This generates the query `select "id" as s17 from "foos" limit 1 union all select "id" as s17 from "foos"`, which PostgreSQL does not accept:

```
Exception in thread "main" org.postgresql.util.PSQLException: ERROR: syntax error at or near "union"
```

**Comment by mlangc** [comment]
I've just been hit by the same problem.

**Comment by maquessime** [comment]
it fails also for 
- SQLite
- Hsqldb
- Derby
- H2

validated by adding this test : https://gist.github.com/maquessime/eb98b47bcc061c5fdc4fd518a2e2b0f0
in UnionTest.scala

**Comment by cvogt** [comment]
inlining the test
```
def testUnionWithLimit = {
    val q1 = managersQuery
    val q2 = employeesQuery
    val union = (q1.take(1) ++ q2).sortBy(_._2.asc)

    (for {
      _ <- (managers.schema ++ employees.schema).create
      _ <- managers ++= managersData
      _ <- employees ++= employeesData
      _ <- mark("union", union.result).map(_ shouldBe List((2,"Amy"), (7,"Ben"), (8,"Greg"), (6,"Leonard")))
    } yield ()) andFinally (managers.schema ++ employees.schema).drop
  }
```

**Comment by cvogt** [comment]
@radsaggi now that you are on the query compiler, maybe this is worth a look for later in the summer

**Comment by maquessime** [comment]
@cvogt I'm currently working for a fix for that issue, do you think it is still relevant since @radsaggi will attack that?

thanks

**Comment by radsaggi** [comment]
@maquessime please highlight your progress with solving this. I'll help you wherever you might need help.

**Comment by cvogt** [comment]
@maquessime if you are working on it, great. @radsaggi has lots of other other things on his plate where he can make an impact in Slick. So there is certainly room for more hands. Don't hesitate to ask questions. The query compiler is not easy.

**Comment by maquessime** [comment]
@cvogt @radsaggi cool, will do a PR then, still got issue with derby at the moment.

**Comment by cvogt** [comment]
sounds great :)!

**Comment by radsaggi** [comment]
Being worked upon in #1538

**Comment by sdether** [comment]
Is there an update on the status of this? I just ran across the bug with 3.2.0 and psotgresql and #1538 work seems to have stalled.

**Comment by dwene** [comment]
I just refreshed #1538 by pulling in master and it's passing all the tests. PR is #1795
