### ISSUE TITLE
Release containing drivers for DB2, Oracle and MS SQL Server 

### ISSUE THREAD

**Issue by lutzh** [slick/slick#1441]
Now that the drivers for drivers for DB2, Oracle and MS SQL Server have been merged in PR #1427 - wouldn't it make sense to create a new release containing them? It could be a 3.1.2 release which is identical to 3.1.1 plus the new drivers.

**Comment by mwz** [comment]
It looks like the milestone [3.1.x](https://github.com/slick/slick/milestones/3.1.x) is just round the corner, so I assume it will be released as 3.1.2 once the last two tickets get closed.

**Comment by Elufimov** [comment]
Any update?

**Comment by cvogt** [comment]
not yet bringing it up again

**Comment by cvogt** [comment]
among the maintainers

**Comment by Elufimov** [comment]
@cvogt thx!

**Comment by Elufimov** [comment]
Same question, any update? It's already passed three months from initial post http://slick.lightbend.com/news/2016/02/01/slick-extensions-licensing-change.html

**Comment by mwz** [comment]
In the meantime, feel free to do a local publish =)
