### ISSUE TITLE
Slick 3.1.0: UUIDJdbcType.sqlType for OracleDriver should be defined as java.sql.Types.BINARY

### ISSUE THREAD

**Issue by skapadia** [slick/slick#1446]
In Slick 3.1.0, `com.typesafe.slick.driver.oracle.OracleDriver` overrides `UUIDJdbcType` and sets `sqlType` to `java.sql.Types.OTHER`.  

Inserting a NULL value into a column defined as `Column[Option[UUID]]` (a nullable RAW(32) column), results in this exception: `java.sql.SQLException: Invalid column type: 1111`.  
1111 = `java.sql.Types.OTHER`.

Instead setting this to `java.sql.Types.BINARY` resolves the issue.  Please note this only appears to be an issue when attempting to insert NULLs.   Please see the sample workaround below that we are currently using:

``` scala
import com.typesafe.slick.driver.oracle.OracleDriver

trait CustomOracleDriver extends OracleDriver {

  override val columnTypes = new JdbcTypes

  class JdbcTypes extends super.JdbcTypes {

    override val uuidJdbcType = new UUIDJdbcType

    class UUIDJdbcType extends super.UUIDJdbcType {
      override def sqlType = java.sql.Types.BINARY
    }
  }
}

object CustomOracleDriver extends CustomOracleDriver
```

I do believe `java.sql.Types.BINARY` is the more appropriate JDBC SQL type for Oracle RAW(16) or RAW(32) columns.

I understand that `slick-extensions` is being contributed back to the core (thus I can see `OracleProfile` on the master branch) so I would assume it could be fixed in the next version of Slick (3.2.0 milestone?).

**Comment by smootoo** [comment]
I have a fix and test for this. It is a comprehensive UUID test and highlights and fixes problems with the other profiles too. I challenge the "effort: easy" tag :-) Should have a PR with 24 hours.

**Comment by cvogt** [comment]
@smootoo wow, that's awesome. I guessed the effort of course :).

**Comment by cvogt** [comment]
we may want to target 3.1.x
