### ISSUE TITLE
Codegen with tables over 22  columns

### ISSUE THREAD

**Issue by ergomesh** [slick/slick#1452]
I am having the same problem with any table over 22 columns as this

http://stackoverflow.com/questions/34186932/scala-slick-3-1-0-stackoverflow-error-after-code-generation

getting stackoverflow errors when i include any table with over 22 columns in codegen

`implicit def Table1Row(implicit e0: GR[String], e1: GR[Long], e2: GR[Option[String]]): GR[Table1Row] = GR{
    prs => import prs._
    <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[Long] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[String] :: <<[Long] :: <<[String] :: <<[String] :: <<?[String] :: HNil
  }
  /** Table description of table TABLE1. Objects of this class serve as prototypes for rows in queries. */
  class Table1(_tableTag: Tag) extends Table[Table1Row](_tableTag, Some("Schema"), "TABLE1") {
    def * = x1 :: x2 :: x3 :: x4 :: x5 :: x6 :: x7 :: x8 :: x9 :: x10 :: x11 :: x12 :: x13 :: x14 :: x15 :: x16 :: x17 :: x18 :: x19 :: x20 :: x21 :: x22 :: x23 :: x24 :: x25 :: x26 :: x27 :: x28 :: x29 :: x30 :: x31 :: x32 :: x33 :: x34 :: x35 :: x36 :: x37 :: x38 :: x39 :: x40 :: x41 :: x42 :: x43 :: x44 :: x45 :: x46 :: x47 :: x48 :: x49 :: x50 :: x51 :: x52 :: x53 :: x54 :: HNil
`

**Comment by Skamander** [comment]
Hi,

I had the same problem a while back with a legacy table with around 45 columns. Giving sbt more heap by changing the SBT_OPTS solved the problem.

http://stackoverflow.com/questions/15280839/how-to-set-heap-size-for-sbt

**Comment by ergomesh** [comment]
Great it works now amazing!
