### ISSUE TITLE
Streaming a 'Blob' from the database and to the database

### ISSUE THREAD

**Issue by Fristi** [slick/slick#1455]
The streaming example on the website shows this;

```
val q = for (c <- coffees) yield c.image
val a = q.result
val p1: DatabasePublisher[Blob] = db.stream(a)
val p2: DatabasePublisher[Array[Byte]] = p1.mapResult { b =>
  b.getBytes(0, b.length().toInt)
}
```

This will fetch all bytes in memory. Wouldn't it be a good idea to stream this in chunks? This could be useful for file downloads. Which brings another thing to the table; uploading a file to the database through chunks. I Think this would be useful as well :)

WDYT?

**Comment by szeiger** [comment]
Yes, it would. It seems we didn't have a ticket for this. Here are some notes I posted to an internal mailing list last year:

> I just thought about LOBs in streaming results again. WDYT about providing a higher-level abstraction that can expose the LOB data as a stream Publisher. The Publisher would hand out only a single stream and any such LOB in a result row would have to be consumed or explicitly skipped in order to continue the main result set stream, the main point being that this creates an explicit back-channel which is independent of demand so that buffering would not be an issue. You could e.g. flatMap the nested LOBs into the outer stream while processing the data.

**Comment by Fristi** [comment]
Great stuff, looking forward to it! :+1:
