### ISSUE TITLE
Pages on main Slick site are not up to date

### ISSUE THREAD

**Issue by aholland** [slick/slick#1465]
Reading http://slick.typesafe.com/doc/3.1.1/gettingstarted.html I see a small spelling error.

Feeling helpful, I click "EDIT THIS PAGE ON GITHUB", fork, find the position, and discover that a correction for the error was merged into master back in Dec 2015.

Why let the presented version on typesafe.com lag the github version by so much? If I find further errors, I'll be thinking "hmm, quite possibly fixed already - perhaps I should just get on with my day!". 

Thanks, Anthony

**Comment by cvogt** [comment]
it's a good point. updating the docs is currently tied to releases of slick, which is probably unfortunate. I remember some discussion in this direction to improve the situation, but don't remember the status. @szeiger?
