### ISSUE TITLE
Facing Issue in using Scala + Slick + MySQL+ Akka + Stream (RejectedExecutionException)

### ISSUE THREAD

**Issue by akshaymhetre** [slick/slick#1474]
Please check the detail about this here : 

http://stackoverflow.com/questions/36357565/facing-issue-in-using-scala-slick-mysql-akka-stream

**Comment by d6y** [comment]
@akshaymhetre I see you have an accepted answer on Stackoverflow.  Is it OK to close this issue?

**Comment by cvogt** [comment]
@akshaymhetre please re-open if needed.
