### ISSUE TITLE
add support for mysql insert ignore

### ISSUE THREAD

**Issue by jpertino** [slick/slick#1480]
not much to add to the title
we are currently using the overrideStatements in cases we want to add the ignore keyword to our inserts,
but it would be great to have native support

https://dev.mysql.com/doc/refman/5.5/en/insert.html

**Comment by marak8** [comment]
In SQLite it's

    INSERT OR IGNORE ...

while in MySQL it's just

    INSERT IGNORE

But in both cases it's same.

**Comment by marak8** [comment]
A simple benchmark demonstrating usefulness of `INSERT OR IGNORE` compared to `INSERT OR UPDATE`:

    import java.nio.file.Files
    import java.sql.DriverManager
    import better.files._
    import scala.language.implicitConversions
  
    object Main extends App {
  
      def measureInsert(insertSql: String): Unit = {
        val dml =
          """
          create table if not exists users (
            id integer primary key,
            name text
          );
          """
  
        val tempFile = Files.createTempFile(null, null)
        try {
          for {
            conn <- DriverManager.getConnection("jdbc:sqlite:upsert.db").autoClosed
            dmlStmt <- conn.prepareStatement(dml).autoClosed
            insertStmt <- conn.prepareStatement(insertSql).autoClosed
          } {
            dmlStmt.executeUpdate()
            for (i <- 1 to 1000)
              insertStmt.executeUpdate()
            val start = System.nanoTime()
            for (i <- 1 to 1000)
              insertStmt.executeUpdate()
            val end = System.nanoTime()
            val elapsed = end - start
            println("SQL: " + insertSql)
            println("Elapsed: " + elapsed)
          }
        }
        finally {
          Files.delete(tempFile)
        }
      }
  
      measureInsert("insert or ignore into users values (1, 'John')")
      measureInsert("insert or replace into users values (1, 'John')")
    
    }

Result:

    SQL: insert or ignore into users values (1, 'John')
    Elapsed: 12703976
    SQL: insert or replace into users values (1, 'John')
    Elapsed: 9171434957

`INSERT OR IGNORE` is 721x times faster than `INSERT OR UPDATE`.

**Comment by hvesalai** [comment]
Closing in favour of #1910
