### ISSUE TITLE
query parameter referring to timestamp without time zone column is interpreted in wrong time zone

### ISSUE THREAD

**Issue by theinzel** [slick/slick#1482]
If you have a postgres 9.1.x database table like

CREATE TABLE wind_meter
(
  metering_id character varying(255) NOT NULL,
  forecast_utc_time timestamp(0) without time zone NOT NULL,
  wind_speed real NOT NULL,
  power integer NOT NULL,
  CONSTRAINT wind_meter_pkey PRIMARY KEY (metering_id, forecast_utc_time)
)

that contains data like

"ZP_CR_0199";"2016-02-01 00:00:00";12.3;1169
"ZP_CR_0199";"2016-02-01 00:15:00";12.1;1105
"ZP_CR_0199";"2016-02-01 00:30:00";11.9;1054
"ZP_CR_0199";"2016-02-01 00:45:00";11.8;853
"ZP_CR_0199";"2016-02-01 01:00:00";11.6;915
"ZP_CR_0199";"2016-02-01 01:15:00";11.5;839
"ZP_CR_0199";"2016-02-01 01:30:00";11.4;805
"ZP_CR_0199";"2016-02-01 01:45:00";11.2;876
"ZP_CR_0199";"2016-02-01 02:00:00";11.1;963
"ZP_CR_0199";"2016-02-01 02:15:00";11.1;978

and you write a query that refers to the timestamp without time zone column (forecastTime)

```
for {
  forecast <- forecastTable.sortBy(_.forecastTime)
  if forecast.meteringId.inSet(assets.map(_.meterPointId))
  if forecast.forecastTime >= startTimePoint && forecast.forecastTime < endTimePoint
} yield forecast
```

and 

startTimePoint is a java.sql.Timestamp (Java 7) that is equivalent to this UTC instant: 2016-02-01T**00:00:00**.000Z    

you end up getting a sql query containing

... and (("forecast_utc_time" >= {ts '2016-02-01 **01:00:00**.0'})  ...

which in turn will give you wrong results (starting with wrong time 01:00:00):

"ZP_CR_0199";"2016-02-01 01:00:00";11.6;915

This is probably because the Timestamp's string representation is in _local (german) time_, whereas the sql interprets it in UTC...

```
scala> val i = Instant.parse("2016-02-01T00:00:00.000Z")
i: org.joda.time.Instant = 2016-02-01T00:00:00.000Z

scala> new Timestamp(i.getMillis)
res43: java.sql.Timestamp = 2016-02-01 01:00:00.0

```

**Comment by hvesalai** [comment]
Please post to one of the community forums or re-open if you think this is really a bug.

**Comment by theinzel** [comment]
@hvesalai I can't reopen it, or I don't know where. Yes, this is a bug - how can a bug description be more concise?

**Comment by hvesalai** [comment]
Not a bug. Your database has a column without timezone and so it is interpreted in the local time. The times in the database are thus to be interpreted to be german time, if your system is in german time.

From psql manual:

> Conversions between timestamp without time zone and timestamp with time zone normally assume that the timestamp without time zone value should be taken or given as timezone local time
