### ISSUE TITLE
Release against Scala 2.12.0-M4

### ISSUE THREAD

**Issue by Diagoras** [slick/slick#1490]
Apologies if this issue has already been opened, I was unable to find it if it was.

It'd be nice to see a Slick release compatible with Scala 2.12, but from what I can tell you only support 2.10 and 2.11. Are you planning to support 2.12 in the near future?

**Comment by cvogt** [comment]
We should also get another Milestone out. I'll bring this up among the commiters and we'll try to prioritize this.

**Comment by margussipria** [comment]
Slick 3.2.0-M1 was released against Scala 2.12.0-M5, so this can be closed? I think that nobody is going to release 3.1.x

**Comment by cvogt** [comment]
we'll get another 3.1.x out eventually
