### ISSUE TITLE
Blob to Text conversion?

### ISSUE THREAD

**Issue by hhimanshu** [slick/slick#1495]
Hello there,
I am new to Slick. I have a `MySQL` table mapped as
```
class HealthReport(tag: Tag) extends Table[(Int, Int, Int, String, Timestamp, Blob)](tag, "LogProcessorHealthReport") {

  def id = column[Int]("id")
  def usersId = column[Int]("Users_Id")
  def tenantId = column[Int]("Tenant_Id")
  def ecId = column[String]("EcId")
  def reportedOn = column[Timestamp]("ReportedOn")
  def healthInfo = column[Blob]("HealthInfo")

  def * = (id, usersId, tenantId, ecId, reportedOn, healthInfo)
}
```
I want to read the contents of `healthInfo`, how can I do that?

Thanks

**Comment by cvogt** [comment]
Try `Array[Byte]`. Please let us know if it worked and re-open if it didn't. Thx

**Comment by hhimanshu** [comment]
@cvogt, my apologies, but I am not sure how to use it, could you guide me on how to use it to get back text value?

**Comment by cvogt** [comment]
Use `def healthInfo = column[Array[Byte]]("HealthInfo")`.

You can convert back and forth between Array[Byte] and String after and before querying like this:

```
val bytes:Array[Byte] = "string".getBytes
val string: String = bytes.map(_.toChar).mkString
```

**Comment by hhimanshu** [comment]
Hey @cvogt, thanks a lot.

I changed it to 
```
  def healthInfo = column[Array[Byte]]("HealthInfo")
``

and then ran it as  

```
  def runHealthReport(): Unit = {
    val lpHealthReports: TableQuery[HealthReport] = TableQuery[HealthReport]
    val run: Future[Unit] = db.run(lpHealthReports.map(_.healthInfo.toString.getBytes.map(_.toChar).mkString).result.map(println))

    Await.result(run, Duration.Inf)
  }

```

and the output I got was  

```
(LogProcessorHealthReport Ref @1103243338).HealthInfo, (LogProcessorHealthReport Ref @1103243338).HealthInfo
```

I am not sure if I am doing it right

**Comment by cvogt** [comment]
You'd need to to the conversion after executing the query, meaning either on the DBIOAction of the Future. E.g.

```
  def runHealthReport(): Unit = {
    val lpHealthReports: TableQuery[HealthReport] = TableQuery[HealthReport]
    val run: Future[Unit] = db.run(
      lpHealthReports.map(_.healthInfo).result.map(
        healthInfo => println( healthInfo.map(_.toChar).mkString )
    ))

    Await.result(run, Duration.Inf)
  }

**Comment by hhimanshu** [comment]
I see, however, I see compilation issue as  
```
Error:(32, 48) value toChar is not a member of Array[Byte]
        healthInfo => println(healthInfo.map(_.toChar).mkString)
                                               ^
```

The dependencies that I have are

```
        <dependency>
            <groupId>com.typesafe.slick</groupId>
            <artifactId>slick_2.11</artifactId>
            <version>3.1.1</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-nop</artifactId>
            <version>1.7.21</version>
        </dependency>
        <dependency>
            <groupId>com.typesafe.slick</groupId>
            <artifactId>slick-hikaricp_2.11</artifactId>
            <version>3.1.1</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.38</version>
        </dependency>
```

Do you see anything wrong with it?

**Comment by cvogt** [comment]
Let the type errors help you there :)! I forgot a .map. Try ``healthInfo.map(_.map(_.toChar).mkString)```

**Comment by hhimanshu** [comment]
That worked, Awsome, thanks @cvogt

**Comment by hhimanshu** [comment]
The only last thing, which you may have some idea is that the data is not printed correctly, seems like the encoding is not set

```
Not availabletService Registry Last Updatedt30 minutes 1 secondx, ﾬ￭srjava.util.LinkedHashMap4￀N\l￀￻ZaccessOrderxrjava.util.HashMapￚ￁ￃ`￑F
```

Does that sounds correct? and how can I change the encoding here?

**Comment by cvogt** [comment]
haha, of course. How could I overlook this. Instead of `arrayOfBytes.map(_.toChar).mkString` do `new String(arrayOfBytes)` and it should be fine given your string having the right encoding. Otherwise google "java string array[byte] encoding"
