### ISSUE TITLE
Compiled SQL

### ISSUE THREAD

**Issue by japgolly** [slick/slick#1497]
Hi. According to the docs it's more efficient to wrap repeated queries in `Compiled`. The docs don't how a working example with `sql"..."`. I tried this but it doesn't work:

```scala
import slick.driver.PostgresDriver.api._

Compiled((a: ConstColumn[String]) => sql"select $a from dual".as[String])

// could not find implicit value for parameter e:
//  slick.jdbc.SetParameter[slick.driver.PostgresDriver.api.ConstColumn[String]]
```

**Comment by cvogt** [comment]
@japgolly it is more efficient for queries using the type-safe (lifted embedding) api, because it caches the compiled SQL query. With sql"..." you are already providing a SQL query. No need to compile or cache that somewhere. Maybe the docs weren't clear enough here. What would have helped?

**Comment by japgolly** [comment]
Ah I see, thanks @cvogt, I incorrectly assumed it was creating `PreparedStatement`s. In which case, using Slick how would I prepare `sql"..."` output into a `PreparedStatement`? Or is it cached by the db driver? I can't remember.

**Comment by cvogt** [comment]
Slick always uses prepared statements and it would be cached by the driver, but depending on the driver you have to make it is enabled. (cc @szeiger)

**Comment by cvogt** [comment]
Correction: You need to make sure it is enabled in your thread pool!

**Comment by japgolly** [comment]
Righto. Thanks again @cvogt!

**Comment by cvogt** [comment]
no prob. let us know here if it worked :)
