### ISSUE TITLE
Postgresql upserting fails, same code works with MySQL

### ISSUE THREAD

**Issue by dkagle** [slick/slick#1499]
PostgreSQL upserting fails with syntax error, works with MySQL.

```
def update(id: Long, name: String, description: String, price: Double): Int = { 
    val updated = item.insertOrUpdate(ItemModel(id, name: String, description: String, price: Double))
    println("SQL "+updated.statements.head)
    val results = ds.run(updated)
    Await.result(results, 1 second)
}
```

case class ItemModel(id: Long, name: String, description: String, price: Double)

// PostgreSQL
CREATE TABLE item (  
    id SERIAL NOT NULL PRIMARY KEY,  
    name varchar(255) NOT NULL,  
    description varchar(1024),
    price real 
);

Update works for Postgres

**Comment by hvesalai** [comment]
@dkagle can you provide more info on your definition of `item` and reopen.
