### ISSUE TITLE
How to use Driver not specific to database?

### ISSUE THREAD

**Issue by hhimanshu** [slick/slick#1500]
I am looking at Hello Slick 3.1 [code](https://github.com/typesafehub/activator-hello-slick/blob/master/src/main/scala/HelloSlick.scala) where there is import as  

```
import scala.slick.driver.H2Driver.simple._
```

and the tests are written against `H2` Database. Now if I need to run this for `MySQL`, do I change the driver?

If yes, then which driver api is agnostic of database? What if I want to write test against `H2` but in production want to run against `MySQL`

**Comment by djx314** [comment]
```scala
trait BaseDB {
  val jdbcProfile: JdbcProfile = slick.driver.H2Driver.api._ //or MysqlDriver
}

class Dao extends BaseDB {
  import jdbcProfile.api._
  ...
}
```

or like the code below
<https://github.com/strongtyped/active-slick/blob/develop/modules/core/src/main/scala/io/strongtyped/active/slick/JdbcProfileProvider.scala#L6>

I suggest that you'd better to use slick 3.1.1, the api changes a lot.

**Comment by cvogt** [comment]
@hhimanshu also, can I suggest, you use the mailing list for support questions, not the issue tracker :)? https://groups.google.com/forum/#!forum/scalaquery
