### ISSUE TITLE
Play slick creation of a table in MySQL with a longtext column fails.

### ISSUE THREAD

**Issue by jacobsallan** [slick/slick#1505]
A zip file is attached containing an sbt project.

Create a database named slickbugdb.  My MySQL version is 5.6.26.

Change the configuration file so that the variables default.db.user, default.db.password, newmysql.db.user, and newmysql.db.password are assigned values appropriate to your local database.

The script dist/sql/mysql/create-tables.sql will create a catalog and
table.  The catalog is slickbugdb.  The table is RSS_FEEDS.

Navigate a Chrome browser to chrome://flags/.  In the list on that page, find "Chrome: Enable Experimental Web Platform Features" and enable that feature.  The CSS Grid is used to enable a layout for an array of input buttons.

Point a Chrome browser at http://localhost:9000/main.  Click on the "Drop table" button to make the RSS_FEEDS table go away.  Use a mysql shell command "SHOW TABLES" to verify this.

Click on the "Create table" button.  Nothing will be created.  This
can be verified using the mysql shell command "SHOW TABLES", too.
The code that should create the table RSS_FEEDS attempts to use a
Slick DDL create.

Click on the "Create table with SQL" button.  Nothing will be created. This can be verified using the mysql shell command "SHOW TABLES", too.  The code that should create the table RSS_FEEDS attempts to use plain SQL.  The plain SQL used is identical to that used in the script
dist/sql/mysql/create-tables.sql.

[SlickLongTextBug.zip](https://github.com/slick/slick/files/253237/SlickLongTextBug.zip)

**Comment by trevorsibanda** [comment]
@jacobsallan Mysql converts 
```sql
  (RSS_NAME varchar(32) NOT NULL,
  RSS_FEED_XML VARCHAR(2147483647) NOT NULL,
  PRIMARY KEY (RSS_NAME));
```
to
```sql
  (RSS_NAME varchar(32) NOT NULL,
  RSS_FEED_XML TEXT NOT NULL,
  PRIMARY KEY (RSS_NAME));
```

And throws a warning. In fact running that query directly in mysql shell produces the warning
```
mysql> create TABLE IF NOT EXISTS RSS_FEEDS    (RSS_NAME varchar(32) NOT NULL,    RSS_FEED_XML VARCHAR(2147483647) NOT NULL,    PRIMARY KEY (RSS_NAME));
Query OK, 0 rows affected, 1 warning (0.40 sec)

mysql> show warnings;
+-------+------+-------------------------------------------------------+
| Level | Code | Message                                               |
+-------+------+-------------------------------------------------------+
| Note  | 1246 | Converting column 'RSS_FEED_XML' from VARCHAR to TEXT |
+-------+------+-------------------------------------------------------+
```

Its not an issue with slick but with jdbc. The exception raised even highlights this

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column length too big for column 'RSS_FEED_XML' (max = 65535); use BLOB or TEXT instead
```

**Comment by cvogt** [comment]
@jacobsallan did you manually pick `VARCHAR(2147483647)` or did slick somehow pick that for you? Looks like the SQL shell is more permissive with this than JDBC?

**Comment by cvogt** [comment]
What happens if you pick TEXT as the type in the sql script. Does the problem still exist?  @trevorsibanda I know there were problems with inferring the right string type in slick's model builder in the past. I can't remember if those were fixed or not.

**Comment by hvesalai** [comment]
@trevorsibanda was this resolved by your PR?

**Comment by Asamsig** [comment]
@hvesalai Looking through the PR, this issue is definitely resolved. So it can be closed.
