### ISSUE TITLE
Slick query

### ISSUE THREAD

**Issue by ntenisOT** [slick/slick#1509]
I would like to report a possible issue with Slick:

Imagine that we have the following code:

```
val joinTables = Customer.join(Card).join(Profile).on {
    case ((customer, card), profile) =>
        customer.id === card.customer &&
        customer.id === profile.customer
}
```

and the following:

```
val joinTables = Customer
.join(Card).on(_.id === _.customer)
.join(Profile).on(_._1.id === profile.customer)
```

The first one translates to a `Cross Join` and the second one creates an `Inner Join`

Is this the correct behaviour?

**Comment by hvesalai** [comment]
It is expected.

**Comment by evbo** [comment]
@hvesalai I don't see a documented explanation for why this is true. Is there any elaboration you can provide?
