### ISSUE TITLE
document how to use flyway with slick

### ISSUE THREAD

**Issue by cvogt** [slick/slick#1514]
As a follow up to https://github.com/slick/slick/issues/46 and #1510 it would be nice to document how to use flyway with Slick. Here is an example app that uses flyway: https://github.com/playframework/play-isolated-slick

**Comment by cvogt** [comment]
@wsargent Do you maybe want to add to the page created in #1510, similar to what @lastland already did there?

**Comment by wsargent** [comment]
I can't, my access was revoked :-(

**Comment by cvogt** [comment]
@wsargent how about a PR :)? We all do that anyways, even the people who have merge/commit permissions.

**Comment by lastland** [comment]
This has probably been resolved by #1515 ?

**Comment by cvogt** [comment]
yep, thx
