### ISSUE TITLE
GeomUtil/Shape Union Bug

### ISSUE THREAD

**Issue by lquinn2015** [slick/slick#1526]
Version: slick 3.1.1

I am unsure how to describe this error but in some cases the union function doesn't combine the shapes as expected. The following picture is from the GeomUtilTest(raw) file. This error also occurs with 2 intersecting rectangles however in that case they make odd triangles shapes

![capture](https://cloud.githubusercontent.com/assets/16884061/16138132/50731a44-3408-11e6-9fe4-085d2b431e03.JPG)

This picture is from my own testing and shows where two rectangles intersect at 90 degrees. In this case union leaves me with this distinctive output.

![image](https://cloud.githubusercontent.com/assets/16884061/16138220/66193da0-3409-11e6-9da6-ba85e27710f0.png)

**Comment by cvogt** [comment]
seems like it has nothing to do with Scala Slick
