### ISSUE TITLE
slick with mysql error: NoSuchMethodError streamableQueryActionExtensionMethods

### ISSUE THREAD

**Issue by daaatz** [slick/slick#1534]
Hi,

Im having strange problem while using new slick version with mysql:

Exception in thread "main" java.lang.NoSuchMethodError: slick.driver.JdbcProfile$API.streamableQueryActionExtensionMethods(Lslick/lifted/Query;)Lslick/profile/BasicActionComp$$$$6aa48549c0a7603df1fa229cf7177493$$$$sionMethodsImpl;

my application.conf:

https://gist.github.com/daaatz/ffd7e53b3b5d10445a39b7c2de1b9de3
code:
https://gist.github.com/daaatz/973e8f96ab62e9dba6d2c77656bbcb8a
build.sbt:
https://gist.github.com/daaatz/479ad86c6bf81fd2bc3152f0e05d3745

I was using similar code with slick 2.0 but with this I doesnt want to work ;/
Any one can help me ?

Thanks

**Comment by daaatz** [comment]
Heh, adding to build sbt:

`scalacOptions := Seq("-feature")`

resolved problem.

**Comment by cvogt** [comment]
that sounds like a linking problem, not exactly on slick's side. can be related to incremental compilation and I assume changing scalacOptions triggered a full recompile and thereby solved it as a side-effect. Closing this here. Feel free to re-open if the issue becomes reproducible.
