### ISSUE TITLE
codegen requires a "IF NOT EXISTS" modifier on CREATE TABLE statements.

### ISSUE THREAD

**Issue by jbdeboer** [slick/slick#1540]
e.g. In the slick/slick-codegen-example repo, the create.sql has IF NOT EXISTS modifiers on the CREATE TABLE statements. https://github.com/slick/slick-codegen-example/blob/master/src/main/sql/create.sql

If you remove the IF NOT EXISTS, codegen will fail with ```org.h2.jdbc.JdbcSQLException: Table "COMPUTERS" already exists; ...```.

This is a pain point as we are generating SQL scripts from an external tool which expects a clean environment.

**Comment by cvogt** [comment]
I don't understand the problem. Why does the code of this example project affect your real project in any way? Seems like you should try to create a schema if you already have one.

Feel free to re-open with more information explaining the problem.

**Comment by jbdeboer** [comment]
I don't have permission to reopen the issue.

e.g. Passing the following SQL to slick-codegen works:
```
CREATE TABLE IF NOT EXISTS "customers"
```

Passing this SQL does not work:
```
CREATE TABLE "customers"
```
