### ISSUE TITLE
Which packages are needed to run slick?

### ISSUE THREAD

**Issue by BorisHollas** [slick/slick#1552]
I use the Scala IDE for Eclipse and I was unable to install and run slick.

Please tell
- if slick can be used without Lightbend Activator,
- which packages must be downloaded and added to the lib path. 
Just adding slick-2.11 and slf4j-nop to the path didn't work.

Note that the Scala IDE for Eclipse doesn't work with sbt.

**Comment by cvogt** [comment]
If you are using sbt it should handle t all for you. Otherwise use mvnrepository.com to access the pom to explore slick's dependencies to know which jars to manually import.

**Comment by cvogt** [comment]
Gitter seems like a better place for this.

**Comment by BorisHollas** [comment]
I explored the pom and still don't know what dependencies are needed. 

However, I've discovered that even the HelloSlick-project (http://www.lightbend.com/activator/template/bundle/hello-slick-3.1) doesn't compile with sbt due to unresolved dependency errors. I'll therefore consider alternatives to slick.

**Comment by cvogt** [comment]
Tracking the hello-slick issue here: https://github.com/typesafehub/activator-hello-slick/issues/25

Slick can be used without activator like this: http://slick.lightbend.com/doc/3.1.1/gettingstarted.html

I recommend using a dependency manager like sbt to automatically download transitive dependencies.
