### ISSUE TITLE
Slick 3.1.2 Release Planning

### ISSUE THREAD

**Issue by szeiger** [slick/slick#1553]
We've just run into https://github.com/slick/slick/pull/1320 in a support case. The PR targeted master instead of 3.1 so it didn't make it into 3.1.1. I'd like to backport it and release 3.1.2.

There are also these two other fixes that have not yet been released for 3.1:

```
$ git log --oneline 3.1.1..3.1
fc04186 Merge pull request #1476 from mkotsbak/3.1
ecd2f15 Add quoting of table names and fk in ALTER TABLE for MySQL
a25da8f Merge pull request #1445 from mustajarvi/fix-#1400-npe-in-init
11196d7 Add init call to getParrentLogger per PR comments
9c73813 Fix of #1400 - race in DriverDataSource.init
```

I've created a 3.1.2 milestone due two weeks from now. If you'd like to see any other fixes in 3.1, please open PRs against this milestone.

**Comment by mkotsbak** [comment]
One month has passed, plans for a release soon?
