### ISSUE TITLE
HelloSlick example doesn't compile

### ISSUE THREAD

**Issue by BorisHollas** [slick/slick#1554]
With sbt compile, the [HelloSlick](http://www.lightbend.com/activator/template/bundle/hello-slick-3.1) produces
[error] (*:update) sbt.ResolveException: unresolved dependency: com.typesafe.play#sbt-fork-run-protocol_2.10;2.3.8: not found
[error] unresolved dependency: com.typesafe.play#routes-compiler_2.10;2.3.8: not found
[error] unresolved dependency: com.typesafe.play#sbt-run-support_2.10;2.3.8: not found
[error] unresolved dependency: net.contentobjects.jnotify#jnotify;0.94: not found
[error] unresolved dependency: com.typesafe#jse_2.10;1.0.0: not found
[error] unresolved dependency: com.typesafe#npm_2.10;1.0.0: not found
[error] unresolved dependency: com.typesafe#webdriver_2.10;1.0.0: not found

**Comment by cvogt** [comment]
please open this issue on the repository it applies to. Not sure which one.

**Comment by cvogt** [comment]
please open this issue on the repository it applies to. Not sure which one.

**Comment by cvogt** [comment]
reproduced the problem and opened an issue here: https://github.com/typesafehub/activator-hello-slick/issues/25
