### ISSUE TITLE
More precise error message needed instead of "This DBMS allows only a single AutoInc column to be returned from an INSERT"

### ISSUE THREAD

**Issue by aholland** [slick/slick#1561]
If this error message were more precise it would save time for developers.

The message is:

[SlickException: This DBMS allows only a single AutoInc column to be returned from an INSERT]

The message should be:

[SlickException: This DBMS allows only a single column to be returned from an INSERT, and that column must be an AutoInc column.]

For a developer attempting to use `return` for a non-AutoInc column the modified message makes it clearer what has been done wrong.

**Comment by cvogt** [comment]
Sounds good to me. @trevorsibanda wanna sneak this in :)?

**Comment by cvogt** [comment]
fixed

**Comment by aholland** [comment]
great! thank you.

**Comment by cvogt** [comment]
thanks to @trevorsibanda  :)!
