### ISSUE TITLE
Make Slick compatible with Scala 2.12.0-RC1

### ISSUE THREAD

**Issue by szeiger** [slick/slick#1572]
Slick will not compile on RC1 due to https://github.com/scala/scala/pull/5287.

**Comment by ChristopherDavenport** [comment]
Since I felt responsible I took a look, since hasNext calls update, and then it uses the same boolean operator as hasNext couldn't this method simply be removed to retain the same functionality, since then rather than cached, as done here it would call head, which would return cached. Unless there is an inner working that I am missing here it seems the implemented headOption in 2.12.0-RC1 could replace this.

**Comment by ChristopherDavenport** [comment]
I only reffed this issue with the ReadAheadIterator problem, are there any other changes that need to be made for 2.12 or has that fixed this issue?

**Comment by fommil** [comment]
heh, "easy" you say. Can a 2.12 release be expected on a version that is also available for scala 2.10/2.11 on Java 7?

**Comment by sarahgerweck** [comment]
Yes, you can quite easily do a 2.12 release while maintaining support for Java 6 or Java 7 if you use SBT's cross compile. You can have different compilation settings and even different dependency versions for each of the cross compilation targets. In the unusual case where your Java 7 source code cannot run on Java 8, you can have a `src-java8` directory.

**Comment by SethTisue** [comment]
was Slick ever published for 2.12? I'd like to make sure that https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md is up-to-date

**Comment by szeiger** [comment]
3.2.0-M2 was published for Scala 2.12.

**Comment by SethTisue** [comment]
scala/make-release-notes@d978646497864864e2e7cc957c702893664735fe

**Comment by ztaoo** [comment]
@szeiger  Can 3.2.0-M2 be used in product?

**Comment by szeiger** [comment]
@ztaoo I recommend to use 3.2.0-M2 over 3.1 and 3.0 because of #1274.

**Comment by sarahgerweck** [comment]
@szeiger Any chance we can have a 3.2.0 release (or a release candidate) if the feeling is that it's already more stable and reliable than 3.1 or 3.0? The delay in producing a Scala 2.12–compatible release has created a lot of concern about this project. If the feeling is that 3.2.0-M2 is production quality, this may be more of a communication problem than an actual problem. People generally treat milestone builds as unsuitable for production use (and as a result, they usually are, as few people are using them for anything real).
