### ISSUE TITLE
SQLServerDriver: `tinyint` SQL type should be presented as `Short` instead of `Byte`

### ISSUE THREAD

**Issue by vasily-kirichenko** [slick/slick#1595]
SQL Server's `tinyint` type is _unsigned_ byte while Scala's `Byte` is _signed_. `tsql"..."` interpolator infers `tinyint` as `Byte` which causes wrong results:

``` sql
create table foo(id tinyint)
insert foo(200)
```

``` scala
// it compiles and returns `Seq(-56)` as a result
val cmd: DBIO[Seq[Byte]] = tsql"select id from foo"
// it does not compile
val cmd: DBIO[Seq[Short]] = tsql"select id from foo"
```

Since we don't have unsigned byte type in Scala, the only correct way I can see is to use `Short` type.

**Comment by trevorsibanda** [comment]
@vasily-kirichenko Check out #1596

**Comment by vasily-kirichenko** [comment]
Great, thanks! I'm not familiar with the Slick release process. How will I know that the fixed version is released?

**Comment by cvogt** [comment]
@vasily-kirichenko we announce things like this on the mailing list. If you only want releases you probably need an email filter.

**Comment by strelec** [comment]
But then this should be true for all data types: if they are unsigned, they should be promoted to one type up.

unsigned longs should therefore be promoted to BigInt.

**Comment by Asamsig** [comment]
This issue should be closed, a fix is already merged in.
