### ISSUE TITLE
Codegen: Allow to override fakeNullable in ColumnDef

### ISSUE THREAD

**Issue by rfuerst87** [slick/slick#1598]
`slick.codegen.AbstractGenerator` currently does not allow to override `ColumnDef.fakeNullable`. I'm facing a case where I need an `Option` type in my mapped case class whereas the database column itself is not nullable. Just like it is with auto incremented values. I'm quite sure this is a common use case for example in situations where values are computed based on other properties of the same object just before a db insert happens.
I suggest to remove the `final` modifier from `fakeNullable`. For flexibility I'd also split `TableDef.autoIncLastAsOption` into two separate properties `autoIncLast` and `autoIncAsOption`. If you agree I'd provide a PR.

**Comment by cvogt** [comment]
@rfuerst87 alternatively you can transform the model before giving it to the code generator.

But sure, I am open to a PR here for all 3 proposed changes.

**Comment by rfuerst87** [comment]
@cvogt Thanks for the quick reply. I was thinking about transforming the model too. Maybe I miss something here, but the only two properties I could find that control whether a column is nullable or not are `model.Column.nullable` and `model.Column.option.AutoInc`. Neither of them can be used because:

1. `nullable` affects both Table and Entity, whereas I only need to set the exposed type to be an Option.
1. `AutoInc` also appends `O.AutoInc` to the table options. This seems to be a bit hacky IMHO.

Please correct me if I overlooked something.
