### ISSUE TITLE
Seq is not a member of object slick.dbio.DBIOAction

### ISSUE THREAD

**Issue by vitalyisaev2** [slick/slick#1607]
Hello!

I use Scala ```2.11.8``` and Slick ```3.1.1```,  it seems like the problem fixed in #1224  is still present:

```
scala> import slick.driver.PostgresDriver.api._
import slick.driver.PostgresDriver.api._

scala> val x = DBIO.Seq()
<console>:14: error: value Seq is not a member of object slick.dbio.DBIOAction
       val x = DBIO.Seq()

```

I would suggest that [HelloSlick.scala](http://www.lightbend.com/activator/template/hello-slick-3.1#code/src/main/scala/HelloSlick.scala) needs to be fixed

**Comment by d6y** [comment]
@vitalyisaev2 I'll close this one as it's `DBIO.seq` (lower case s) not `DBIO.Seq`.  Please re-open if you need to. Thanks!

**Comment by vitalyisaev2** [comment]
@d6y , thanks, my fault...
