### ISSUE TITLE
Compiled query takes 4 seconds vs 60 ms for non-compiled version

### ISSUE THREAD

**Issue by shado23** [slick/slick#1621]
I've run into a strange behaviour with Slick 3.1.1 (on MSSQL using jTDS) where the same query takes an obscene amount of time when being run from a compiled query (on every execution) and runs as expected when not running precompiled.

```scala
object Assets extends TableQuery(new AssetTable(_)) {
  def nextReference(partial_ref: String): Future[String] = db.run {
    lastReferenceQuery(partial_ref).result.head
  }

  // takes < 100 ms
  def lastReferenceQuery(partial_ref: String) = for {
    asset <- Assets.sortBy(_.create_date.desc)
    if (asset.reference like partial_ref) && (asset.reference like "%[0-9]") && asset.image && !asset.deleted
  } yield asset.reference.getOrElse("")

  // takes > 3 seconds
  val lastReferenceQuery = for {
    partial_ref <- Parameters[String]
    asset       <- Assets.sortBy(_.create_date.desc)
    if (asset.reference like partial_ref) && (asset.reference like "%[0-9]") && asset.image && !asset.deleted
  } yield asset.reference.getOrElse("")
}
```
Here are debug logs for both cases.
[compiled.txt](https://github.com/slick/slick/files/498050/compiled.txt)
[uncompiled.txt](https://github.com/slick/slick/files/498051/uncompiled.txt)

**Comment by szeiger** [comment]
The non-compiled version doesn't use a bind variable. you're giving the database a concrete value so it can produce a more specialized and better execution plan, possibly prefetching the required data at preparation time (which is not included in the execution time).

For a fair comparison you need to use `partial_ref.bind` in the non-compiled version. This should yield the same preparation and execution times for both versions. When benchmarking without `bind`, make sure to count both preparation time and execution time.

**Comment by shado23** [comment]
Yes, you're right. Using `partial_ref.bind` it's exactly the same with the non-compiled version. So it's not a slick issue at all.

Thanks for the explanation and sorry for the noise.
