### ISSUE TITLE
Changing behaviour of parameter being None when updating

### ISSUE THREAD

**Issue by JeremiasIsnardy** [slick/slick#1625]
Hello,

Is there any way to change the behaviour of slick for None parameter? When I'm doing an update on a table slick updates a column, whose parameter being None, with "null". For my purposes it would be better to ignore this parameter.

I know I could map and choose the columns I want to update, but this is quite ugly to achieve, because I would need do select them by means of the parameter I want to (or not want to) update.

Another solution I found would be to first do a Select on this columns, get the current values and use them for all the parameter being None. But this solution is also one I cannot cotton up to, because I don't want to an additional Select for each Update.

Currently I'm trying to override the queryUpdateActionExtensionMethods of the JdbcActionComponent and implement my own update method, but I have come to a point being lost. ;-)

So, my question, is there any 'good' way to achieve this?

Best regards
JI

**Comment by hvesalai** [comment]
Please post this question to one of the community forums.
