### ISSUE TITLE
Unused import

### ISSUE THREAD

**Issue by MasseGuillaume** [slick/slick#1628]
I'm using the `scalacOptions -= "-Ywarn-unused-import"` flag.

the code generates unused imports:

``` scala
import profile.api._
import slick.model.ForeignKeyAction
```

**Comment by trevorsibanda** [comment]
@MasseGuillaume Good news... #1736 removed unused imports :smiley:  

Am closing this issue, feel free to re-open it

**Comment by giorgiopers** [comment]
I still have 

`import slick.model.ForeignKeyAction`
