### ISSUE TITLE
"Contain" feature

### ISSUE THREAD

**Issue by rmartins90** [slick/slick#1640]
Hello guys, first congrats to all contributors of this library, it's great!

I'm trying to do a very particular thing and I want to use slick.js for this purpose, I've found that Flickity has this feature already, is it possible on slick.js? The feature is described on the following link:
http://flickity.metafizzy.co/options.html#contain

Basically I need to use centerMode but shouldn't exists any excess of slick track on both left and right edges.

**Comment by trevorsibanda** [comment]
@rmartins90 Wrong project 

This is slick.js repo -> https://github.com/kenwheeler/slick
