### ISSUE TITLE
`UPDATE test_table set col = col + 1` in slick?

### ISSUE THREAD

**Issue by norcalli** [slick/slick#1643]
I can't seem to find an example explicating how to use the value of a column in the table to do an update. Say to increment a column, or in postgres `set jsoncolumn = jsoncolumn - 'field'`, which is a very useful pattern. Any information on this would be appreciated.

**Comment by cvogt** [comment]
for now one has to use plain sql. Support for the typed api is being worked on here  https://github.com/slick/slick/pull/1530 and here https://github.com/slick/slick/issues/497
