### ISSUE TITLE
Using PostgreSQL's `?` jsonb operators in plain SQL statements

### ISSUE THREAD

**Issue by natemurthy** [slick/slick#1646]
Postgres offers database admins the ability to create columns with JSON datatypes, namely `json` and `jsonb`. Some often used operators to determine whether elements belong to top-level keys in a JSON object are the `?`, `?|`, `?&` operators (see https://www.postgresql.org/docs/9.5/static/functions-json.html). I'm using Slick 3.1.1, and using these operators appears to be broken when making plain SQL statements. This:

```
val query = sql"""SELECT data FROM foo WHERE target ? 'elem'""".as[String]
db.run(query)
```

throws a `java.util.concurrent.TimeoutException` while waiting for the future to complete. Is there maybe an escape character I can place in front of the question mark operator that will make Slick happy. If there isn't, could we get full support for all the Postgres `json` and `jsonb` operators in an upcoming release?

**Comment by tminglei** [comment]
Hi @natemurthy  use `??` to replace `?`.

I added the support in PR pgjdbc/pgjdbc#227.

**Comment by natemurthy** [comment]
Thanks @tminglei this worked! I scoured the web trying to find exactly this. Is this documented some place either in the Slick or pgjdbc docs for my future reference?

**Comment by tminglei** [comment]
@natemurthy it was documented here now:
https://jdbc.postgresql.org/documentation/head/statement.html

**Comment by natemurthy** [comment]
Beautiful. Thank you so much for pointing me to these resources and for contributing to this library!

**Comment by tminglei** [comment]
You're welcome! :-)

**Comment by Gowtham-Pallekonda** [comment]
> @natemurthy it was documented here now: https://jdbc.postgresql.org/documentation/head/statement.html
> 
> _p.s. the last item._

Pls provide the current documentation link
