### ISSUE TITLE
"value delete is not a member of slick.lifted.Query" 

### ISSUE THREAD

**Issue by jdelafon** [slick/slick#1658]
I am using Play-slick 2.0.2, which claims support for Slick 3.1. I hit this issue when trying to use ".delete" on a valid query:

    value delete is not a member of slick.lifted.Query

According to the many threads I could find, this is most likely due to me "mixing drivers" somehow somewhere. Now, 
* I read that this was fixed in Slick 3.1 (#1253), yet it occurs to me now.
* Can it be a play-slick issue instead?
* Documentation and a better error message (#670) have been missing for about 2 years now. Even knowing that this is likely the error, there are not many clues how to solve it. Is it in my `application.conf`? How can one diagnose it to be sure there is a driver conflict?

Here is the code that reproduces the error:

**[application.conf]**

    slick {
      dbs {
        default {
          driver = "slick.driver.H2Driver$"
          db.driver = "org.h2.Driver"
          db.url = "jdbc:h2:mem:test;MODE=MYSQL;DATABASE_TO_UPPER=false"
          db.user = "sa"
          db.password = ""
        }
      }
    }

(no `db` entry)

**[Controller]**

(The `driver` and `db` are the things available from an injected controller, as suggested by the Play docs, and they have type respectively )

    import slick.driver._

    class MyController @Inject()(dbConfigProvider: DatabaseConfigProvider) extends Controller
      val dbConfig = dbConfigProvider.get[JdbcProfile]
      val driver: JdbcProfile = dbConfig.driver
      val db = dbConfig.db
      ...
      def delete() = Action.async {
        DAO(driver, db).remove()
      }
    }

**[Generic DAO]**

(because I have 120 tables)

    import slick.lifted._
    import slick.driver.JdbcProfile

    abstract class GenericDAO[T <: AbstractTable[_]](val driver: JdbcProfile, val db: JdbcProfile#Backend#Database) {
      import driver.api._
      def table: TableQuery[T]
      ...
    }

**[Specific table DAO]**

    class RunsDAO(override val driver: JdbcProfile, override val db: JdbcProfile#Backend#Database) extends GenericDAO[Runs](driver, db) {
      import this.driver.api._
      val table = TableQuery[Runs]
      def remove() = {
        ...
        db run action.delete()
      }
    }

I was inspired by [this template](https://github.com/voidcontext/slick-generic-dao-example) for a Generic DAO, which actually suffered from [the same issue](https://github.com/voidcontext/slick-generic-dao-example/issues/1#issuecomment-258942699) before I reported it, and it was fixed by a [super-ugly hack](https://github.com/voidcontext/slick-generic-dao-example/commit/85127cc661a7aea3d3ba6acb66dab43c157d8916):

    private def buildDeleteAction(id: Id) = {
      driver.createDeleteActionExtensionMethods(
        driver.deleteCompiler.run(filterById(id).toNode).tree, ()
      )
    }

    def deleteById(id: Id) = {
      val action = buildDeleteAction(id)
      db run action.delete
    }

It looks very much like the [fix](https://github.com/slick/slick/issues/1253#issuecomment-135040991) proposal in #1253.

**Comment by cvogt** [comment]
Also see this: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scalaquery/JMnNfuPL8T4/-wo_GyX0JgAJ
The solution seems to be using `Table` instead of `AbstractTable`

**Comment by jdelafon** [comment]
The difficulty was to find out that it exists and how to import it:

    <driver>.profile.api.Table

for instance:

    slick.driver.MySQLDriver.profile.api.Table

The trap is that when you inspect a Table, your IDE (IntelliJ) tells you that it is an AbstractTable, so you think this is the type you need, especially since for some strange reason is has all required concrete methods except for .delete.

The only complete example of a working generic DAO that I could find for Slick 3: 
https://github.com/bravegag/play-authenticate-usage-scala/blob/master/app/dao/generic/GenericDao.scala
