### ISSUE TITLE
[slick-hikaricp] Update hikaricp to latest version (v2.5.1+)

### ISSUE THREAD

**Issue by alias1** [slick/slick#1670]
Looking in the latest [Build.scala](https://github.com/slick/slick/blob/master/project/Build.scala) in master I can see `v2.3.13`:

```
val hikariCP = "com.zaxxer" % "HikariCP-java6" % "2.3.13"
```

It seems that `slick-hikaricp 3.1.1` is only using `hikaricp 2.3.7` (which is what lead to my issue [here](https://github.com/brettwooldridge/HikariCP/issues/788#issuecomment-268637592))

Looking at the [hikaricp repo](https://github.com/brettwooldridge/HikariCP) they are up to `v2.5.1` now.

Are there any plans to update to the latest? I'm guessing it would have to be in slick 3.2+ due to the Java 8 changes.

Edit: As a sanity check, just looked at [3.2.0-M2](https://github.com/slick/slick/blob/3.2.0-M2/project/Build.scala) and it's still using `v2.3.13`.

**Comment by cvogt** [comment]
A PR would be great :)

**Comment by alias1** [comment]
I assume if I just bump the version and run the tests that should be enough to 'prove it works'? If so, can probably do it.

Get Outlook for iOS




On Fri, Dec 23, 2016 at 4:29 AM +1100, "Jan Christopher Vogt" <notifications@github.com> wrote:












A PR would be great :)

**Comment by cvogt** [comment]
sounds good :)
