### ISSUE TITLE
connection leak detected

### ISSUE THREAD

**Issue by simao** [slick/slick#1678]
Our app is reaching a point where all connections in the pool get used used but never released, no matter how we size our pool.

Using the default settings:

numThreads: 20
maxConnections: numThreads * 20
queueSize: 1000

After a while we start getting the following exceptions:

```
java.sql.SQLTimeoutException: Timeout after 3000ms of waiting for a connection.
    at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:227)
    at com.zaxxer.hikari.pool.BaseHikariPool.getConnection(BaseHikariPool.java:182)
    at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:93)
    at slick.jdbc.hikaricp.HikariCPJdbcDataSource.createConnection(HikariCPJdbcDataSource.scala:12)
    at slick.jdbc.JdbcBackend$BaseSession.conn$lzycompute(JdbcBackend.scala:415)
    at slick.jdbc.JdbcBackend$BaseSession.conn(JdbcBackend.scala:414)
```

Checking the metrics for the connection pool, we get:

```
I|17:00:24.355|metrics|type=GAUGE, name=database.pool.ActiveConnections, value=50
I|17:00:24.355|metrics|type=GAUGE, name=database.pool.TotalConnections, value=50
I|17:00:24.355|metrics|type=GAUGE, name=database.pool.IdleConnections, value=0
I|17:00:24.355|metrics|type=GAUGE, name=database.pool.PendingConnections, value=10
I|16:59:24.357|metrics|type=TIMER, name=database.pool.Wait, count=1124, min=0.00314, max=669.83618, mean=2.4348944424985675, stddev=27.715996025113594, median=0.004702, p75=0.007536999999999999, p95=0.048871, p98=7.805542999999999, p99=37.235472, p999=498.98862199999996, mean_rate=1.8733480005928587, m1=0.0033051119490839277, m5=0.6506749574842373, m15=0.695739471013702, rate_unit=events/second, duration_unit=milliseconds
```

Enabling leak detection, we get the following errors:

```
com.zaxxer.hikari.pool.LeakTask|Connection leak detection triggered for connection org.mariadb.jdbc.MariaDbConnection@12d9442a, stack trace follows
```

Removing all `.transactionally` calls in the affected code, the app holds on for a few additional requests, but then the same behaviour is observed.

Checking mysql processlist, all connections are on Sleep state, so connections are not waiting for data from mysql.

We tried with the patched version of slick for #1461, with the same results.

How can we get more information to find this leak? Is there anyway to check where these connections are being leaked?

**Comment by szeiger** [comment]
Something doesn't quite match up. 30000ms is the default connection timeout of HikariCP but Slick overrides it to 1000ms (the minimum that HikariCP allows). If you let Slick configure the pool with only the 3 configuration settings you listed there should not be any 30000ms timeout.

Are you configuring the pool on your own? How does the pool get injected into Slick? For the new scheduling algorithm in #1461 to work correctly without deadlocks it is critical that Slicks knows the connection pool size. It is set automatically when you let Slick configure HikariCP, in all other cases you have to do it on your own.

**Comment by hvesalai** [comment]
How is this (it is critical that Slick knows the connection pool size) done when I want to configure my own pool?

**Comment by szeiger** [comment]
Good question. `forDataSource` doesn't provide any option for that, which is dangerous. You have to call `forSource` and subclass `DataSourceJdbcDataSource` to set the value. I'm assigning this ticket back to 3.2.0. We have to change the API so that you're required to set the pool size in `forDataSource`.

**Comment by szeiger** [comment]
I'm changing `forDataSource` in #1685. If there is more to this issue than a misconfigured pool, it is probably the same as #1614 so I'm closing this as a duplicate.
