### ISSUE TITLE
slick.SlickTreeException: Cannot convert node to SQL Comprehension when using DROP without SORTYBY

### ISSUE THREAD

**Issue by rabzu** [slick/slick#1680]
MSSQL

this works:
```
    query .sortBy
              .drop(page)
              .take(perPage)

```
this causes error:

 ```
query
      .drop(page)
      .take(perPage)
```

**Comment by trevorsibanda** [comment]
@rabzu Can you provide more details.

There is a test for this at [https://github.com/slick/slick/blob/51e14f2756ed29b8c92a24b0ae24f2acd0b85c6f/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/PagingTest.scala#L18](https://github.com/slick/slick/blob/51e14f2756ed29b8c92a24b0ae24f2acd0b85c6f/slick-testkit/src/main/scala/com/typesafe/slick/testkit/tests/PagingTest.scala#L18) 

Giving more info about your query would help

**Comment by hvesalai** [comment]
Please post a question to one of the community forums and reopen if this is really a bug
