### ISSUE TITLE
Codegen Slick 3.2-RC1 SQLServer Class Cast Exception

### ISSUE THREAD

**Issue by jacobus** [slick/slick#1690]
Hi,

I've mentioned this problem on the [slick forum](https://groups.google.com/forum/#!topic/scalaquery/HK_pK7StqYc), but there were no views on the question so far. I am logging it as a bug, because it appears to be one.

I'm trying to generate code from SQL Server 2014 using Slick 3.2-RC1 but I'm getting a class cast exception. Please see below

Scala version: 2.12.1
Java version 1.8
SQL Server 2014
JDBC driver 6.1.0 for java 8

Note commands below are copied from Ammonite:

import $ivy.`com.typesafe.slick::slick:3.2.0-RC1`
import $ivy.`com.typesafe.slick::slick-codegen:3.2.0-RC1`
import $ivy.`com.microsoft.sqlserver:mssql-jdbc:6.1.0.jre8`
 slick.codegen.SourceCodeGenerator.main(Array("slick.jdbc.SQLServerProfile","com.microsoft.sqlserver.jdbc.SQLServerDriver","jdbc:sqlserver://localhost:1433;databaseName=test","/home/dude/generated","somepackage","user", "pass")) 
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
  com.microsoft.sqlserver.jdbc.SQLServerResultSet.getInt(SQLServerResultSet.java:2328)
  slick.jdbc.PositionedResult.nextIntOption(PositionedResult.scala:62)
  slick.jdbc.GetResult$GetIntOption$.apply(GetResult.scala:39)
  slick.jdbc.GetResult$GetIntOption$.apply(GetResult.scala:39)
  slick.jdbc.PositionedResult.$less$less(PositionedResult.scala:31)
  slick.jdbc.PositionedResult.$less$less$qmark(PositionedResult.scala:32)
  slick.jdbc.meta.MColumn$.$anonfun$getColumns$2(MColumn.scala:27)
  slick.jdbc.ResultSetInvoker$$anon$4.extractValue(ResultSetInvoker.scala:37)
  slick.jdbc.ResultSetInvoker$$anon$2.extractValue(ResultSetInvoker.scala:26)
  slick.jdbc.PositionedResultIterator.fetchNext(PositionedResult.scala:176)
  slick.util.ReadAheadIterator.update(ReadAheadIterator.scala:28)
  slick.util.ReadAheadIterator.hasNext(ReadAheadIterator.scala:34)
  slick.util.ReadAheadIterator.hasNext$(ReadAheadIterator.scala:33)
  slick.jdbc.PositionedResultIterator.hasNext(PositionedResult.scala:167)
  scala.collection.Iterator.foreach(Iterator.scala:929)
  scala.collection.Iterator.foreach$(Iterator.scala:929)
  slick.jdbc.PositionedResultIterator.foreach(PositionedResult.scala:167)
  slick.jdbc.Invoker.foreach(Invoker.scala:49)
  slick.jdbc.Invoker.foreach$(Invoker.scala:47)
  slick.jdbc.ResultSetInvoker.foreach(ResultSetInvoker.scala:14)
  slick.jdbc.StreamingInvokerAction.run(StreamingInvokerAction.scala:22)
  slick.jdbc.StreamingInvokerAction.run$(StreamingInvokerAction.scala:20)
  slick.jdbc.ResultSetAction$$anon$1.run(ResultSetInvoker.scala:42)
  slick.jdbc.ResultSetAction$$anon$1.run(ResultSetInvoker.scala:42)
  slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:240)
  slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:240)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)

**Comment by cvogt** [comment]
Looks like the jdbc driver is giving us a String for the SOURCE_DATA_TYPE while slick expected an Int. I am not clear how to read this here: http://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-

> *SOURCE_DATA_TYPE* short => source type of a distinct type or user-generated Ref type, SQL type from java.sql.Types (null if DATA_TYPE isn't DISTINCT or user-generated REF)

Sounds like we should change MColumn to allow for `Any` in this field. Wanna give it a shot, @jacobus?

**Comment by jacobus** [comment]
Hi Jan,

I'm not being lazy, but it will be great if you can fix this. I am way
overloaded in my current project. Been sitting at work straight through the
weekend. This is currently blocking me, and I simply don't have the time at
this point to figure out how to fix it myself.

Please please pretty please with sugar on top.

Kind regards,
Jack

**Comment by jacobus** [comment]
p.s. I tried with both 4.0.2206.100 and 6.1.0.jre8 JDBC drivers but getting the same problem with both.

**Comment by trevorsibanda** [comment]
@jacobus Can you provide me with the schema you used so I can add a test. Am working on a patch

**Comment by jacobus** [comment]
@trevorsibanda

Thank you very much for helping out!

I'll ask my client if I can send you a copy. They are a little difficult
 on such things, but I'll do my best. They may feel it's sensitive
information. The other problem is that I have already left the office so
can only send it tomorrow.

If I'm not allowed to send the full schema (it's a monster), I'll try and
identify the culprit tables and send them only.

Thank you very much for helping out so quickly :-)


On 12 Feb 2017 23:56, "Trevor SIbanda" <notifications@github.com> wrote:

@jacobus <https://github.com/jacobus> Can you provide me with the schema
you used so I can add a test. Am working on a patch

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/slick/slick/issues/1690#issuecomment-279210483>, or mute
the thread

**Comment by cvogt** [comment]
https://github.com/slick/slick/pull/1691

**Comment by trevorsibanda** [comment]
I think this should be closed?
