### ISSUE TITLE
MTable.getTables should not pass null to DatabaseMetaData.getTables

### ISSUE THREAD

**Issue by TimMoore** [slick/slick#1692]
`MTable.getTables` calls this code:

```scala
_.metaData.getTables(cat.orNull, schemaPattern.orNull, namePattern.orNull, types.map(_.toArray).orNull)
```

https://github.com/slick/slick/blob/7fb013e448154ed50da3c3d4689a4853b00d8a59/slick/src/main/scala/slick/jdbc/meta/MTable.scala#L28

The API documentation for [`DatabaseMetaData.getTables`](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getTables(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String[])) does not specify that `null` is permitted for the `tableNamePattern` parameter.

In fact the MySQL JDBC driver (`"mysql" % "mysql-connector-java" % "6.0.5"`) throws an exception when `null` is passed:

```
java.sql.SQLException: Table name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545) ~[mysql-connector-java-6.0.5.jar:6.0.5]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513) ~[mysql-connector-java-6.0.5.jar:6.0.5]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505) ~[mysql-connector-java-6.0.5.jar:6.0.5]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479) ~[mysql-connector-java-6.0.5.jar:6.0.5]
	at com.mysql.cj.jdbc.DatabaseMetaData.getTables(DatabaseMetaData.java:3836) ~[mysql-connector-java-6.0.5.jar:6.0.5]
	at slick.jdbc.meta.MTable$$anonfun$getTables$1.apply(MTable.scala:28) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.meta.MTable$$anonfun$getTables$1.apply(MTable.scala:28) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.ResultSetInvoker$$anon$4.createResultSet(ResultSetInvoker.scala:36) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.ResultSetInvoker.iteratorTo(ResultSetInvoker.scala:19) ~[slick_2.11-3.1.1.jar:na]
	at slick.jdbc.Invoker$class.foreach(Invoker.scala:48) ~[slick_2.11-3.1.1.jar:na]
```

This might also be the cause of #1485.

I'm testing with Slick 3.1.1, but the same issue exists on master.

## Workaround

You can pass `"%"` as the table name pattern to get all tables.

**Comment by NickMcAvoy** [comment]
I'm hitting this same issue.

**Comment by cvogt** [comment]
@NickMcAvoy you mean mysql-connector-java:5.1.23 ?

**Comment by NickMcAvoy** [comment]
@cvogt That's right. But using version 6.0.5 manifested this issue.

**Comment by nafg** [comment]
See http://stackoverflow.com/a/43039214/333643

**Comment by nafg** [comment]
As I linked above, MySQL JDBC connector is configurable with regard to this behavior. However it seems to prefer using `"%"` rather than `null`. Does `"%"` work on all database JDBC drivers that we support? If so it would seem preferable to just use that.

**Comment by TimMoore** [comment]
When I tested this, `"%"` worked with everything I tried:

- Oracle 12c 12.1.0 (`"com.oracle.jdbc" % "ojdbc7" % "12.1.0.2"`)
- MySQL 5.7.17 (`"mysql" % "mysql-connector-java" % "6.0.5"`)
- Postgres 9.6.2 (`"org.postgresql" % "postgresql" % "9.4.1212"`)
- H2 in-memory and filesystem (`"com.h2database" % "h2" % "1.4.192"`)

This was with Slick 3.1.1 and Slick Extensions 3.1.0.

Oracle also failed with `null`.

I didn't notice the table of supported driver versions at the time, so I was testing with the latest version I could find of each driver.

I think that the [spec](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html) makes it pretty clear that JDBC drivers _ought to_ work with `"%"`. It also implies less clearly that `null` should work the same way. Here are some relevant excerpts.

The parameter docs for [`getTables`](https://docs.oracle.com/javase/7/docs/api/java/sql/DatabaseMetaData.html#getTables(java.lang.String,%20java.lang.String,%20java.lang.String,%20java.lang.String[])):

> `catalog` - a catalog name; must match the catalog name as it is stored in the database; "" retrieves those without a catalog; `null` means that the catalog name should not be used to narrow the search
>
> `schemaPattern` - a schema name pattern; must match the schema name as it is stored in the database; "" retrieves those without a schema; `null` means that the schema name should not be used to narrow the search
>
> `tableNamePattern` - a table name pattern; must match the table name as it is stored in the database
>
> `types` - a list of table types, which must be from the list of table types returned from `getTableTypes()`, to include; `null` returns all types

Note that it explicitly allows `null` for everything _but_ `tableNamePattern`.

> Some DatabaseMetaData methods take arguments that are String patterns. These arguments all have names such as fooPattern. Within a pattern String, "%" means match any substring of 0 or more characters, and "_" means match any one character.

This seems pretty clear that anything that is described as a "pattern" should match everything with `"%"`.

> Only metadata entries matching the search pattern are returned. If a search pattern argument is set to null, that argument's criterion will be dropped from the search.

This implies that `null` would be equivalent to matching everything.

**Comment by nafg** [comment]
Would you like to open a pull request? IIUC what you want to do is to
change the parameter's default value to Some("%").

**Comment by cvogt** [comment]
Sounds great! We are aiming for a new release for around the time of Scala Days. So if we manage to merge a PR until then, it would include this.

**Comment by TimMoore** [comment]
Submitted #1717. Thanks for the feedback.

**Comment by hvesalai** [comment]
@kflorence note that PR #1717 is on hold until somebody has time to finalize it.
