### ISSUE TITLE
`distinct` doesn't change the query's collection type to Set

### ISSUE THREAD

**Issue by kubukoz** [slick/slick#1702]
Calling `distinct` on a `Query[T, U, Seq]` doesn't change the last type parameter to one that guarantees unique values - e.g. `Set` - is there any particular reason for that in the Slick philosophy? Without such behavior, we need an `implicit ec: ExecutionContext` and an additional `.map(_.toSet)` call every time.

If not, would it be difficult to implement?

**Comment by szeiger** [comment]
`distinct` generally preserves ordering, so it makes sense to keep an ordered collection type. You can call `.to[Set]` on the `Query` to change it upfront so that Slick doesn't build an intermediate `Seq` from the result set.

**Comment by kubukoz** [comment]
Ah, that explains a lot. `.to[Set]` should be just as good, thanks!

**Comment by nafg** [comment]
Should this be closed?

**Comment by kubukoz** [comment]
Yeah, I think so
