### ISSUE TITLE
Field autoincrement for Oracle without trigger?

### ISSUE THREAD

**Issue by Ivykp** [slick/slick#1710]
Hello everybody,

I am trying to insert rows in a ErrorTable which has a few fields plus an idError which is supossed to be the primary key, i need idError to be autoincremented. However one requirement is we cannot use a trigger, so using O.AutoInc would not work for us.

We also tried to use plain sql using a sequence, however we have 2 blob fields which makes the query too long, getting the string literal too long error.

Some idea about how to attack this problem? I am also considering to use UUID.

Thanks for the time!

**Comment by trevorsibanda** [comment]
@Ivykp I hope you managed to find a suitable solution.

Usually the [Gitter Channel](https://gitter.im/slick/slick) is the best place for questions, not the issue tracker. 

I'm going to close this, feel free to re-open it
