### ISSUE TITLE
 distinctOn doesn't seem to work

### ISSUE THREAD

**Issue by cvogt** [slick/slick#1712]

**Comment by cvogt** [comment]
@nafg writes:
> his doesn't have tests for distinctOn. It doesn't seem to work -- it puts all the columns in the ON list, not just the one I specified.

see https://github.com/slick/slick/pull/1271#issuecomment-289607725

**Comment by nafg** [comment]
Thanks for opening. ;) Possible duplicate of #1340

**Comment by klclee** [comment]
Hi guys is there some advance in this? Coming on the same problem

**Comment by hvesalai** [comment]
Duplicat eof #1340
