### ISSUE TITLE
Slick codegen not giving any output

### ISSUE THREAD

**Issue by samikrc** [slick/slick#1718]
I am trying to use the current version of slick and slick-codegen (3.2.0) with a sqlite database, using sqlite-jdbc:3.8.7 as recommended. When I try listing the table, I get the names properly. However, when I try to generate classes corresponding to the tables, I do not get any output.

This works:
```
object TableCodeGenerator extends App
{
	val db = Database.forURL("jdbc:sqlite:/home/samik/db/mydb.db", driver = "org.sqlite.JDBC")
	val tables = Await.result(db.run(MTable.getTables), 1 second).toList
	tables.foreach(println)
}
```
I get the output below:
```
MTable(MQName(models),TABLE,null,None,None,None)
MTable(MQName(users),TABLE,null,None,None,None)
```

However, the following code, run directly in the same way, doesn't work:
```
object TableCodeGenerator extends App
{
    val db = Database.forURL("jdbc:sqlite:/home/samik/db/mydb.db", driver = "org.sqlite.JDBC")
    val dbio = SQLiteProfile.createModel(Some(MTable.getTables))
    val model = db.run(dbio)

    val codegenFuture: Future[SourceCodeGenerator] = model.map(model => new SourceCodeGenerator(model))

    codegenFuture.onSuccess
    {
        case codegen => codegen.writeToFile(
            "slick.jdbc.SQLiteProfile",
            "/tmp",
            "my.package.dao",
            "Tables",
            "Tables.scala")
    }
}
```
Meaning, the code runs successfully, but I do not see any output file. Is there anything I am missing?

Also, I tried running the code below:
```
object TableCodeGenerator extends App
{
	slick.codegen.SourceCodeGenerator.main(Array(
		"slick.jdbc.SQLiteProfile", 
		"org.sqlite.JDBC", 
		"jdbc:sqlite:/home/samik/db/optcloud.db", 
		"/tmp", 
		"my.package.dao"))
}
```
But that returns an exception, which I have no clue how to resolve. 
```
/opt/jdk/bin/java ...
Exception in thread "main" scala.MatchError:  (of class java.lang.String)
	at slick.jdbc.SQLiteProfile$ModelBuilder$$anon$1.<init>(SQLiteProfile.scala:101)
	at slick.jdbc.SQLiteProfile$ModelBuilder.createColumnBuilder(SQLiteProfile.scala:98)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder$$anonfun$columns$1.apply(JdbcModelBuilder.scala:163)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns$lzycompute(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.columns(JdbcModelBuilder.scala:163)
	at slick.jdbc.JdbcModelBuilder$TableBuilder.buildModel(JdbcModelBuilder.scala:161)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
	at slick.jdbc.JdbcModelBuilder$$anonfun$buildModel$3$$anonfun$apply$17.apply(JdbcModelBuilder.scala:96)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
        ...
```

Any pointers on the above issues using each of the approaches? 
Many thanks.

**Comment by cvogt** [comment]
if you check this file (https://github.com/slick/slick/blob/51e14f2756ed29b8c92a24b0ae24f2acd0b85c6f/slick-codegen/src/main/scala/slick/codegen/OutputHelpers.scala), you should be able to run `packageCode` directly and look at it. Don't know why you are not seeing the file being written.

**Comment by cvogt** [comment]
The exception you are seeing in the end seems to be caused by a typeName slick doesn't expect. You could try printing it and see if you can work out a fix: https://github.com/slick/slick/blob/3.2/slick/src/main/scala/slick/jdbc/SQLiteProfile.scala#L101

**Comment by samikrc** [comment]
Just to make sure I understand: both the suggestions would need me to download the slick codebase, add print statements etc., compile and run through, right?

**Comment by cvogt** [comment]
The `packageCode` one no, you can read the code here but call the pre-compiled method. The second one maybe, but not necessarily. You can extend and override from your project or copy the source code of only the driver into it. It may turn out easier to download slick in the end, patching it as is and publishing it locally may be easier. One of the beauty of open source is that the code is right there and you can play with it and debug it. Even though Scala's tooling around it isn't the greatest.

**Comment by samikrc** [comment]
Thanks Jan. Trying out the packageCode method: I am confused about the last parameter: parentType (Option[String]). It is not documented in the code in the list of parameters, and I could not find any example either. Can you provide some pointer about what that parameter should be?

Will go down the source code route soon as well.

Regards.

**Comment by samikrc** [comment]
I did some more investigation and what I am observing is that, the following works:
```
    val tables = Await.result(db.run(MTable.getTables), 1 second).toList
    tables.foreach(println)
```
But, this doesn't work:
```
    val f: Future[Seq[MTable]] = db.run(MTable.getTables)
    f.onSuccess{ case s => s.foreach(println) }
```
Meaning, the onSuccess block is never executed (I ascertained this through debug mode). The problem seem to have nothing to do with the code generation side - the handling of 'Future' is not working for executions in some sense. 

Any pointers?

**Comment by cvogt** [comment]
Did wait for the future to finish before termination of your program? Use Await.result.

**Comment by samikrc** [comment]
Like this?
```
    val f: Future[Seq[MTable]] = db.run(MTable.getTables)
    f.onSuccess{ case s => s.foreach(println) }
    Await.result(f, Duration.Inf)
```
Still no result. Am I missing something?

**Comment by cvogt** [comment]
try
```
    val f: Future[Seq[MTable]] = db.run(MTable.getTables).map{ case s => s.foreach(println) }
    Await.result(f, Duration.Inf)
```

I unfortunately have limited time to help with just general debugging of Scala. You may want to try gitter for more help.

**Comment by samikrc** [comment]
Hi Jan,

Thanks - I have moved that conversation to gitter. 

I have also found out the source of the Exception. I use the following DDL for creating table in SQLite:
```
CREATE TABLE models (modelKey PRIMARY KEY, devKey REFERENCES users (devKey), name, lang, version, code)
```
SQLite assumes that, when datatype is not mentioned, it is stored as TEXT (https://sqlite.org/datatype3.html), so when that is the intended datatype, you do not need to mention it in the DDL. However, that seemed to have trumped slick, since `meta.TypeName` was coming as blank. 

One fix is that I change the DDL, which I think I will do. It is better from maintainability perspective. The other, code fix would be if `meta.TypeName` in https://github.com/slick/slick/blob/3.2/slick/src/main/scala/slick/jdbc/SQLiteProfile.scala#L101 is coming in as blank, to use the type as `TEXT` instead.

Regards.
-Samik

**Comment by trevorsibanda** [comment]
@samikrc Have a look at #1722

**Comment by cvogt** [comment]
We'll probably get a new slick version with this fix out within a week or two

**Comment by samikrc** [comment]
I checked out the fix - looks good. Thanks Trevor and Jan. Closing.
