### ISSUE TITLE
RelationalProfile does not support java.sql.Date columns

### ISSUE THREAD

**Issue by deusaquilus** [slick/slick#1724]
I am using a simplified Multi-DB pattern in order to be able to test my queries with different databases and the Heap, the latter is really important because H2 and Hsqldb are way too slow for my tests.
```scala
class QueryMaker(val profile: RelationalProfile, date:java.sql.Date) extends ProfileComponent  {
    import profile.api._
    for {
        myTable <- TableQuery[MyTable] if myTable.dateColumn === date.bind
    } yield (myTable.dateColumn, myTable.otherColumn)
}
```
The problem is that since RelationalProfile doesn't have a Jdbc Date type, the bind doesn't work because there's no TypedType of java.sql.Date and the === doesn't work because there's no OptionMapper for java.sql.Date.
Any ideas how I could get this working?

**Comment by deusaquilus** [comment]
The best I could do is a conditional import (below) which works but is far, far from ideal.
```scala
implicit val dateColumnType = if (profile.isInstanceOf[JdbcProfile]) {
      profile.asInstanceOf[JdbcProfile].api.dateColumnType
} else {
      MappedColumnType.base[java.sql.Date, Long](
        { date => date.getTime },
        { epochTime => new java.sql.Date(epochTime) })
}
```
Anyone have any ideas on how this could be done in a better or safer way?

**Comment by cvogt** [comment]
@trevorsibanda if you have a second, maybe you'd like to take a look

**Comment by hvesalai** [comment]
Best option is to implement it your self, look for example how it is done in https://github.com/tminglei/slick-pg
