### ISSUE TITLE
Document totally fails to describe the imports and how to use them

### ISSUE THREAD

**Issue by armtuk** [slick/slick#1732]
http://slick.lightbend.com/doc/3.1.0/queries.html

On this page it sets up the most basic example of an object mapping.  And yet, it totally fails to give you any imports!!!!  You have to go digging through google, and even then, it still a total mystery as to what works and what doesn't.  After two hours of messing about desperately attempting to get this working, I'm STILL getting a compile error.

This is the third or fourth time bootstrapping from scratch with Slick on a project, and every time I run into this same problem since slick 1.0.0.  At this point in my career journey, I just don't have time anymore to mess with this.  If it doesn't work out of the box, forget it.  DOA.

**Comment by szeiger** [comment]
The "most basic example" is http://slick.lightbend.com/doc/3.1.0/gettingstarted.html. Later chapters like "Queries" cover specific features in more detail. Their snippets generally require a single `.api._` import from a profile. The new documentation system for 3.2.1+ will link the snippets to the sources on github so you can see all snippet code in the context of a full compilation unit.

**Comment by cvogt** [comment]
@d6y what do you think about this topic?

**Comment by d6y** [comment]
A reminder at the start of each major section regarding the imports and a link back to "Getting Started" could be good.  The reminder is for those finding their way in Slick, and as a signal to new users as to where they should start from.

Using the latest ([Ornate](https://github.com/szeiger/ornate)-based) doc in master, this is what I mean (the yellow note box):

![queries 2017-06-01 19-41-16](https://cloud.githubusercontent.com/assets/102661/26695305/56f55bb2-4702-11e7-9820-833ba025963d.png)

---
Happy to run through the main pages and insert that, if we like it.

**Comment by cvogt** [comment]
it's a good idea I think. +1 from me
