### ISSUE TITLE
MySQL's SMALLINT unsigned should be presented as INT instead of SHORT

### ISSUE THREAD

**Issue by luzhongjian** [slick/slick#1734]
I was using slickVersion = "3.2.0-M2" against MySQL server v5.7 running on CentOS and found out that MySQL's SMALLINT UNSIGNED being converted to Short in source code generated by slick.codegen.SourceCodeGenerator. UNSIGNED SMALLINT in MySQL should be converted to Int in scala source code as it is unsigned. What is more, according to https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-type-conversions.html, I presume SMALL SIGNED should also be converted to Int in scala source code. And I quote ``java.lang.Integer (regardless of whether it is UNSIGNED or not)''.

**Comment by trevorsibanda** [comment]
Merged fix #1735 
Feel free to reopen this issue if there's anything else
