### ISSUE TITLE
 The right syntax to use near '(6) NOT NULL DEFAULT NULL COMMENT CURRENT_TIMESTAMP(6),

### ISSUE THREAD

**Issue by HidTosh** [slick/slick#1740]
When creating this table I hate this error ! need some help please

CREATE TABLE `count_portfolio_display` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mtr_portfolio_id` int(11) NOT NULL,
  `timestamp` timestamp(6) NULL DEFAULT NULL COMMENT 'in microsecond',
  PRIMARY KEY (`id`),
  KEY `count_portfolio_display_mtr_portfolio_id_idx` (`mtr_portfolio_id`),
  KEY `search` (`id`,`mtr_portfolio_id`,`timestamp`),
  CONSTRAINT `count_portfolio_display_mtr_portfolio_id`, 
  FOREIGN KEY (`mtr_portfolio_id`), 
  REFERENCES `MTRUser`.`mtr_portfolios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,

) ENGINE=InnoDB AUTO_INCREMENT=1594965 DEFAULT CHARSET=latin1;
/*!40101 SET character_set_client = @saved_cs_client */;

ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(6) NOT NULL DEFAULT NULL COMMENT CURRENT_TIMESTAMP(6),

**Comment by trevorsibanda** [comment]
@HidTosh this doesn't seem to be a bug with Slick, rather MySQL syntax error. The error is self explanatory. have a look at https://stackoverflow.com/questions/23515347/how-can-i-fix-mysql-error-1064

Closing this, feel free to reopen it
