### ISSUE TITLE
custom code generator improvement

### ISSUE THREAD

**Issue by mendrik** [slick/slick#1747]
If one wants to use a custom code generator one has to copy a lot of boilerplate to replace/extend the original one. Could the sbt argument array take a class reference as it's done for slick profile and db driver and use that instead of implementing one's own static main & run method.

**Comment by mendrik** [comment]
to elaborate: instead of new SourceCodeGenerator(model) in the current runner, one could use Class.forName(...)

**Comment by cvogt** [comment]
Sounds like a good idea. I'd be happy to review it if you want to open a PR

**Comment by mendrik** [comment]
I'll try :)

**Comment by mendrik** [comment]
Is there some special settings I should apply in Intellij, sbt compiles fine but I get some highlighted errors in my IDE, i use sbt 13 and scala 2.11.11
![image](https://user-images.githubusercontent.com/160805/27259630-c0af26f8-541f-11e7-8e34-bef301b95cb2.png)
