### ISSUE TITLE
removing slide from left

### ISSUE THREAD

**Issue by pdamartechnopartner** [slick/slick#1755]
Hi, I'm trying to remove a slide on `afterChange` with `$(".element").slick('slickRemove', currentSlide-1)`, and then create another slide afterwards.

`$(".element").slick('slickRemove', currentSlide-1);`
`$(".element").slick('slickAdd', stringToAdd);`

The problem is, the next slide after the current one will be skipped. any idea how to fix this?

**Comment by trevorsibanda** [comment]
Wrong github page
