### ISSUE TITLE
DBIO.from not rollback if outer transaction failed 

### ISSUE THREAD

**Issue by pangwa** [slick/slick#1759]
```scala
def updateUser(uid: Long) = db.run(Users.filter(_.id === uid).map(_.name).update("test).transactinally)
def outerTrans() = db.run((for {
  _ <- DBIO.from(updateUser(123L)
 _ <- DBIO.fail(new Exception("just fail..")
).transactionally) 
```
The updateUser(123L) isn't rollback(which I think it should as the outer transaction failed.)

**Comment by AtkinsChang** [comment]
The method `updateUser` will execute statement and commit in a session while `outerTrans` is executed in another session. So the column `name` will be updated to "test".
The correct way is make then execute in same session.
```
def updateUser(uid: Long) = users.filter(_.id === uid).map(_.name).update("test").transactionally
def outerTrans() = db.run {
  (for {
    _ <- updateUser(123L)
    _ <- DBIO.failed(new Exception("just fail.."))
  } yield ()).transactionally
}
```

**Comment by cvogt** [comment]
@pangwa that code sample is syntactically incomplete. hard to tell what's called on what there. feel free to re-open with a better code sample.
