### ISSUE TITLE
Postgres timestamps returning with inconsistent precision on reads after prepared statement threshold

### ISSUE THREAD

**Issue by michaelzg** [slick/slick#1763]
## Description and Context
Slick (and also hikari-cp) version 3.2.1
PostgreSQL JDBC driver version 42.1.1
PostgreSQL 9.6.3
Scala 2.11.8

Reading a PostgreSQL `TIMESTAMP` using plain SQL returns an inconsistent format after the 5th query (deterministically). `000` gets appended to create what looks like a timestamp with microsecond precision.

## Observed Behavior
I wrote a test to showcase this, here is the screenshot. The test code is provided in the Recreate section below.

![image](https://user-images.githubusercontent.com/5251779/28445357-c3f1948c-6d78-11e7-8a5e-c42cc600e0fa.png)

## Expected Behavior
The timestamp format on reads should remain consistent.

## Recreate
The ScalaTest code from the screenshot above is here:
```scala
import org.joda.time.DateTimeZone
import org.joda.time.format.DateTimeFormat
import org.scalatest.{AsyncFreeSpecLike, Matchers}
import slick.jdbc
import slick.jdbc.JdbcBackend
import slick.jdbc.PostgresProfile.api._

class Investigation extends AsyncFreeSpecLike with Matchers {

  val db: jdbc.JdbcBackend.Database = JdbcBackend.Database.forConfig("config.postgres")
  
  val pattern = "yyyy-MM-dd HH:mm:ss.SSS"
  val formatter = DateTimeFormat.forPattern(pattern).withZone(DateTimeZone.UTC)
  val timestamp = "2017-07-21 00:21:01.132"

  s"writing timestamp $timestamp with millisecond precision should succeed" in {
    db.run(
      sqlu"""
      INSERT INTO investigation
      VALUES ($timestamp::TIMESTAMP);
      """
    ).transform(_ => succeed, _ => fail)
  }

  (1 to 5).foreach{ i =>
    s"reading timestamp $i time should match the expected timestamp format" in {
      db.run(
        sql"""
      SELECT test_timestamp FROM investigation
      """.as[String]
      ).map { result =>
        val ts = result.head
        println(s"Query timestamp result: $ts")
        ts shouldBe timestamp
      }
    }
  }

  s"reading timestamp a 6th time should fail" in {
    db.run(
      sql"""
      SELECT test_timestamp FROM investigation
      """.as[String]
    ).map { result =>
      val ts = result.head
      println(s"Query timestamp result: $ts")
      ts shouldBe timestamp
    }
  }

  "a 7th read using the underlying JDBC connection passes!" in {
    val qs = """ SELECT test_timestamp FROM investigation """
    val query = SimpleDBIO { x =>
      val stmt = x.connection.createStatement()
      val rs = stmt.executeQuery(qs)
      rs.next()
      val ts = rs.getString("test_timestamp")
      println(s"7th read query using JDBC connection: $ts")
      ts shouldBe timestamp
    }
    db.run(query)
  }

  s"reading timestamp a 8th time using Slick should fail still" in {
    db.run(
      sql"""
      SELECT test_timestamp FROM investigation
      """.as[String]
    ).map { result =>
      val ts = result.head
      println(s"Query timestamp result: $ts")
      ts shouldBe timestamp
    }
  }
}

```

To be thorough, here is a rough and simplified template of how I set the database up locally. I used the postgres docker image. I provide the schema of the `investigation` table as well.

init.sql schema
```
CREATE TABLE IF NOT EXISTS investigation (
  test_timestamp TIMESTAMP NOT NULL
);
```

Dockerfile
```
FROM postgres:9.6.3

ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres
ENV POSTGRES_DB testdb

COPY init.sql /docker-entrypoint-initdb.d/init.sql
```

application.conf
```
config {
  postgres {
    dataSourceClass = "slick.jdbc.DatabaseUrlDataSource"
    properties = {
      driver = "org.postgresql.Driver"
      url = "jdbc:postgresql://127.0.0.1:5432/testdb"
      user = "postgres"
      password = "postgres"
    }
  }
}
```

**Comment by pettyjamesm** [comment]
An interesting note on this behavior: the Postgres JDBC driver is set up to only switch to using server-side prepared statements after 5 client side queries. That might explain the magical number here. To confirm, you can add the `"prepareThreshold"` parameter to your url. Relevant postgres JDBC docs [here](https://jdbc.postgresql.org/documentation/head/server-prepare.html) and [here](https://jdbc.postgresql.org/documentation/head/connect.html).

**Comment by michaelzg** [comment]
Thank you @pettyjamesm! Your comment led me to find more clarity.

For starters, disabling prepared statements through  `prepareThreshold=0` resulted in consistent behavior. Here are the same tests re-run after changing my jdbc connection url to be:

```
jdbc:postgresql://127.0.0.1:5432/testdb?prepareThreshold=0
```

![image](https://user-images.githubusercontent.com/5251779/28496069-83b89196-6f16-11e7-8c79-ca938929ee75.png)

And it further explains why my original test showcasing that 7th query passing using the underlying JDBC connection--i was using `createStatement()` rather than `prepareStatement(String sql)`.

However, one may hesitate to call it a "solution" since there is a potential performance hit in globally disabling prepared statements to work around this issue. I tried to further investigate why this was happening. Slick ["uses prepared statements wherever possible but it does not cache them on its own"](http://slick.lightbend.com/doc/3.2.0/database.html), so perhaps something useful to add in order to give users more flexibility is an option to enable/disable the use of prepared statements in certain situations.

The root cause is likely something deeper in the postgres JDBC driver. I found some hints from https://github.com/pgjdbc/pgjdbc/issues/130 where it was stated:

> As for what the driver is doing with the timestamp - all PostgreSQL returns for timestamp without time zone is a uint64 with some pretty formatting (or, with the binary protocol, just the uint64).

So one guess would be that the use of prepared statement causes the timestamp on `SELECT` to use microsecond precision and append those extra `000` on a timestamp with only millisecond precision. But, if this was indeed the case, I would imagine more people taking notice. Anyhow, the place for delving deeper into the root of this issue will be within pgdbc. If i have the bandwidth, I'll try to re-create using pgjdbc in Java and post something.

I'll close this.

**Comment by michaelzg** [comment]
Re-opening upon being unable to re-create this issue using the JDBC `prepareStatement`.

Here is a screenshot with some additional test results comparing the JDBC results with that of Slick's plain SQL. Also note, I have set `prepareThreshold=2` for both cases.

![image](https://user-images.githubusercontent.com/5251779/28496383-31da07e4-6f1e-11e7-9890-25c18fcf9d3f.png)

I have even tried to mirror how [Slick calls with `prepareStatement` with certain ResultSet type and concurrency](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/JdbcBackend.scala#L320). Same issue.

```
val stmt = conn.prepareStatement(qs, ResultSet.TYPE_FORWARD_ONLY, ResultSet.CONCUR_READ_ONLY)
```

Here is the relevant snippet in my new test code:

```

val pattern = "yyyy-MM-dd HH:mm:ss.SSS"
val formatter = DateTimeFormat.forPattern(pattern).withZone(DateTimeZone.UTC)
val timestamp = "2017-07-21 00:21:01.132"

s"writing timestamp $timestamp with millisecond precision should succeed" in {
  db.run(
    sqlu"""
    INSERT INTO investigation
    VALUES ($timestamp::TIMESTAMP);
    """
  ).transform(_ => succeed, _ => fail)
}

(1 to 4).foreach { i =>
  s"$i: Read using JDBC connection" in {
    import java.sql.DriverManager
    val url = "jdbc:postgresql://127.0.0.1:5432/testdb?user=postgres&password=postgres&prepareThreshold=2"
    val conn = DriverManager.getConnection(url)
    val qs = """ SELECT test_timestamp FROM investigation """
    val stmt = conn.prepareStatement(qs)
    val rs = stmt.executeQuery()
    rs.next()
    val ts = rs.getString("test_timestamp")
    println(s"$i: JDBC query result: $ts")
    ts shouldBe timestamp
  }
}

(1 to 4).foreach { i =>
  s"$i Read using Slick plain SQL" in {
    db.run(
      sql"""
      SELECT test_timestamp FROM investigation
      """.as[String]
    ).map { result =>
      val ts = result.head
      println(s"$i: Slick query result: $ts")
      ts shouldBe timestamp
    }
  }
}
```

Could this be something within Slick or Slick-hikaricp?

**Comment by AtkinsChang** [comment]
You should use same connection for testing instead creating new one every time, then it will fail at the third time (remember to close `stmt` and `rs`).

**Comment by michaelzg** [comment]
@AtkinsChang thank you for pointing out my mistake! I was indeed able to recreate the issue with the Postgres JDBC driver following your suggestions. Thus, I have opened https://github.com/pgjdbc/pgjdbc/issues/885 to track this issue further.

I will close this (again). Thanks everyone!
