### ISSUE TITLE
Result action broken with plain SQL queries

### ISSUE THREAD

**Issue by dominikschmid** [slick/slick#1764]
```
import slick.jdbc.H2Profile.api._

sql"""select c.name, s.name
      from coffees c, suppliers s
      where c.price < 42 and s.id = c.sup_id""".as[(String, String)].result
```

Error:(35, 71) value result is not a member of slick.sql.SqlStreamingAction[Vector[(String, String)],(String, String),slick.dbio.Effect]
      where c.price < 42 and s.id = c.sup_id""".as[(String, String)].result
                                                                     ^

**Comment by LoranceChen** [comment]
Plain sql shouldn't use `result` operator
```
db.run(sql"""select c.name, s.name
      from coffees c, suppliers s
      where c.price < 42 and s.id = c.sup_id""".as[(String, String)]) 
```

Also hope slick could improve document.

**Comment by d6y** [comment]
Hi @dominikschmid and @LoranceChen - do you have any thoughts on what would improve the documentation?  

It looks like the SQL example comes from the [result set section](http://slick.lightbend.com/doc/3.2.1/sql.html#result-sets) of the Plain SQL page.  The example on the page is correct, and the text says: "This results in a `DBIO[Seq[(String, String)]]`."  I guess we could add to that: "This means it is an action ready to pass to `db.run`" or similar.

The top of the page says: "All Plain SQL queries result in DBIOAction that can be composed and run like any other action."  Maybe we can add: "That is, there is no `.result` method to call for Plain SQL Queries".

Would either of those suggestions help? Do you have any other ideas?

Thanks!

**Comment by dominikschmid** [comment]
Maybe it would be best to show a full example including `db.run`. 

For me it was also confusing that code completion in Intellij seems to suggest there is a `result ` method but when selected it is marked "red". Not sure why that is.

**Comment by LoranceChen** [comment]
Hi @d6y , I think a restful document, just like @dominikschmid refers that should add a full relative code in document example, will be welcome.After all, make program works is first things when use a new library but at this point we haven't know enough concept of the library.

On another sight, I recommend adopt unit test as a part of document. like [this git example](https://github.com/underscoreio/essential-slick-code) making usage straight to understand. Linking a unit test file to download below a simple example code or at the bottom of a chapter is also recommend.

Finally, I'm feeling difficult to read slick source code even though I have familiar with Scala language for a long time. I'm very very hope slick could give a guide of how does it implement.It's not care about how to use slick but how to implement it.

Thanks
