### ISSUE TITLE
Problems in the published Slick 3.2.1 manual

### ISSUE THREAD

**Issue by szeiger** [slick/slick#1766]
- http://slick.lightbend.com/doc/3.2.1/gettingstarted.html still points to (non-existent) Activator templates. It should point to the correct github location of the sample projects that are now included in the main Slick repo

- The multi-version dropdown doesn't work because github doesn't generate index pages (i.e. http://slick.lightbend.com/doc/ is a 404). We should make it scrape our manually generated index http://slick.lightbend.com/docs/ (note the "s" at the end) instead.

**Comment by cooervo** [comment]
+1 on this, all activator links I have encountered are broken.

**Comment by dmitraver** [comment]
@szeiger hi, I've looked into it already as a part of #1789. However, I haven't found any g8 templates for slick. Should the new link point to http://developer.lightbend.com/start/?group=slick then ? This page has hello slick 3.1 examples only and not 3.2.

**Comment by smourapina** [comment]
Just want to point out that these links are still broken in the latest version (http://slick.lightbend.com/doc/3.3.1/gettingstarted.html). The links would now point to the GH repos linked in https://developer.lightbend.com/start/?group=slick

**Comment by kluen** [comment]
Also, the Github links in on the [Getting Started page](http://slick.lightbend.com/doc/3.3.1/gettingstarted.html) point to the non-existent branch `3.3`, for example in https://github.com/slick/slick/tree/3.3/samples/hello-slick. I guess it is supposed to be pointing to the branch `3.3.x`?

**Comment by ochnev** [comment]
https://github.com/slick/slick/tree/3.3/samples/hello-slick
https://github.com/slick/slick/tree/3.3/samples/slick-plainsql
Actually, all the links to all the samples are broken.
Real working samples are badly needed!

**Comment by hvesalai** [comment]
Hmm... I wonder what broke them. They are there on master https://github.com/slick/slick/blob/master/samples/hello-slick/README

**Comment by ochnev** [comment]
> Hmm... I wonder what broke them. They are there on master https://github.com/slick/slick/blob/master/samples/hello-slick/README

Yes, finally, I've found them recently.
The links to the numbered versions are broken, the master version link is OK.

**Comment by SethTisue** [comment]
if someone is still concerned about this, please open a new ticket clarifying the current status (much of the previous discussion is about very old Slick versions)
