### ISSUE TITLE
Turning off Slick Logging in a Play Framework based Web Application

### ISSUE THREAD

**Issue by joesan** [slick/slick#1776]
My project is a Play Framework based web project and here is what I have as my dependency in my build.sbt:

```
libraryDependencies ++= Seq(
  ws,
  "io.monix" %% "monix" % "2.1.0",
  "com.typesafe.slick" %% "slick" % "3.2.0",
  "com.typesafe.scala-logging" %% "scala-logging" % "3.4.0",
  "org.scala-lang.modules" % "scala-async_2.11" % "0.9.6",
  "com.zaxxer" % "HikariCP" % "2.4.1",
  "com.typesafe" % "config" % "1.3.1",
  "mysql" % "mysql-connector-java" % "5.1.26",

  // test
  "com.typesafe.akka" %% "akka-testkit" % "2.5.2" % Test,
  "org.scalatest" %% "scalatest" % "3.0.1" % Test,
  "com.h2database" % "h2" % "1.4.186" % Test,
"org.scalatestplus.play" %% "scalatestplus-play" % "1.5.0" % Test
)
```

I tried the following:

Set the logLevel in build.sbt to INFO

`logLevel := Level.Info`

Unfortunately that did not have any effect!

I used a test-logger.xml that looks like this:

```
<logger name="scala.slick" level="INFO" />
<logger name="play" level="INFO" />
<logger name="application" level="INFO" />
<logger name="akka" level="INFO" />
```

and used the following command when I run my unit tests:

`sbt -Dlogger.resource=conf/test-logger.xml clean coverage test coverageReport`

But strangely, that did not have any effect at all as I still keep seeing those annoying DEBUG statements! I'm using Play Framework 2.5.9!

Is this a bug?

**Comment by jishnair** [comment]
I don't know whether this the correct way, but adding the following in the xml file works.
```
<root level="info">
        <appender-ref ref="STDOUT"/>
</root>
```
Regards,
Jishnu
