### ISSUE TITLE
Schema not found when using tables with schemas

### ISSUE THREAD

**Issue by beethovenklc** [slick/slick#1786]
Hello, I'm trying to create some unit tests using an in memory h2 database.

When I try to create table schemas, I would get an exception "Schema -- not found", even if I run an action to create the schema (tried several ways).

If the table doesn't use a schema, table schemas are created without errors.

I'm running scala version 2.12.3, sbt 1.0 in Ubuntu 16.04 64 bits and the following lib versions:
  com.typesafe.slick:slick_2.12:3.2.0
  com.h2database:h2:1.4.195

Is there a way that I can create a schema to overcome this error? Or is this a bug?

Thanks!

Here is the code:

```
sealed case class Employee(
    id: String,
    name: String
  )

///// if I use (tag, "employee") instead of (tag, Some("people"), "employee") it works (but PROD db has a schema)
  class Employee(tag: Tag) extends Table[model.Employee](tag, Some("people"), "employee") {
    def id: Rep[String] = column[String]("id", O.PrimaryKey)
    def name: Rep[String] = column[String]("name")
  }

///// also tried adding schema creation inside the forURL parameter
  val db = Database.forURL("jdbc:h2:mem:test", driver = "org.h2.Driver")
  val employeeTableQuery = TableQuery[table.Employee]

  val createSchemasAction = sqlu"""CREATE SCHEMA people;"""

  val setup = DBIO.seq(
    createSchemasAction,

    // Create the tables, including primary and foreign keys
    employeeTableQuery.schema.create,

    // Insert an employee
    employeeTableQuery += Employee("1", "Tom")
  )

  db.run(setup).onComplete {
    res =>
///// org.h2.jdbc.JdbcSQLException: Schema "people" not found; SQL statement: create table "people"."employee" (..)
      println(res)                  
  }
```

**Comment by cvogt** [comment]
You probably need to set DB_CLOSE_DELAY. See https://stackoverflow.com/questions/5763747/h2-in-memory-database-table-not-found

Reopen if still an issue

**Comment by beethovenklc** [comment]
Hello again. Thanks for you reply.

DB_CLOSE_DELAY in this case was not necessary, but I'll need it later if I want to run more than one query :+1: 

Still, using this option, queries would throw an exception and complains that the schema doesn't exist. It only works if the table class doesn't provide a schema.

Now I have two queries (using DB_CLOSE_DELAY) to see which values are being returned for each. See the code below:

```
// also tried without the MODE option (the real database is a postgresql)
val db = Database.forURL("jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;", driver = "org.h2.Driver")

val createSchemasAction = sqlu"""CREATE SCHEMA people;"""

val prepareDatabaseFutureValue = Await.ready(
  db.run(
    DBIO.seq(
      createSchemasAction, // not necessary if there is no schema, but still works
      employeeTableQuery.schema.create,
      employeeTableQuery += Employee("1", "Tom")
    ).transactionally),
  30 seconds).value

val searchFutureValue = Await.ready(
  db.run(
    employeeTableQuery.result),
  30 seconds).value
```

When table class doesn't use a schema:
```
prepareDatabaseFutureValue == Some(Success(()))
searchFutureValue == Some(Success(Vector(Employee("1","Tom"))))
```
When table class uses a schema (the problem):
```
prepareDatabaseFutureValue == Some(Failure(org.h2.jdbc.JdbcSQLException: Schema "people" not found; SQL statement: create table "people"."employee" (..)
searchFutureValue == Some(Failure(org.h2.jdbc.JdbcSQLException: Schema "people" not found; SQL statement: select "id", "name" from "people"."employee"
```

Maybe is something else missing? 

Thanks again!
