### ISSUE TITLE
Hello Slick template not working

### ISSUE THREAD

**Issue by minarth** [slick/slick#1789]
There is a link in documentation on page: http://slick.lightbend.com/doc/3.2.1/introduction.html#what-is-slick which points to 404 page on Activator.

**Comment by dmitraver** [comment]
hi, I can pick this one.

**Comment by trevorsibanda** [comment]
@dmitraver Awesome! Please do.

**Comment by dmitraver** [comment]
@trevorsivanda, I haven’t found any g8 templates for slick. Should the new link point to developer.lightbend.com/start/?group=slick then ? This page has hello slick 3.1 example only.

**Comment by hvesalai** [comment]
@dmitraver what is the status of this?

**Comment by Luka-Abey** [comment]
Heya any updates on this? All the links (GitHub and zips for the four examples) are broken. Happy to help, would just need to know the destination urls for these links !

**Comment by Luka-Abey** [comment]
Found the GitHub link - and opened a PR to at least sort half of the issue out. Zips are still a problem. https://github.com/slick/slick/pull/2143
