### ISSUE TITLE
ResultSetHelper skipUntilColumn does not work for Alias

### ISSUE THREAD

**Issue by moqichenle** [slick/slick#1791]
for example, 
```SQL
select t.id as hello, t.name from table t.
```
ResultSetHelper.skipUntilColumn("hello", r) does not work.

**Comment by d6y** [comment]
Hello @moqichenle - I don't believe there's a `ResultSetHelper` in this project. Did you mean a different project?

I'll close this issue, but feel free to re-open if I've misunderstood you.
