### ISSUE TITLE
For comprehensions with .exists

### ISSUE THREAD

**Issue by Abrasha** [slick/slick#1793]
Hi. I cannot find in documentation how can I use `exists` in Slick for comprehensions?

For example:

    // users, admins - tables
    for {
    	u <- users.filter(_.username === "Test").exists
    	m <- messages if u
    } yield m

This behavior can be easily achieved by using `flatMap` on actions:

    users.filter(_.username === "Test").exists.result.headOption flatMap {
    	case true => messages.result
    	case _ => DBIO.failed(new RuntimeException)
    }

P.S. examples are synthetic.

**Comment by lukaszwawrzyk** [comment]
Any slick query, with or without for comprehensions, will eventually become SQL that will be run on your database. How would you rewrite your first example to SQL? It is a good way to go when you can't figure how to write something in slick: to write SQL for that and then rewrite it to slick (it is ususally kind of natural). But I feel like this simply can't be rewritten to plain sql.
