### ISSUE TITLE
Support DATABASE_URL formats without a password

### ISSUE THREAD

**Issue by sloshy** [slick/slick#1804]
The DatabaseUrlDataSource implementation uses regexes of this format to detect a non-JDBC database URL:
```
"^(?:postgres|postgresql)://([a-zA-Z0-9_]+):([^@]+)@([^/]+)/([^\\s]+)$"
```
A similar regex exists for MySQL. This parses the username, password, host and database from the URL syntax but it does not take into account null passwords. According to the [PostgreSQL libpq documentation](https://www.postgresql.org/docs/9.3/static/libpq-connect.html), URLs of the format `postgres://user@host/db` are also accepted, indicating a null password. Currently, DatabaseUrlDataSource does not take this into account.

To fix this issue, the regexes would have to be modified to allow for optional passwords. A possible solution would be a regex of this format (note the non-capturing group around the colon):
```
"^(?:postgres|postgresql)://([a-zA-Z0-9_]+)(?::([^@]+))?@([^/]+)/([^\\s]+)$"
```
I am working on a PR for this issue myself and plan to submit it for review if this feature request is approved for the next Slick version. It's a small tweak and can be written up with a couple tests quickly.

Also, I have already signed the Lightbend CLA due to a previous PR I submitted to the Play team recently.

**Comment by cvogt** [comment]
merged
