### ISSUE TITLE
construction of cats-effect instance for DBIO

### ISSUE THREAD

**Issue by hejfelix** [slick/slick#1806]
I am wanting to create an instance of cats-effect for DBIO since this would greatly benefit my application logic, i.e. I would be able to create my entire computation inside DBIO.

It is not clear to me whether this is possible. The function that stops me from implementing the typeclass is `suspend` which has the following signature: `def suspend[A](thunk: => DBIO[A]): DBIO[A] = ???`. ([link](https://github.com/typelevel/cats-effect/blob/master/core/shared/src/main/scala/cats/effect/Sync.scala#L38))
Since DBIO has the method `def from[R](f: Future[R]): DBIOAction[R, NoStream, Effect]`, it would suggest to me that it is indeed possible to mix and match queries and general Scala computations inside DBIO's. However, I cannot construct a `Future` without eagerly evaluating the result, thus it is unsuited to implement `suspend`.

Is it possible to implement the suspend function for DBIO?

**Comment by alexander-branevskiy** [comment]
seems that it's possible to do using the approach below
DBIO.successful(()).map(_ => println("ok"))
