### ISSUE TITLE
maxConnections not properly being propagated to AsyncExecutor

### ISSUE THREAD

**Issue by renatocaval** [slick/slick#1814]
The value of `maxConnections` is not always propagated further to the `AsyncExecutor`.

## HikariCPJdbcDataSource - OK
When using Hikari, it is propagated. 

First, the property is used to configure Hikari pool size.
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick-hikaricp/src/main/scala/slick/jdbc/hikaricp/HikariCPJdbcDataSource.scala#L47-L48

Next, Hikari pool size is used to configure the `JdbcDataSource.maxConnection`
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick-hikaricp/src/main/scala/slick/jdbc/hikaricp/HikariCPJdbcDataSource.scala#L18

Finally, the `JdbcDataSource.maxConnections` is used to configure the `AsyncExecutor`  
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick/src/main/scala/slick/jdbc/JdbcBackend.scala#L290-L294

## DataSourceJdbcDataSource - NOK

`DataSourceJdbcDataSource` is used in two situations:

1. When user explicitly disable a connection pool
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick/src/main/scala/slick/jdbc/JdbcDataSource.scala#L40
In that case, `maxConnections` is not set and the `AsyncExecutor` with `numThreads * 5`

Note that maxConnections == None
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick/src/main/scala/slick/jdbc/JdbcDataSource.scala#L102

Later it folded and `numThreads * 5` is used.
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick/src/main/scala/slick/jdbc/JdbcBackend.scala#L290-L294

2. When user configures the connection using a JNDI resource. In that case, nothing is passed down to the `AsyncExecutor` and the final vaill will be `Integer.MAX_VALUE`
https://github.com/slick/slick/blob/65a59491fdf238bb0af581fefd80447bfd2540f9/slick/src/main/scala/slick/jdbc/JdbcBackend.scala#L105-L109

**Comment by hvesalai** [comment]
@renatocaval would you like to make a PR for a fix?

**Comment by renatocaval** [comment]
@hvesalai there is one already (PR #1815) 

However, I marked it as working in progress because I wanted to do some more tests, but it ended out of radar.

**Comment by hvesalai** [comment]
@renatocaval are you planning on finalizing it. My goal is to get a 3.2.2 release out soon with a set of fixes. This could fit in.

**Comment by renatocaval** [comment]
Ok, I will try to see if we can shuffle some priorities so I can finalise it.
