### ISSUE TITLE
Unable to use a custom profile with tsql

### ISSUE THREAD

**Issue by mattfeury** [slick/slick#1816]
Hello,

I am currently using tsql for a few queries.

However, if I go into `MyPostgresDriver.scala` and make *any* change (even a simple newline) and then try and run `sbt compile`, I get this error: `Cannot load @StaticDatabaseConfig("file:conf/application.conf#tsql"): Error getting instance of profile "utils.db.MyPostgresDriver$"`

Any clue why this is happening? if I had to guess I would say that making the change to my driver file removes it from the classpath, and it is not recompiled before the tsql macro runs. It's very frustrating because I can't make any code changes to my db logic.

thanks

**Comment by mattfeury** [comment]
just to follow up here, it really seems like any clean of my system where the `MyPostgresDriver` compiled class is removed causes this issue. so basically if I start with a fresh system, this won't work for me because the class is not compiled and the macro of tsql runs before it compiles it.

I added a debug log in the slick code and see this as the root exception: `java.lang.ClassNotFoundException: utils.db.MyPostgresDriver $` which seems to align with my thoughts above.

not sure how this could be working for others and not me. any ideas?

**Comment by mattfeury** [comment]
doing a little digging here and it seems like this may be because i'm using a custom driver?

this seems relevant  (i'm using slick-pg as well): https://github.com/slick/slick/pull/1152

**Comment by andrezimmermann** [comment]
It's neither a problem with slick or slick-pg, it's more like one pitfall of java/scala inter-op.
`MyPostgresDriver$` is a java class of a scala object, generated by the compiler.
The slick configuration takes a String. If you compile both the slick and this `MyPostgresDriver`, the java/scala compiler can't tell that need to compile `MyPostgresDriver` (to generate the `MyPostgresDriver$`) before validating the configuration. 
Moving the driver to a sub project and make a it as a dependency, is the most appropriated solution.

**Comment by mattfeury** [comment]
thanks for the reply @andrezimmermann. i get that and figured that it was the case. definitely see that it's a fundamental problem with the compiler. however, it would be good to see some extra documentation around this case in the tsql section.

i understand it's not a slick problem, per se, but as an end user of the library, it kind of is. the end user shouldn't care about all the nitty gritty of the library. the purpose of the library is to abstract all that. they should just be able to use all the features of the library as documented. in this case, that's not possible, so i think, in short of some really creative solution here (i tried to compile a single file using the [compile-quick plugin](https://github.com/etsy/sbt-compile-quick-plugin) but couldn't quite get it working – although I feel like it should work theoretically), the documentation should at least reflect the shortcomings.

there's a bit of my personal viewpoint in the above, but think at the end of the day would be good to document this use case for others. surprised i'm the first to run into it
