### ISSUE TITLE
ignoring an auto-increment column on insert or update

### ISSUE THREAD

**Issue by jcabrerazuniga** [slick/slick#1819]
We are using Scala and Slick and we created a function for an object that contains an auto increment column called myid that looks like:

     def convertFromJSON(....):
     ...
         if((json \ "myid").asOpt[Int].isEmpty) 0 else (json\"myid").as[Int])
     ...
    
unfortunately this is assigning by default a value of 0 to myId and this is happening every-time we create a new object. Is there a command to allow me to ignore this field? We are using mysql
thanks

**Comment by cvogt** [comment]
this doesn't look Slick related, rather play-json. Please try there or provide more context why you think this is a slick issue.
