### ISSUE TITLE
Optional filtering / Maybe filter - Filter on a conditional predicate

### ISSUE THREAD

**Issue by Asamsig** [slick/slick#1820]
One common headache my team has been encountering with Slick, is the need to optionally filter on a parameter, depending on if it is present or not.

Like this example:
`personTable.filter(person => Option.empty[String].map(name => person.name like name).getOrElse(valueToConstColumn(true)) && person.age > 18 )`

The generated SQL will be something like:

`select name, age from person where true and (age > 18)`

This is a bad coding experience, and a bad result.

What I suggest is implementing an `optionalFilter`, where you'd be able to write the former query like this:

`personTable.optionalFilter(Option.empty[String])(_.name like _).filter(_.age > 18)`

And then the generated SQL would be:

`select name, age from person where age > 18`

See this [gist](https://gist.github.com/cvogt/9193220) by cvogt as well.

If there is interest in adding this to core Slick, I'll be willing to implement this, currently we have added our own implicit class supplying this functionality.

**Comment by djx314** [comment]
You can use
```scala
val query1 = if (nameOpt.isDefined) {
  personTable.optionalFilter(_.name like nameOpt.get)
} else {
  personTable
}
query1.filter(_.age > 18)
```

And I prefer than implementing `filterIf` rather than `optionalFilter`.
```scala
personTable.optionalFilter(nameOpt.isDefined)(_.name like nameOpt.get)
```
`filterIf` is more common and can deal with more situations.

**Comment by Asamsig** [comment]
The problem I see with `filterIf`, is that you're still at the mercy of using `.get`, which is something many people try to avoid. I think that `filterIf`, could be useful as well, though my only problem so far, has been with Options. So as for the API, I'd like the idiomatic way to do it in Slick didn't involve `.isDefined` and `.get`.

As for naming I'm open for suggestions.

**Comment by djx314** [comment]
@Asamsig 
What I mean is not only the option. And alse
```scala
personTable.filterIf(model.isWomen)(_.age > 16)
  .filterIf(model.isMan)(_.age > 18)
```
```scala
personTable.filterIf(either.isLeft)(s => (s.successful === false) && (s.mark < 60))
  .filterIf(either.isRight)(s => (s.successful === true) && (s.mark < either.right.get))
```
It's better to use `filteIf` than use `optionalFilter` in the query above. So I just say it's more common.

**Comment by Asamsig** [comment]
Oh I agree, `filterIf` definitively has its use cases, and it adds a way to handle optional filtering. My inclination is more that both could be added.

I like the idea of `filterIf`, but I don't like how the handling of Options would turn out, as it would be very unidiomatic Scala, and somewhat counter intuitive for people used to handling Options.

`optionalFilter` should probably start with`filter*`, to be more intuitive in the API as well.

My intention of this issue, is also to hear what people think, if they think it would be bloat in the API, or if there actually is a demand for it. Since you can quite easily implement your known implicit enrichment to add this functionality.

**Comment by hvesalai** [comment]
We have filterIf implemented in our project like so:

```
    // CONDITIONAL QUERY FILTER

    implicit class ConditionalQueryFilter[A,B,C[_]](q: Query[A,B,C]) {
      def filterOpt[D, T <: Rep[_] : CanBeQueryCondition](option: Option[D])
                   (f: (A, D) => T): Query[A, B, C] =
        option.map(d => q.filter(a => f(a,d))).getOrElse(q)

      def filterIf(p: Boolean)(f: A => Rep[Boolean]): Query[A,B,C] =
        if (p) q.filter(f) else q
    }
```

**Comment by hvesalai** [comment]
If you would like to have this feature in Slick, I kindly ask you to make a PR

**Comment by XOfSpades** [comment]
Would be cool to have a release with this functionality. This is something which bites me currently in a JSON api with optional query parameters..

**Comment by waichee** [comment]
yep this is really handy.

any ETA on when the new release would be  @hvesalai ?

**Comment by nafg** [comment]
Seems like it's just released now

**Comment by yoshi49535** [comment]
https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/lifted/Query.scala#L64

Isn't this like below?

```
def filterIf[T <: Rep[_]: CanBeQueryCondition](p: Boolean)(f: E => T): Query[E, U, C] =
```

otherwise, nullable column cannot be filtered.

**Comment by hvesalai** [comment]
@yoshi49535 very nice! Can you make a pull request against master. This change needs to go into 3.4.0 since it is not binary compatible with 3.3.0

**Comment by nafg** [comment]
FWIW Quill just added a couple such things
