### ISSUE TITLE
Implement window function like LAG and LEAD sql function

### ISSUE THREAD

**Issue by lepirlouit** [slick/slick#1826]
Hello,Could you please implements the basic window functions ?

I dont know if this is available in the JDBC driver.

https://www.postgresql.org/docs/current/static/functions-window.html

**Comment by lepirlouit** [comment]
Slick-PG is implementing this and lot of other functions : 
https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/window/PgWindowFuncSupport.scala

Code can probably be integrated.

**Comment by hvesalai** [comment]
You should use slick-pg. It will not be integrated.
