### ISSUE TITLE
ORA-00942: table or view does not exist appearing for change in property file

### ISSUE THREAD

**Issue by shweta59** [slick/slick#1829]
I am having this error while adding new username and passwords in my connections.property file 
I am using Oracle database to connect.

Below is the content of property file

service=xxxx08-xx.xx.xxx-xxtx.com:1201
database=XXXX_1

username=FI_ANALYTIC_REPORTING
password=FI_ANALYTIC_REPORTING

username=FI_FMW
password=FI_FMW

username=FI_HOLDING
password=FI_HOLDING

And below is my dbFit testcase:-
!path lib/*.jar
!|dbfit.OracleTest|
!|ConnectUsingFile|credentials.properties|
!|Query|!- select distinct clr.fil_crude_type as RC  from FI_ANALYTIC_REPORTING.clr_xxxes clr ,FI_FMW.fmw_xxes fmw
where  clr.EFFECTIVE_DATE=fmw.EFFECTIVE_DATE
and clr.TRADABLE_ENT_ID=fmw.TRADABLE_ENT_ID
and clr.EFFECTIVE_DATE='09-nov-2017'
and fmw_xxx_type in('IRS_xx','TRS_SWxx','CDS_xx_xx') -!|
|RC|
|Derivative|.

It works fine if I change the username/passwords pair of connection property file as below:-
username=FI_FMW
password=FI_FMW

username=FI_ANALYTIC_REPORTING
password=FI_ANALYTIC_REPORTING.

Can anyone explain the reason and how can I put different username and passwords in a property file.
Thanks in advance .

**Comment by hvesalai** [comment]
Please post this question to one of the community forums. Reopen if there is a bug.
