### ISSUE TITLE
take and then drop generates "where 1=0" in sql

### ISSUE THREAD

**Issue by devwinportable** [slick/slick#1839]
I'm following the essential slick book, and at chapter2, there's drop and take.
I tried the reverse order, and it seems to break slick's sql generation.

Here's the example where drop->take works, but take->drop is funky:

```scala
import slick.jdbc.H2Profile.api._

case class Message(
    sender: String,
    content: String,
    id: Long = 0L
)

class MessageTable(tag: Tag) extends Table[Message](tag, "message") {
  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def sender = column[String]("sender")
  def content = column[String]("content")
  def * = (sender, content, id).mapTo[Message]
}

lazy val messages = TableQuery[MessageTable]

// OK: select "sender", "content", "id" from "message" order by "sender" limit 5 offset 5
messages.sortBy(_.sender).drop(5).take(5).result.statements.mkString

// ???: select "sender", "content", "id" from "message" where 1=0 order by "sender"
messages.sortBy(_.sender).take(5).drop(5).result.statements.mkString
```

**Comment by d6y** [comment]
Hello @devwinportable 👋 

The first thing to say is that it looks like Slick is producing a correct query (in the sense that the results will be right). So I read the question as: this is surprising. Why is it happening?

I don't know. But digging around.... 

- Your TAKE 5 and DROP 5 is carried through the Slick compiler phases right up to `mergeToComprehensions` (you can turn on the compiler phase logging with `  <logger name="slick.compiler.QueryCompiler" level="DEBUG"/>` in your `logback.xml`)
- At that point, it is converted into a FETCH 0, OFFSET 5.
- That FETCH 0 is [a case handled in the SQL generation](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/JdbcStatementBuilderComponent.scala#L127-L152) layer and turned into the `1 = 0` thing.

...why does that happen? I don't have the history on that but a total guess is that if you're returning zero rows, the where clause building is irrelevant and can be replaced with a logical `false`. Or it could be that some databases don't allow queries that use limits/fetches that produce zero rows.

If that answers the question, let me know, and I'll close the ticket.
