### ISSUE TITLE
How to have a  slick.lifted.Rep.None for a custom (multi-column) type ?

### ISSUE THREAD

**Issue by kheraud** [slick/slick#1846]
I try to map a `Element1` Query to a `(Element1, Option.empty[Element2])` Query to have this subquery included in a more complex query / join.

I tried `query.map(element1 => (element1, slick.lifted.Rep.None[Element2]))` to map my :
- `slick.lifted.Query[Element1Table, Element1Table#TableElementType, Seq]`
- to `slick.lifted.Query[(Element1Table, slick.lifted.Rep[Option[Element2Table]]),(Element1, Option[Element2]),Seq]`

But no matter what I try, an implicit `TypedType` is missing.

Digging in the source code I see that `slick.lifted.Rep.None` is `only supported for single-column values`. I understand that it won't work with my custom multi-column type. Right ?

Is there a workaround to be able to do my mapping rather than creating fake `joinLeft` on impossible `on` conditions ?

**Comment by hvesalai** [comment]
Please use other forums for support questions

**Comment by abhandaru** [comment]
Could you link to the correct forum?
I may have stumbled across a related issue and will need to continue digging.

**Comment by hvesalai** [comment]
http://slick.lightbend.com/community/
