### ISSUE TITLE
JdbcBackend.Database.forName potentially broken

### ISSUE THREAD

**Issue by renatocaval** [slick/slick#1859]
I found this potential bug when working on PR #1815.

The current code in master is:

```scala
def forName(name: String, maxConnections: Option[Int], executor: AsyncExecutor = null) = new InitialContext().lookup(name) match {
  case ds: DataSource => forDataSource(ds, maxConnections, executor match {
    case null => AsyncExecutor.default(name)
    case e => e
  })
  case x => throw new SlickException("Expected a DataSource for JNDI name "+name+", but got "+x)
}
```

In PR #1815, this was refactored to

```scala
def forName(name: String, maxConnections: Option[Int], executor: AsyncExecutor = null) =
  new InitialContext().lookup(name) match {

    case ds: DataSource =>
      val configuredExecutor =
        (executor, maxConnections) match {
          case (null, Some(maxConnec)) => AsyncExecutor.default(name, maxConnec)
          case (null, None) => AsyncExecutor.default(name)
          case (e, _) => e
        }
      forDataSource(ds, maxConnections, configuredExecutor)

    case x => throw new SlickException("Expected a DataSource for JNDI name "+name+", but got "+x)
  }
``` 

In both cases, there is the dangerous for calling `forName` twice for the same `DataSource` name. When that happens, we will have two instances of a Slick Database using the same `DataSource` but bounded to two different `AsyncExecutor`.

**Comment by hvesalai** [comment]
I think this is quite the edge case. I see two alternatives to a solution:
- just document this in the scaladoc of `forName`
- if there is a clean an simple way to prevent it (for example, by having some meta-data in the JNDI context), then do it that way... however remembering also race conditions.

**Comment by renatocaval** [comment]
You are right about it being an edge case and probably a clear note on the scaladoc is the best we can do. Trying to use the JNDI context for this will be messy and error-prone.
