### ISSUE TITLE
"SELECT .. FOR UPDATE NOWAIT" regression in 3.2.2

### ISSUE THREAD

**Issue by Daenyth** [slick/slick#1870]
**DESCRIPTION:**

I have some code to use postgres's SELECT FOR UPDATE code that works on 3.2.1, but when I upgrade our dependency to 3.2.2, the unit test covering it fails 100% of the time with a timeout error.

**STEPS TO REPRODUCE:**

```scala
sealed trait LockFailure
case object LockInUse extends LockFailure
case object NothingToLock extends LockFailure

sealed trait LockResult[T]
case class LockFailed[T](reason: LockFailure) extends LockResult[T]
case class LockAcquired[T](result: T) extends LockResult[T]

class FastLock[E, U](
    query: Query[E, U, Seq]
)(
    implicit db: Database,
    ec: ExecutionContext
) {

  def apply[R](effect: U => DBIO[R]): Future[LockResult[R]] =
    retryFailedLock(attemptLock(effect))

  private def attemptLock[R](effect: U => DBIO[R]): Future[LockResult[R]] =
    db.run(
      (for {
        element <- forUpdateNoWait
        result <- element match {
          case Some(row) => effect(row).map(LockAcquired[R](_))
          case _         => DBIO.successful(LockFailed[R](NothingToLock))
        }
      } yield {
        result
      }).transactionally
    )

  private def retryFailedLock[R](
      result: Future[LockResult[R]]): Future[LockResult[R]] =
    result.recover {
      case PgSqlState.LockNotAvailable() => LockFailed(LockInUse)
    }

  private def forUpdateNoWait: DBIO[Option[U]] =
    lockAction.flatMap(_ => query.result.headOption)

  private def lockAction: DBIO[Option[Int]] =
    sql"SELECT 1 FROM (#$baseSql) base FOR UPDATE NOWAIT".as[Int].headOption

  private val baseSql = query.result.statements.head
}

// Test
    it("locks the row without waiting") {
      val query = TableQuery[Foo]
      await(db.run(query forceInsert fooRow))

      val result = await(FastLock(query) { sync =>
        val inner = await(FastLock(query) { sync =>
          DBIO.successful(s"inner ${sync.id.get}")
        })

        DBIO.successful((s"outer ${sync.id.get}", inner))
      })

      assert(
        result === LockAcquired(
          (s"outer ${sync.id.get}", LockFailed(LockInUse))))
    }
```

**EXPECTED RESULT:**

The code that works in 3.2.1 works in 3.2.2

**ACTUAL RESULT:**

The `val result = await ..` line raises a Future timeout error after 2 seconds.

**SETUP:**

Postgres using the slick-pg profile.

**Comment by hvesalai** [comment]
Now this is what I call a well written bug description. The only thing I'm missing is the AsyncExecutor setup, i.e. how many threads and connections. Also a thread dump (kill -3 in unix) of the JVM just when the timeout occurs would be very revealing.

**Comment by Daenyth** [comment]
ExecutorService is the akka testkit ExecutorService. If you can point me to the relevant application.conf sections I can pull out whatever you need.

I'll try to get you that thread dump

**Comment by hvesalai** [comment]
I'm unable to help with anything Akka related.

**Comment by hvesalai** [comment]
The only reason I could see why you would get a deadlock in this case is if you run out of threads. I.e. all your threads are waiting for connections (which are waiting for the lock) and then you don't have any free threads to run the only action that could actually proceed.

Are there any errors in the logs when you run this. Slick will log a warning if you have a configuration that can result in a deadlock.

**Comment by Daenyth** [comment]
I'll try that, but I'd be surprised if it's akka related. I should be able to swap out the test base class with a pure one untouched by akka in any case.

The test passes on 3.2.1 and if I do nothing other than change build.sbt to 3.2.2 it fails, so I don't think it's akka related.

**Comment by hvesalai** [comment]
I'm not saying it is akka related, but I'm saying it might be configuration related. Previously the default was maxConnections == numThreads x 5, but now it's just maxConnections == numThreads.

**Comment by Daenyth** [comment]
I don't see maxConnections in our src/test/resources/application.conf, so that might be it!

**Comment by hvesalai** [comment]
What is the numThreads you have?

**Comment by Daenyth** [comment]
`numThreads = 1`

**Comment by hvesalai** [comment]
bingo!

**Comment by Daenyth** [comment]
So the fix would be to set `postgres.maxConnections = 5` to get equivalent behavior to the previous defaults?

**Comment by hvesalai** [comment]
yes

**Comment by Daenyth** [comment]
I'll test that as soon as I can

**Comment by Daenyth** [comment]
Setting `maxConnections = 5` makes the test now pass again! Thanks :)
