### ISSUE TITLE
The mapTo macro doesn't compile when target case class has a companion object

### ISSUE THREAD

**Issue by gaelrenoux** [slick/slick#1873]
The mapTo method is in slick.lifted.ShapedValue, the associated macro is ShapedValue.mapToImpl.

Using the mapTo macro fails to compile whenever you target a case class that have a companion object, even if that companion object is completely empty. It gives the following error:
```
Error:(20, 40) value tupled is not a member of object slicktemplate.App.Message
    def * = (sender, content, id).mapTo[Message]
```

Here is a test case: 
```
object App {
  import slick.jdbc.H2Profile.api._

  final case class Message(
    sender:  String,
    content: String,
    id:      Long = 0L)

  object Message {}

  final class MessageTable(tag: Tag)
      extends Table[Message](tag, "message") {

    def id      = column[Long]("id", O.PrimaryKey, O.AutoInc)
    def sender  = column[String]("sender")
    def content = column[String]("content")

    def * = (sender, content, id).mapTo[Message]
  }
}
```
Remove the 'object Message{}' line and it compiles.

I'm using Slick 3.2.2, Scala 2.12.4 and sbt 1.0.4. I have checked with H2Profile and PostgresProfile, I get the same error.

**Comment by hvesalai** [comment]
Would you happen to have a PR that fixes this?

**Comment by hvesalai** [comment]
This happens because your `object Message` does not extends `FunctionX`.

If you define it this way, then the code would compile

```
object Message extends ((String, String, Long) => Message) {
}
```

The reason is that Function3 has a `method tupled` available, where as your definition of Message does not have it. 

The macro could be changed to call `(Message.apply _).tupled` instead (since your Message will have the `apply` method).

**Comment by hvesalai** [comment]
Or so that nothing is broken, the macro could be changed to first see if the given thing defines the `tupled` method, and if not, then to check for `tupled` on `apply`

**Comment by gaelrenoux** [comment]
First, thanks for the workaround ! Unfortunately, macros are the one part of Scala I'm really not familiar with. It doesn't seem too hard, I'll try it later today if I can find the time.

I don't agree with your assessment that this is not a bug, though. The implicit companion object for a case class does seem to implement the Function1 trait, as the tupled method can be called on it, but the Scala specification doesn't mention it. I think it's an implementation quirk of the compiler, and we should probably not rely on it. Besides, I've pretty much never seen people implement Function1 when they write companion objects, so it will probably catch a lot of them unaware as well.

**Comment by Daenyth** [comment]
If you define your own `def apply = (MyClass.apply _).tupled` in the companion object it works

**Comment by ksilin** [comment]
@Daenyth shouldn't it rather be `tupled`?

`def tupled = (MyClass.apply _).tupled`

**Comment by Daenyth** [comment]
You're right

**Comment by jabrouwer82** [comment]
Hey @hvesalai, I'm not sure if y'all are still interested in a pr for this, but I created one that I think does the trick and I figured I would add a comment here for visibility.
