### ISSUE TITLE
Surprising behavior: (col === None) is translated to (col = null).

### ISSUE THREAD

**Issue by strelec** [slick/slick#1874]
Let col be a nullable column (for example, Option[Int]).

EXPECTED:
(col === None) being equivalent to col.isEmpty

ACTUAL:
(col === None) being equivalent to false.

SOLUTION:
a) document this behavior
b) change the condition generation.

**Comment by hvesalai** [comment]
Yeah, I think b would be ideal, if doable.

**Comment by hvesalai** [comment]
And Pull Requests are always welcomed.

**Comment by strelec** [comment]
The problem is, if we do this, we break backward compatibility.

**Comment by hvesalai** [comment]
@strelec I don't fully understand your latest comment.

Are we talking about `Rep[Option[_]] === ConstColumn[None]`?

**Comment by strelec** [comment]
We are talking about comparing `Rep[Option[T]] === Rep[Option[T]]`. You do not get results where both results are null.

**Comment by hvesalai** [comment]
Ah, but that is as it should be. In SQL `NULL = NULL` equals false.

**Comment by hvesalai** [comment]
I.e. it behaves like NaN

```
scala> Double.NaN == Double.NaN
res5: Boolean = false
```

**Comment by strelec** [comment]
But it should not be. This is scala, people expect it to behave like comparing two Options.

**Comment by djx314** [comment]
@strelec I don't think this is nessary. Because in sql, `tablea.name = null` is autal exists. So we don't know when and where we would use it. I think it need to be exists in slick's api.
If you'd like to compare with isNull, you can write
```scala
for {
  a <- tqA if (if paramOpt.isEmpty) a.name.isNull else (a.name === paramOpt.get))
} yield {
  ...
}
```
or write a implicit class yourself if you are instested.

**Comment by nafg** [comment]
This behavior is documented.

**Comment by hvesalai** [comment]
Ok, I'm closing this. Documentation is a never ending project, but if we have this in there in some format, then rather than keeping this issue open, we would welcome a PR that makes the doc better.
