### ISSUE TITLE
case class generation independent of column count

### ISSUE THREAD

**Issue by mb73** [slick/slick#1885]
slick-codegen generates case class for tables having up to 22 columns and only types otherwise. A more uniform behavior would be helpful. 

~~A quick solution may be to~~
~~1. rename type FooRow to type FooRowHList~~
~~2. change GetResultFooRow result type to GR[FooRowHList]~~
~~3. replace def FooRow by case class FooRow (just drop the result type and def body)~~
~~4. inside class Foo surround the body of def * with brackets and then call .mapTo[FooRow]~~

**Comment by hvesalai** [comment]
Nice ideas. We are welcoming PRs for clean solutions.

**Comment by hvesalai** [comment]
See PR #1889, also #1462

**Comment by hvesalai** [comment]
@mb73 can you review #1462 and give here your comments about what cvogt says there about case classes see "cvogt commented on Mar 16, 2016 "

**Comment by mb73** [comment]
@hvesalai Until now I basically implemented those changes without IDE support, because I am not able to properly open/import the slick project with IntelliJ IDEA 2018.1.1 (Community Edition) and Scala plugin 2018.1.8. (Errors all over the place.) Is there some guide regarding IDE support?

**Comment by mb73** [comment]
On second thought, GetResultFooRow could always return an instance of the case class. We just need to generate a call to the constructor. I think there is no need to generate a tuple in any case. Therefore there is also no need to generate such a `HList` based type anymore ...

**Comment by hvesalai** [comment]
Closed by #1889
