### ISSUE TITLE
Invalid SQL is generated for null UUID values in PostgresProfile

### ISSUE THREAD

**Issue by nebehr** [slick/slick#1901]
Invalid SQL is generated for null UUID values (perhaps some other types as well) by ```PostgresProfile```. I encounter this issue while using slick-pg but it does not look as though it is on their side. Basically, the code like this:
```
val query = table.map { t =>
  val w = Over.partitionBy(t.name).sortBy(r.timestamp)
  (t.id, lag(t.id.?) :: w)
}
db.run(query.result)
```
where id is declared as ```def id = column[UUID]("id", O.PrimaryKey, O.SqlType("UUID"))```, generates the following or similar SQL:
```select id, lag(id,1,'null') over ( partition by name order by timestamp) from my_table limit 100 offset 0```
which produces "ERROR: invalid input syntax for uuid: "null"".

The problem is at https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/PostgresProfile.scala#L451 where value is enclosed in quotes even if it is null. Corresponding line in slick-pg is https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/window/PgWindowFuncSupport.scala#L35, and it seems to correctly pass null as a default value for lag function.

The workaround is to override ```UUIDJdbcType``` like this:
```
class UUIDJdbcType extends super.UUIDJdbcType {
  override def valueToSQLLiteral(value: UUID) = if (value == null) null else "'" + value + "'"
}
```

**Comment by hvesalai** [comment]
Thank you @nebehr for the good report. @smootoo has an outstanding PR on UUID fixes, maybe this could be fixed with that. What do you think @smootoo ?

**Comment by smootoo** [comment]
I don't think this a bug in the main slick code. The `valueToSQLLiteral` method takes a value of type `UUID`, not an `Option[UUID]`. And this is Scala code, so we really shouldn't be checking for `null`. The slick code handles null literals correctly when it encounters an `Option` type with a `None`.

For example, defining a `coalesce` function which can legitimately take `NULL` literals.
```
val coalesce = SimpleFunction.binary[Option[UUID], Option[UUID], Option[UUID]]("coalesce")
val nullUUID: Option[UUID] = None
table.map(x => coalesce(x.optData, nullUUID)).result
```
The postgres SQL generated is correct
`select coalesce("optData",null)`

If we try something similar with `null.asInstanceOf`

```
val nullUUID: UUID = null.asInstanceOf[UUID]
val coalesce = SimpleFunction.binary[UUID, UUID, UUID]("coalesce")
table.map(x => coalesce(x.data, nullUUID)).result
```
Then we get invalid SQL
`select coalesce("data",'null')`

Maybe @tminglei can say why those [Window functions](https://github.com/tminglei/slick-pg/blob/master/core/src/main/scala/com/github/tminglei/slickpg/window/PgWindowFuncSupport.scala#L35) were implemented with `null.asInstanceOf`

**Comment by nebehr** [comment]
@smootoo you may be correct here in suggesting that PG-specific functions might be implemented in a slightly different fashion to prevent such issues. At the same time I will point out that: a) this is not the first occasion even in my limited experience when slick does not handle non-standard types correctly (I have already run into https://github.com/slick/slick/issues/1446 in the past), and b) current implementation of window functions does work for plain types such as strings which is probably why the bug is still there. By the way you may see null checks elsewhere, e.g. at https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/OracleProfile.scala#L361. To me, this whole type processing issue demonstrates some design flaw which may yet manifest itself in more ways than one.

**Comment by hvesalai** [comment]
I think the flaw is the use of `null` in the first place, not the design of slick types. #1446 was a mapping issue, not a design issue.

Having said that, I think the bug should be filed in slick-pg. @nebehr can you do that and reference this issue so that @tminglei can chime in if he thinks the fix should be attempted on slick side.

**Comment by tminglei** [comment]
Fixed in `slick-pg` side. For details pls ref tminglei/slick-pg#404.
