### ISSUE TITLE
How to generate code for some specific tables in a database ?

### ISSUE THREAD

**Issue by zhangshengshan** [slick/slick#1912]
As title. If there are a lot tables in a database ,  how to generate code for only a few tables in a database? 
```
package com.example

import com.typesafe.config.ConfigFactory

object SlickCodeGer extends App {
  val config = ConfigFactory.load()
  val mysqlConfig = config.getConfig("mysql")
  val targetMysqlConfig = mysqlConfig.getConfig("retail.realtime.daily")
  println(s"targetMysqlConfig = ${targetMysqlConfig}")
  val uri = "slick.db.mysql"
  val profile = "slick.jdbc.MySQLProfile"
  val jdbcDriver = "com.mysql.jdbc.Driver"
  val url = targetMysqlConfig.getString("url")
  val outputFolder = "src/main/scala/com/youzan/model"
  val pkg = targetMysqlConfig.getString("pkg")
  val user = targetMysqlConfig.getString("user")
  val password = targetMysqlConfig.getString("password")
  slick.codegen.SourceCodeGenerator.main(
    Array(profile, jdbcDriver, url, outputFolder, pkg, user, password))
}
```
The code above may make a Tables.scala file too long. Is there any config to get the code for only the wanted table ?

**Comment by Asamsig** [comment]
This is probably a better question for gitter or the community page. This is an issue tracker.

Check out this plugin which streamlines codegen more. https://github.com/tototoshi/sbt-slick-codegen/blob/master/README.md#configuration

**Comment by zhangshengshan** [comment]
@Asamsig   if use this sbt plugin , does it means very time i run `sbt compile`, slick generate the code again ?

**Comment by hvesalai** [comment]
@zhangshengshan please use community forums for your questions. This is an issue tracker for bugs and such.
