### ISSUE TITLE
countDefined operator: Cannot prove that Boolean <:< Option[_].

### ISSUE THREAD

**Issue by ravinderpayal** [slick/slick#1913]
I read about countDefined operator which lacks the documentation, and tried to use it for counting the number of fields having value true.

**STEPS TO REPRODUCE:**

val q = (for {
      c <- WebImage.webimage
    } yield (c.pageUrl, c.lastAccess, c.isAnnotated)).groupBy(a => (a._1, a._3)).map{
      case(a,b) => (a._1, b.map(_._2).max, b.map(_._3).countDefined, b.length)
    }
    db.run(q.result)
**EXPECTED RESULT:**

(String,Option[Long]. Int, Int)
**ACTUAL RESULT:**
Compilation error:
Cannot prove that Boolean <:< Option[_].

In /home/ravinder/IdeaProjects/structurer/app/scrapper/Datastore.scala:60
56  def get = {
57    val q = (for {
58      c <- WebImage.webimage
59    } yield (c.pageUrl, c.lastAccess, c.isAnnotated)).groupBy(a => (a._1, a._3)).map{
60      case(a,b) => (a._1, b.map(_._2).max, b.map(_._3).countDefined, b.length) 
61    }
62    db.run(q.result)
63  }
64

**Comment by hvesalai** [comment]
As the instructions CLEARLY stated, this is not a help forum. Please find other channels to get help and stop abusing the bug tracker.
