### ISSUE TITLE
Links to Slick TestKit examples are broken

### ISSUE THREAD

**Issue by hungaikev** [slick/slick#1917]
Hi I just wanted to report that the links to examples are broken 
  http://slick.lightbend.com/doc/3.2.3/testkit.html

**Comment by hvesalai** [comment]
Hmm... I don't know much about the activator templates, but if somebody is willing to make a PR that fixes the current master in this regard, I would be happy to merge it.

**Comment by hungaikev** [comment]
@hvesalai I think this PR fixes the issue https://github.com/slick/slick/pull/1711
