### ISSUE TITLE
Intermittent test failures on travis running the JdbcTypeTest.testZonedDateTime[oracle]

### ISSUE THREAD

**Issue by smootoo** [slick/slick#1923]
Examples here
https://travis-ci.org/slick/slick/builds/385265902?utm_source=github_status&utm_medium=notification
https://travis-ci.org/slick/slick/builds/390067961?utm_source=github_status&utm_medium=notification

`[error] Test com.typesafe.slick.testkit.tests.JdbcTypeTest.testZonedDateTime[oracle] failed: java.util.NoSuchElementException: Invoker.first, took 0.105 sec
[error]     at slick.jdbc.Invoker$class.first(Invoker.scala:33)
[error]     at slick.jdbc.StatementInvoker.first(StatementInvoker.scala:15)
[error]     at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:52)
[error]     at slick.jdbc.StreamingInvokerAction$HeadAction.run(StreamingInvokerAction.scala:51)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anon$2.liftedTree1$1(BasicBackend.scala:275)
[error]     at slick.basic.BasicBackend$DatabaseDef$$anon$2.run(BasicBackend.scala:275)
[error]     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]     at java.lang.Thread.run(Thread.java:748)
`

**Comment by smootoo** [comment]
It looks like there is at least one more.
I'll refactor the test so that we see these much more quickly and don't have intermittent failures.
https://travis-ci.org/slick/slick/builds/391607629

**Comment by hvesalai** [comment]
@smootoo any progress?

**Comment by smootoo** [comment]
Sorry. No progress. I'll take another look at it this week.

**Comment by renatocaval** [comment]
Resolved by #1960
