### ISSUE TITLE
Default AsyncExecutor Leads to Deadlock Warning

### ISSUE THREAD

**Issue by mattusifer** [slick/slick#1938]
**DESCRIPTION:**

[AsyncExecutor.default()](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/AsyncExecutor.scala#L197) creates an AsyncExecutor with maxConnections=Integer.MAX_VALUE and maxThreads=20. Since maxConnections > maxThreads, we get [this warning](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/util/AsyncExecutor.scala#L64). According to the warning, the *default* configuration could lead to deadlocks.

**STEPS TO REPRODUCE:**

Create an AsyncExecutor using AsyncExecutor.default()

**EXPECTED RESULT:**

The default AsyncExecutor should not lead to warnings.

**ACTUAL RESULT:**

Configuration warnings appear when using the default AsyncExecutor.

**SETUP:**

Any setup when using the default AsyncExecutor.

**Comment by mattusifer** [comment]
@hvesalai I would prefer to just change the behavior of default, but I'm not well versed on all of the implications of such a change. 

Let's say we make `maxConnections` equal to `numThreads` in the default configuration. What are the practical implications of changing `maxConnections` for people that are already using the default configuration? Would they incur a drop in performance upon upgrading to 3.4.0 if they are usually using lots of concurrent connections, or worse, would they encounter runtime errors if a connection is attempted and the number of connections is already equal to `maxConnections`? Are there any other implications of this change?

If changing the default configuration like this could potentially be disruptive to existing users when they upgrade to 3.4.0, I'm fine with creating a new deadlock-free configuration and deprecating the default.

**Comment by hvesalai** [comment]
What is the default `queueSize`?

**Comment by mattusifer** [comment]
The default `queueSize` is 1000

**Comment by hvesalai** [comment]
@mattusifer care to review #2025 and see what you think about it?

**Comment by mattusifer** [comment]
Looks good to me!
