### ISSUE TITLE
Allow lifted values to be passed to "in" clauses

### ISSUE THREAD

**Issue by ashleymercer** [slick/slick#1997]
**DESCRIPTION:**

Slick can currently produce two types of `in` clause in a SQL statement:

- filtering against a subquery, which is available through [ColumnExtensionMethods.in](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/lifted/ExtensionMethods.scala#L44)
- filtering against a known (fixed) set of values, which is available through [ColumnExtensionMethods.inSet](https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/lifted/ExtensionMethods.scala#L46)

However, there is a third possibility which is supported by at least some DBMSes: `in` clauses that refer directly to columns / tables already defined earlier in the query. These take the form:

```sql
select p.*
from people p, children c
where p.id in (c.parent_id_1, c.parent_id_2)
```

(See [this StackOverflow question](https://stackoverflow.com/questions/54961139/scala-slick-filter-using-in-on-multiple-columns) for the full table structure and explanation).

As fas as I can see, it's not currently possible to produce SQL of the third form using slick. They can be mimicked by using a sequence of `or`s but for reasons explained in the SO question, and for example [this bug report in H2](https://github.com/h2database/h2database/issues/320), using `or` often leads to sub-optimal query plans.

I'd like to propose (and am happy to submit a PR for) adding the third form to `ColumnExtensionMethods`.

**Comment by ashleymercer** [comment]
Okay, I have a PR ready for this:

- which branch should I commit to? 
- I have a few comments / questions on implementation details, but suspect the PR is a better place to discuss than here?

**Comment by hvesalai** [comment]
Oh, sounds cool! Master is the branch for everything. We will backport to other branches if there is no breaking changes to APIs

**Comment by ashleymercer** [comment]
PR submitted although the build is failing with some docker error? Suspect it might be related to #1993?

**Comment by ashleymercer** [comment]
@hvesalai bump - is somebody looking at the build infrastructure?

**Comment by hvesalai** [comment]
@ashleymercer the infra was fixed long since, the build is now failing because of MIMA issues (binary incompatibilities). You need to add an exception to the MIMA rules
