### ISSUE TITLE
Avoid "case ... then ... else" when sorting after a left join

### ISSUE THREAD

**Issue by Reddone** [slick/slick#2000]
**DESCRIPTION:**

When using sortBy after a leftJoin and when sorting using the right part of the join a "case when .... then ... else null" is generated. Since we can handle null values in sorting using
nullsLast and nullsFirst, there is no sense in putting a case statement in the generated sql.

**STEPS TO REPRODUCE:**

case class Person(id: Long, name: String)
case class PersonMetric(id: Long, personId: Long, name: String, value: Double)

Basically, a person has various metrics. Now suppose that we want to order people using the value of a specific metric. For example, I want to order people using their weight. Not all people have the weight metric.

```scala
val orderingSupportQ = PersonMetricTable.filter(_.name === "weight")

val orderedByWeightQ = PersonTable
   .leftJoin(orderingSupport)
   .on(_.id === _.personId)
   .sortBy(_._2.map(_.value).desc.nullsFirst)
```
**EXPECTED RESULT:**

The query should end with "order by x43.x39 desc nulls first"

**ACTUAL RESULT:**

The query ends with "order by (case when (x43.x37 is not null) then x43.x39 else null end) desc".

**SETUP:**

Slick 3.3.0 with PostgresSQL 9.4

**Comment by spcoleman** [comment]
Hi, was this issue every fixed? I've upgrade to Slick 3.3.3 with PostgresSQL 12 and I'm still seeing this in the SQL generated by Slick.
order by ((case when (x50."instrument_id" is null) then null else 1 end), x50."market_cap") desc nulls last
and 
order by (x2.x50, x2.x52) desc nulls last   (where x50 is the same case statement above but in one of the sub selects)

**Comment by nafg** [comment]
I'm guessing @Reddone closed it because he no longer needs it -- I don't see any evidence that it was fixed. A PR would be welcome.

**Comment by spcoleman** [comment]
Thanks @nafg for your prompt reply. I've tried everything I can think of using Slick to work around this issue, but without any joy. I may need to fix this in code, which is inefficient and expensive. 
This works:
order by (case when (x50."instrument_id" is null) then null else 1 end), x50."market_cap" desc nulls last
or this:
order by x50."market_cap" desc nulls last
But the two together like this does not. I would have expected Postgres would apply the nulls last to both, but it doesn't work that way.

**Comment by Reddone** [comment]
Wow, same problem still happens after 3 years! Honestly, I gave up on using a particular language to use SQL.

At the moment I don't work with Scala and Slick anymore. Anyway, I switched to writing plain SQL in general. Slick was really good to work with, but the power and the predictivity you get from using plain SQL made the difference in complex projects. The are many libraries which let you write reusable fragments, so I don't see the point in "having to test my SQL" because sometimes edge cases like this one in the issue can produce strange queries.

**Comment by nafg** [comment]
One technique I sometimes use is to store a subquery as a view in the database, then model it in Slick as I would a table.

The advantage of this over SQL strings in code is a stronger guarantee that it won't become stale. For instance, if a migration changes the database scheme either it will update the view or it will fail and force me to update the view in the migration as well.

**Comment by Reddone** [comment]
I agree that it works, but a non-regression test would cover the case of having stale sql strings in the code, and I have to write non-regression tests in any case, so it's not extra work; writing an additional view does not always comes for free, for example you also have to create grants and update the view as the table changes.

Type-checked code at compile time will never substitute tests IMHO, that's why I think plain sql is not bad. And if you don't like strings you can always use a DSL, even if it won't be checked at compile time (that really depends on the programming language)

**Comment by spcoleman** [comment]
Morning, thanks for everyone's comments. For the most part, Slick is doing a good job for the application I'm working on. Most queries are simple and the SQL generated is efficient enough. Yesterday, I started looking at using dynamic SQL to solve my sort problem for now for the one query that has the problem. Perhaps someone has some ideas on how I can create a dynamic where clause using the sql interpolator and bind variables. I can splice the order by, limit and offset, no risk of SQL injection there but variables for the where conditions are from user input. 

So the SQL statement is simple enough.

select i.id
  from instruments as i
       inner join markets as m
	           on m.id = i.market_id
	   left outer join ratios as r
	           on r.instrument_id = i.id 
	   left outer join organisations as o
	           on o.id = i.issuer_org_id
	   left outer join industries as ind
	           on ind.code = i.industry_code
	   left outer join sectors as s
	           on s.code = ind.sector_code
 where i.in_use = ?
 -- Add dynamic where conditions
 order by r.market_cap desc nulls last
 limit 50 
 offset 0;
 
 The where conditions variables are a mixture of strings, numbers, booleans, and some lists.
 
 case class SearchInstrumentsInput(
    query: Option[String] = None,
    queryFields: Option[Seq[QuerySearchField]] = None,
    limit: Option[Int] = None,
    offset: Option[Int] = None,
    realTime: Option[Boolean] = Some(false),
    instrumentTypes: Option[Seq[InstrumentType]] = None,
    countryCodes: Option[Seq[String]] = None,
    industryCodes: Option[Seq[String]] = None,
    orgIds: Option[Seq[OrgId]] = None,
    peRatio: Option[BigDecimalFilterInput] = None,
    pbRatio: Option[BigDecimalFilterInput] = None,
    marketCap: Option[BigDecimalFilterInput] = None,
    `yield`: Option[BigDecimalFilterInput] = None,
    currentRatio: Option[BigDecimalFilterInput] = None,
    debtToEquity: Option[BigDecimalFilterInput] = None,
    returnOnAssetsTtm: Option[BigDecimalFilterInput] = None,
    returnOnInvestmentTtm: Option[BigDecimalFilterInput] = None,
    returnOnEquityTtm: Option[BigDecimalFilterInput] = None,
    epsTrend1: Option[BigDecimalFilterInput] = None,
    epsTrend5: Option[BigDecimalFilterInput] = None,
    epsTrend10: Option[BigDecimalFilterInput] = None,
    debtRatio: Option[BigDecimalFilterInput] = None,
    returnOnCapitalEmployed: Option[BigDecimalFilterInput] = None,
    dividendCover: Option[BigDecimalFilterInput] = None,
    netProfitMargin: Option[BigDecimalFilterInput] = None,
    grossProfitMargin: Option[BigDecimalFilterInput] = None,
    orderBy: Option[List[SortFieldDirection]] = None,
    symbolSuffix: Option[String] = None,
    symbol: Option[String] = None,
    includeInactive: Option[Boolean] = Some(false)
)

This is how I currently do it and it works well. I don't really like all the sub selects slick generates, but hey it works. I dynamiclly add the sortby later based on the orderBy input.

    val bq = instruments
      .filterIf(!i.includeInactive.getOrElse(false))(_.inUse === true)
      .filterIf(i.query.isDefined)(byQuery(i, _))
      .filterIf(nonEmpty(i.instrumentTypes))(byInstrumentTypes(i, _))
      .filterIf(nonEmpty(i.industryCodes))(byIndustryCodes(i, _))
      .filterIf(i.symbol.isDefined)(bySymbol(i, _))
      .filterOpt(i.orgIds) {
        case (is, orgIds) => is.issuerOrgId inSet orgIds
      }
      .join(markets)
      .on(_.marketId === _.id)
      .filterIf(nonEmpty(i.countryCodes))(byCountryCodes(i, _))
      .filterIf(i.symbolSuffix.isDefined)(bySymbolSuffix(i, _))
      .map(_._1)
      .joinLeft(quotes)
      .on((in, q) => in.id === q.instrumentId && q.realTime === realTime)
      .filterIf(i.peRatio.flatMap(_.gte).isDefined && !useDtMarketData)(
        byGtePeRatio(i, _))
      .filterIf(i.peRatio.flatMap(_.lte).isDefined && !useDtMarketData)(
        byLtePeRatio(i, _))
      .filterIf(i.`yield`.flatMap(_.gte).isDefined && !useDtMarketData)(
        byGteYield(i, _))
      .filterIf(i.`yield`.flatMap(_.lte).isDefined && !useDtMarketData)(
        byLteYield(i, _))
      .map(_._1)
      .joinLeft(ratios)
      .on(_.id === _.instrumentId)
      .filterIf(i.pbRatio.flatMap(_.gte).isDefined)(byGtePbRatio(i, _))
      .filterIf(i.pbRatio.flatMap(_.lte).isDefined)(byLtePbRatio(i, _))
      .filterIf(i.marketCap.flatMap(_.gte).isDefined)(byGteMarketCap(i, _))
      .filterIf(i.marketCap.flatMap(_.lte).isDefined)(byLteMarketCap(i, _))
      .filterIf(i.peRatio.flatMap(_.gte).isDefined && useDtMarketData)(
        byGtePeRatioRatios(i, _))
      .filterIf(i.peRatio.flatMap(_.lte).isDefined && useDtMarketData)(
        byLtePeRatioRatios(i, _))
      .filterIf(i.`yield`.flatMap(_.gte).isDefined && useDtMarketData)(
        byGteYieldRatios(i, _))
      .filterIf(i.`yield`.flatMap(_.lte).isDefined && useDtMarketData)(
        byLteYieldRatios(i, _))
      .filterIf(i.debtToEquity.flatMap(_.gte).isDefined)(
        byGteDebtToEquity(i, _)
      )
      .filterIf(i.debtToEquity.flatMap(_.lte).isDefined)(
        byLteDebtToEquity(i, _)
      )
      .filterIf(i.returnOnAssetsTtm.flatMap(_.gte).isDefined)(
        byGteReturnOnAssets(i, _)
      )
      .filterIf(i.returnOnAssetsTtm.flatMap(_.lte).isDefined)(
        byLteReturnOnAssets(i, _)
      )
      .filterIf(i.returnOnInvestmentTtm.flatMap(_.gte).isDefined)(
        byGteReturnOnInvestment(i, _)
      )
      .filterIf(i.returnOnInvestmentTtm.flatMap(_.lte).isDefined)(
        byLteReturnOnInvestment(i, _)
      )
      .filterIf(i.returnOnEquityTtm.flatMap(_.gte).isDefined)(
        byGteReturnOnEquity(i, _)
      )
      .filterIf(i.returnOnEquityTtm.flatMap(_.lte).isDefined)(
        byLteReturnOnEquity(i, _)
      )
      .filterIf(i.currentRatio.flatMap(_.gte).isDefined)(
        byGteCurrentRatio(i, _)
      )
      .filterIf(i.currentRatio.flatMap(_.lte).isDefined)(
        byLteCurrentRatio(i, _)
      )
      .filterIf(i.epsTrend1.flatMap(_.gte).isDefined)(
        byGteEpsTrend1(i, _)
      )
      .filterIf(i.epsTrend1.flatMap(_.lte).isDefined)(
        byLteEpsTrend1(i, _)
      )
      .filterIf(i.epsTrend5.flatMap(_.gte).isDefined)(
        byGteEpsTrend5(i, _)
      )
      .filterIf(i.epsTrend5.flatMap(_.lte).isDefined)(
        byLteEpsTrend5(i, _)
      )
      .map(_._1)

Any thoughts or practical experience advice on doing this would be appreciated. I haven't found any useful examples of how best to do this.

**Comment by Reddone** [comment]
I had a similar problem when I was implementing a GraphQL backend, i.e. tons of objects with a lot of fields to filter, where filters also applied to other objects having a relation with the first one.

I solved it using Shapeless and case classes: basically sql where conditions are represented with a case class, and then shapeless does all the job in creating the sql query. You can find it in my github if you are curious. I don't want to encourage you in using it because I don't work on it anymore (and also because it has nothing to do with slick and with the initial issue), but maybe you can get the basic idea and apply it to your project, maybe with Slick.
