### ISSUE TITLE
repeat log in JdbcBackend.scala

### ISSUE THREAD

**Issue by wtog** [slick/slick#2003]
**DESCRIPTION**:

these codes logged twice, JdbcBackend.logStatement("Preparing statement", sql) should be deleted?
* JdbcBackend.logStatement("Preparing statement", sql)
* loggingPreparedStatement(decorateStatement(resultSetHoldability.withDefault(defaultHoldability)

![image](https://user-images.githubusercontent.com/39434237/54824942-4d53ba80-4ce7-11e9-8091-e3ffed5f3592.png)

**Comment by hvesalai** [comment]
A tested PR is welcome to fix the issue.

**Comment by wtog** [comment]
repeat log is my mistake in my config in log4j2.xml
the config below, will not log repatedly due to `additivity="false"`

```
<Root level="INFO" additivity="false">
        <appender-ref ref="STDOUT"/>
</Root>
<Logger name="slick.jdbc.JdbcBackend.statement" level="debug" additivity="false">
        <appender-ref ref="STDOUT"/>
</Logger>
```
