### ISSUE TITLE
Enable JDK11 in our Appveyor build

### ISSUE THREAD

**Issue by WellingR** [slick/slick#2022]
As part of #2020, support was added for building on JDK11 using travis. However, we also use Appveyor to test slick using various versions of Microsoft SQL Server (currently 'SQL2008R2SP2', 'SQL2012SP1', 'SQL2014', 'SQL2017'). This functionality seems to have been added as part of #1443.

The question is should we test on Appveyor using a single JDK version only (if so, which?), or should we test using all supported JDKs?

**Comment by WellingR** [comment]
Side-note the same question could be asked about the scala versions. It seems that sbt is not called with an explicit scala version, which (currently) means that scala 2.11.12 will be used, perhaps we want to use the latest version instead, or multiple scala versions.

**Comment by WellingR** [comment]
@smootoo As you have worked on #1443, could you let me know what you think?

**Comment by smootoo** [comment]
@WellingR when the original Appveyor build was put in place, it couldn't handle testing all the scala versions without timing out. Given the travis build is testing multiple jdk and scala versions, I think the Appveyor build can stick to just testing the latest supported scala and jdk and so as not to hit the build timeout.
So, I think testing Jdk11 and scala 2.12 is the best pragmatic choice.

**Comment by WellingR** [comment]
Sounds good, if I have the time I will see if I can make a PR for this
