### ISSUE TITLE
Slick 3.2.3 and 3.3.0: UUIDJdbcType.sqlType for OracleDriver should be defined as java.sql.Types.BINARY

### ISSUE THREAD

**Issue by brendony** [slick/slick#2033]
This is a continuation of #1446. I can see in the source code for 3.2.3 and 3.3.0 that the UUID sqlType is still not being set correctly for the OracleProfile, leading to the same exception as the previous bug report.
> Inserting a NULL value into a column defined as Column[Option[UUID]] (a nullable RAW(32) column), results in this exception: `java.sql.SQLException: Invalid column type: 1111.
1111 = java.sql.Types.OTHER.`

I looked in the pull request for the related bug #1449, and that pull request did not fix the sqlType for Oracle's UUID, although it DID fix the sqlType for some of the other drivers.

Interestingly, when I create the CustomOracleProfile as suggested in the previous bug, I still get the above exception.

In the short term, I will find a workaround for this problem!

**Comment by hvesalai** [comment]
Hi @brendony, you should focus your debugging efforts on understanding why `java.sql.Types.OTHER` was even though the OracleDriver specifies `java.sql.Types.VARBINARY` for the UUID type

see https://github.com/slick/slick/blob/master/slick/src/main/scala/slick/jdbc/OracleProfile.scala

You could also paste the full stack trace here.

**Comment by brendony** [comment]
Thanks for your quick reply!     Yes, I see that the code is correct in 3.3.0.   So my heading is incorrect.
In my project, I am using slick_2.12:3.2.3 and the OracleProfile has this code:
```
    class UUIDJdbcType extends super.UUIDJdbcType {
      override def sqlTypeName(sym: Option[FieldSymbol]) = "RAW(32)"
      override def valueToSQLLiteral(value: UUID) = {
        val hex = value.toString.replace("-", "").toUpperCase
        s"hextoraw('$hex')"
      }
      override def hasLiteralForm = true
    }
```
(so it is missing the `sqlType` declaration).

When I tried to change my sbt file to use version 3.3.0 I must have not rebuilt my project correctly.
