### ISSUE TITLE
> This is not a help channel. Please use the other community channels for that. You can try, for example, gitter.im or stackoverflow.

### ISSUE THREAD

**Issue by Ashaniroshan** [slick/slick#2039]
> This is not a help channel. Please use the other community channels for that. You can try, for example, gitter.im or stackoverflow.

@hvesalai -
i think this is slick issue .

_Originally posted by @Ashaniroshan in https://github.com/slick/slick/issues/2038#issuecomment-493856398_

**Comment by hvesalai** [comment]
@Ashaniroshan if you don't stop abusing our issue tracker, I shall report you.

If I deem the issue you reported is indeed a bug, I shall re-open it. You don't have to do new issues.
