### ISSUE TITLE
insertOrUpdate succeeds when no rows are inserted

### ISSUE THREAD

**Issue by simao** [slick/slick#2045]
**DESCRIPTION:**

Using slick with mysql.

`insertOrUpdate` succeeds when rows are not inserted due to foreign key constraints.

**STEPS TO REPRODUCE:**

Create two tables, for example Books and BooksMeta. Build a foreign key from BooksMeta to Books.

Try to insert a row with `insertOrUpdate`. 

There is a failing test here: https://github.com/advancedtelematic/libats/blob/bef7cd77f5d4c5f0cfcc994711d29b5a84ec383a/libats-slick/src/test/scala/com/advancedtelematic/libats/slick/db/SlickExtensionsSpec.scala#L109 It works with slick 3.2.x but not slick 3.3.x

**EXPECTED RESULT:**

`insertOrUpdate` fails with some `Throwable` as the row cannot be inserted. This was the behavior in 3.2.x.

At the very least, `insertOrUpdate` should return a `Future` with value `0`.

I tracked this to this PR: https://github.com/slick/slick/pull/1879 When `insert ignore` is used instead of `insert`, no errors will be thrown.

**ACTUAL RESULT:**
`insertOrUpdate` returns a successful `Future[Int]` with value `1`.

**SETUP:**

Slick 3.3.x + Mysql.

**Comment by disordered** [comment]
This also affects other errors that are now ignored, for example, data truncation, when inserting too long value.

**Comment by jotarada** [comment]
I think this relates to #2076

**Comment by SethTisue** [comment]
someone could pick up this abandoned PR: #2101

**Comment by simao** [comment]
I think we can close this. It has been fixed by #2201 At least my test now passes.
