### ISSUE TITLE
Slick-codegen generates code that contains a warning on scala 2.13 (early initializers are deprecated) 

### ISSUE THREAD

**Issue by MariosPapasofokli** [slick/slick#2054]
**DESCRIPTION:**
Slick Codegen generates code that contains a warning when compiled with scala 2.13 as below:

```
object Tables extends {
  val profile = slick.driver.H2Driver
} with Tables
```
early initializers are deprecated; they will be replaced by trait parameters in 2.14, see the migration guide on avoiding var/val in traits.
[warn] object Tables extends {
[warn]   ----------------------^

**STEPS TO REPRODUCE:**
Generate code with slick codegen and then compile with scala 2.13

**EXPECTED RESULT:**
Generated code which compiles without warnings

**ACTUAL RESULT:**
Generated code which compiles with warnings

**SETUP:**
Scala: 2.13
Slick: 3.3.2
Db: Any

**Comment by MeerKatDev** [comment]
I replaced that code with

`
import slick.jdbc.{ MySQLProfile => profile }
object Tables extends Tables
`

which compiles just fine. what would  be the issue with this?

**Comment by MariosPapasofokli** [comment]
I would expect that slick codegen would generate non deprecated code for scala 2.13 instead of manually changing it every time I run codegen

**Comment by MeerKatDev** [comment]
> I would expect that slick codegen would generate non deprecated code for scala 2.13 instead of manually changing it every time I run codegen

Me too, just suggesting a way for now. Probably with the next bug fix. :)

**Comment by psyanite** [comment]
+ 1

**Comment by Folux** [comment]
+1

**Comment by travs15** [comment]
Worked for me avoiding this warning using this, I'm currently usign the scala version 2.13.8

```
import scala.annotation.nowarn

@nowarn
object Tables extends {
  val profile = slick.jdbc.MySQLProfile
} with Tables
```
