### ISSUE TITLE
Proposal: migrate site to scala-slick.org

### ISSUE THREAD

**Issue by TimMoore** [slick/slick#2082]
Lightbend has purchased the domain name scala-slick.org. We'd like to migrate the Slick site from slick.lightbend.com to scala-slick.org to improve search engine optimization. I'm opening this issue to invite comments from the community before we move ahead.

As far as I know, once the DNS is set up on our side, the only changes required would be to update the `CNAME` and `baseurl` configurations in the GitHub Pages site.

https://github.com/slick/slick.github.com/blob/master/CNAME
https://github.com/slick/slick.github.com/blob/master/_config.yml#L3

**Comment by hvesalai** [comment]
No objections from me.

**Comment by Asamsig** [comment]
Sounds good! 🎉

**Comment by d6y** [comment]
Could there be some way to redirect slick.lightbend.com pages to the new home for pages? Rather than not resolving them or 404ing existing URLs in the wild.

**Comment by TimMoore** [comment]
@d6y absolutely. Sorry, I meant to say that in my original post but forgot! We'll be sure to set up a redirect so that links aren't broken.

**Comment by d6y** [comment]
Great! Thanks @TimMoore 👍

**Comment by TimMoore** [comment]
We're planning to switch this over around Thursday, 14 November 2019, 10:00:00 UTC (tomorrow)

**Comment by TimMoore** [comment]
This is complete now. If you see a GitHub Pages 404 when you load slick.lightbend.com, rather than being redirected to scala-slick.org, you may need to refresh your DNS cache.
