### ISSUE TITLE
How to use plain sql? The documented examples don’t work 

### ISSUE THREAD

**Issue by aliakhtar** [slick/slick#2083]
I’m trying to follow the examples given in the documentation for running plain SQL queries. According to docs, importing a profile should bring the string interpolation functions (`sqlu` etc) into scope, but I continue to get ‘Symbol not found’ for these functions. My import is:

`import slick.jdbc.PostgresProfile.api._ `

P.S sorry for asking here, I did try gitter but it was pretty inactive, and in the absence of a solution I’m being forced to run a large number of inefficient queries in production, so on a little bit of time crunch.

Thanks.

**Comment by d6y** [comment]
Hello @aliakhtar - please persevere with Gitter. I'll close this issue. 

If you're still stuck, I've created a runnable repository that contains the Plain SQL example from the Slick Manual: https://github.com/d6y/slick-manual-plainsql-example

**Comment by aliakhtar** [comment]
@d6y The problem I'm having is, the `sqlu` method doesn't seem to be getting imported for the postgres profile.

In your example, you're importing `import slick.jdbc.H2Profile.api._` which I believe is importing the `sqlu` symbol, right. I'm importing `import slick.jdbc.PostgresProfile.api._` but I always get the error that `sqlu` etc isn't in scope.

Any ideas how to make this work for postgres / could you update your example to work for postgres?

**Comment by ygots** [comment]
The example works only with the H2 db. How it should be adjusted to work with postgres?
