### ISSUE TITLE
Slick website is currently broken - 404 errors

### ISSUE THREAD

**Issue by PiotrJander** [slick/slick#2084]
E.g. http://slick.lightbend.com/docs/ gives 404

**Comment by d6y** [comment]
The docs are being moved over to https://scala-slick.org/ (via https://github.com/slick/slick/issues/2082) 

That's just started happening. The slick.lightbend.com docs are going to eventually be redirected to the new site (is my expectation).

**Comment by d6y** [comment]
@TimMoore copying you in so you're aware of this.

**Comment by TimMoore** [comment]
Thanks. The DNS changes might take some time to be visible.

**Comment by d6y** [comment]
Looks like the DNS changes are working for me. Let's leave this ticket open for a few more hours in case others have the problem (e.g, maybe stale caches).
