### ISSUE TITLE
Travis build: Stop! java 8.0.232.hs-adpt is already installed.

### ISSUE THREAD

**Issue by d6y** [slick/slick#2087]
This is an issue for tracking a Travis build failure (https://travis-ci.org/slick/slick/jobs/620094769). The error from Travis is: 

```
$ sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)
Stop! java 8.0.232.hs-adpt is already installed.
The command "sdk install java $(sdk list java | grep -o "$ADOPTOPENJDK\.[0-9\.]*hs-adpt" | head -1)" failed and exited with 1 during .
```

I suspect this may just go away if Travis cycles a machine  (if that's how it works).

Or it may be that we need to "do something" to make the Travis build more reliable.

**Comment by marcospereira** [comment]
It looks like we should either not cache `~/.sdk` directory entirely, or handle the situation where that JDK version is already installed. I think the easy fix is to cache only `~/.sdkman/archives/` since downloading the file is possibly the bottleneck here.
