### ISSUE TITLE
`createIfNotExists` doesn't create auto increment sequences

### ISSUE THREAD

**Issue by mdibaiee** [slick/slick#2099]
**DESCRIPTION:**

Using `createIfNotExists` does not create auto increment sequences, whereas `create` works just fine in creating those sequences.

A symptom of this issue is if you use `createIfNotExists` with `O.AutoInc` fields, you will get these errors:

```
postgres    | 2020-02-15 13:46:18.160 UTC [412] ERROR:  null value in column "id" violates not-null constraint
```

This doesn't happen if you have the correct sequence.

**STEPS TO REPRODUCE:**

Clone [mdibaiee/slick-bug-sequences](https://github.com/mdibaiee/slick-bug-sequences) and run the code as is initially:
```
createdb slick_bug

DATABASE_URL=postgresql://testuser:testpassword@localhost:5432/slick_bug sbt run
```

**EXPECTED RESULT:**

Sequence should be created and no error should be thrown.

**ACTUAL RESULT:**

You will get an error:
```
[error] (run-main-0) org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint
[error]   Detail: Failing row contains (null, Test).
[error] org.postgresql.util.PSQLException: ERROR: null value in column "id" violates not-null constraint
[error]   Detail: Failing row contains (null, Test).
[error]         at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
[error]         at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
[error]         at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
[error]         at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
[error]         at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143)
[error]         at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120)
[error]         at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.$anonfun$run$15(JdbcActionComponent.scala:520)
[error]         at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement(JdbcBackend.scala:425)
[error]         at slick.jdbc.JdbcBackend$SessionDef.withPreparedStatement$(JdbcBackend.scala:420)
[error]         at slick.jdbc.JdbcBackend$BaseSession.withPreparedStatement(JdbcBackend.scala:489)
[error]         at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl.preparedInsert(JdbcActionComponent.scala:511)
[error]         at slick.jdbc.JdbcActionComponent$InsertActionComposerImpl$SingleInsertAction.run(JdbcActionComponent.scala:517)
[error]         at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:28)
[error]         at slick.jdbc.JdbcActionComponent$SimpleJdbcProfileAction.run(JdbcActionComponent.scala:25)
[error]         at slick.dbio.DBIOAction$$anon$4.$anonfun$run$3(DBIOAction.scala:239)
[error]         at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:553)
[error]         at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:551)
[error]         at scala.collection.AbstractIterable.foreach(Iterable.scala:921)
[error]         at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:239)
[error]         at slick.dbio.DBIOAction$$anon$4.run(DBIOAction.scala:237)
[error]         at slick.basic.BasicBackend$DatabaseDef$$anon$3.liftedTree1$1(BasicBackend.scala:276)
[error]         at slick.basic.BasicBackend$DatabaseDef$$anon$3.run(BasicBackend.scala:276)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:835)
```

Also try connecting to the database (`psql slick_bug`) and check for sequences and tables:

```
\dt
\ds
```

You will see tables existing, but no sequences.

Now try changing the `src/main/scala/example/Hello.scala` file and replacing `createIfNotExists` with `create`. Drop the database and recreate and run again:

```
dropdb slick_bug
createdb slick_bug

DATABASE_URL=postgresql://testuser:testpassword@localhost:5432/slick_bug sbt run
```

This time there will be no errors and you can check that the sequence is created successfully in postgres shell (`psql slick_bug`):

```
\ds
```

**SETUP:**

Libraries:
```
  "com.typesafe.slick" %% "slick" % "3.3.2",
  "org.postgresql" % "postgresql" % "42.2.5" //org.postgresql.ds.PGSimpleDataSource dependency
```

Postgres 12.1

**Comment by mdibaiee** [comment]
`createIfNotExists` was introduced here: https://github.com/slick/slick/pull/1704

**Comment by itaross** [comment]
I have the same behaviour! I can confirm that creating the schema with create instead of creatIfNotExists is working as expecting, generating BIGSERIAL instead of BIGINT

**Comment by itaross** [comment]
I think I have a clue.
There are two code generation made when calling createIfNotExists:
The two are:
`   protected def createPhase1 = Iterable(createTable(false)) ++ primaryKeys.map(createPrimaryKey) ++ indexes.map(createIndex)
    protected def createIfNotExistsPhase = Iterable(createTable(true)) ++ primaryKeys.map(createPrimaryKey) ++ indexes.map(createIndex)
`

And can be found in JdbcStatementBuilderComponent line 604 and 605.
So when you call this method:

 ```
 override def appendColumn(sb: StringBuilder): Unit = {
      sb append quoteIdentifier(column.name) append ' '
      if(autoIncrement && !customSqlType) {
        sb append (if(sqlType.toUpperCase == "BIGINT") "BIGSERIAL" else "SERIAL")
      } else appendType(sb)
      autoIncrement = false
      appendOptions(sb)
    }

```
The first time it is autoIncrement == true, so the BIGINT becomes BIGSERIAL.
The second time you pass with createIfNotExistsPhase the autoIncrement has been put to false by the previous call.
In this way the BIGINT stays BIGINT and it is not becoming BIGSERIAL.

I suspect that just removing autoIncrement = false in PostgresProfile, line 246 is not enough.

Can you please check? @gnufied @jkutner @marcospereira

**Comment by mdibaiee** [comment]
@itaross I just quickly tried that change but this is the result of removing `autoIncrement = false` from `PostgresProfile`:

```
 Execution exception[[PSQLException: ERROR: both default and identity specified for column "id" of table "actions"]]
```

I'll try to have another more in-depth look, but it would help for maintainers to give us hints on this if they know what's up off the top of their head.

**Comment by itaross** [comment]
Yeah I was quite sure that changing that line was not enough as I have not built and tested the code myself. I am very new to slick but I guess that if you add another toggle to handle the state you should fix.

If autoIncrement = true then apply it two times and then toggle it false, do not toggle it false the first time as it is now. Something like that. This of course it is a just a suggestion that must prove to be fixing the issue.

If I had time I would try myself but in this moment I am really busy :(

**Comment by mdibaiee** [comment]
Okay, so it was a matter of reverting to the original value of `autoIncrement` after running `appendOption`.

`appendOption` is defined:
```
    protected def appendOptions(sb: StringBuilder): Unit = {
      if(defaultLiteral ne null) sb append " DEFAULT " append defaultLiteral
      if(autoIncrement) sb append " GENERATED BY DEFAULT AS IDENTITY(START WITH 1)"
      if(notNull) sb append " NOT NULL"
      if(primaryKey) sb append " PRIMARY KEY"
      if( unique )   sb append " UNIQUE"
    }
```

and since for Postgres we want to avoid the `GENERATED BY DEFAULT...`, `autoIncrement` is set to false before running it, but the problem is that subsequent calls for `addColumns` will lose the original value of `autoIncrement` and this includes the sequences. Tested this locally and worked.

**Comment by itaross** [comment]
Do you have any update on when this will be merged?

**Comment by mdibaiee** [comment]
@itaross honestly, I don't. One of the maintainers should review and merge. I've requested review but got no response yet. Latest commit is October, which is unfortunate. Do you have any idea?

**Comment by SethTisue** [comment]
reviewer wanted on #2100
