### ISSUE TITLE
Improve description on GitHub repo

### ISSUE THREAD

**Issue by eed3si9n** [slick/slick#2108]
**DESCRIPTION:**

The description on this GitHub repo is not descriptive, which affects the search results on GitHub search and Scaladex.

**STEPS TO REPRODUCE:**

- https://index-dev.scala-lang.org/search?q=database
- https://github.com/search?l=Scala&q=database&type=Repositories

**EXPECTED RESULT:**

Slick should show up.

Suggested description is "Slick is a modern database query and access library for Scala."

It would be helpful to also add tags like `database`, `jdbc` etc.

**ACTUAL RESULT:**

Slick doesn't come up in the search result because the description doesn't contain the word database.

**Comment by SethTisue** [comment]
done
