### ISSUE TITLE
Scala 2.13.3 <> deprecation warning

### ISSUE THREAD

**Issue by Randerspl** [slick/slick#2121]
Scala: 2.13.3
Sbt: 1.3.2
Slick: 3.3.2
DB: Sql Server (Sql Server Profile) 
OS: Windows 10
IDE: newest Intellij Community 
JDK: 1.8 (i found it on JDK 11 too)

After upgrading Scala from 2.13.2 to 2.13.3 slick function `<>` throws warning
`multiarg infix syntax looks like a tuple and will be deprecated
[warn]     def * : ProvenShape[ ExampleClass ] = (id, count) <> (ExampleClass.tupled, ExampleClass.unapply)`

Everything works, but i think this should be reported here.

**Comment by Randerspl** [comment]
I found that if we use dot notation of `<>` then scala will not warn anything,
For example `def * : ProvenShape[ ExampleClass ] = (id, count).<>(ExampleClass.tupled, ExampleClass.unapply)` will not warn anything.
Maybe this should be mentioned in slick documentation?

**Comment by hvesalai** [comment]
@Randerspl can you do a PR for the documentation change?
