### ISSUE TITLE
Release 3.3.3

### ISSUE THREAD

**Issue by renatocaval** [slick/slick#2128]
I would like to cut v3.3.3 because of https://github.com/slick/slick/pull/2127

There are a few other open PRs that we can try to add to this release as well:

* https://github.com/slick/slick/pull/2120 - I can review it soonish

**Eventually also**

* https://github.com/slick/slick/pull/2119
* https://github.com/slick/slick/pull/2097
* https://github.com/slick/slick/pull/2061 - documentation 
* https://github.com/slick/slick/pull/2124 - documentation 

Please, let me know if there is anything I'm missing.

/cc @hvesalai, @d6y, @smootoo

**Comment by hvesalai** [comment]
I think we should go through all of these https://github.com/slick/slick/pulls?q=is%3Aopen+is%3Apr+no%3Amilestone

And decide if they are for 3.3.3 or for 3.4.0

Also while you are making a release, would you have time to also take a lead on 3.4.0?

**Comment by renatocaval** [comment]
I will go through the list of PR without a milestone and see what could be added to 3.3.3 and if not, I will assign it to 3.4.0. 

My goal was to only pick low-hanging fruits for 3.3.3. If build is green and is a documentation improvement or bug fix, I was planning to include. 

About taking the lead for 3.4.0, I don't think I will have much time as we have some major stuff on our pipeline for the next 6 months. I can make time for reviews and cut the release when needed though.

**Comment by d6y** [comment]
Is it worth considering snapshot releases (or similar, if they can be automated)? I know historically Slick has not done this.

I'm thinking:  optimistically merge in PRs to master, announce, and so allow users to try out a change against a snapshot comparatively quickly. It's not something anyone would want to rely on: we'd still need to ask Lightbend for a release from time to time. But, an easier way to get the contributed PRs out? 

Perhaps there are other build/release models that would be a better fit.

**Comment by hvesalai** [comment]
I would love to see SNAPSHOTs from master being automated. I still think there are way too many manual steps involved in doing the release. That's why we don't do them more often.

And if everything could be brought to run on github, that would be even better, but don't know if that is feasible at all.

**Comment by Donatas-L** [comment]
@renatocaval Would be great to see 3.3.3 soon.

**Comment by hvesalai** [comment]
@renatocaval will you do the twitter and other announcements (users.scala-lang.org, gitter.im, etc)

**Comment by renatocaval** [comment]
@hvesalai, I did the scala-lang.org and gitter announcement. Is there a twitter account? If so, I don't have access. I can tweet from my own account though.

**Comment by renatocaval** [comment]
I sent a tweet: https://twitter.com/renatocaval/status/1304035150376960003

If someone wants to amplify, be my guest. ;-)
