### ISSUE TITLE
Migrate repository away from travis-ci.org

### ISSUE THREAD

**Issue by ignasi35** [slick/slick#2136]
travis-ci.org will be shutdown on Dec 31st 2020. 

A new CI environment will be required. There are several options:

1. travis-ci.com:  Travis recommends migrating the jobs to travis-ci.com. Go to https://travis-ci.com/organizations/slick/migrate to perform the migration(requires login + permissions). The migration operation requires certain permissions in both travis and github over the repository to be migrated. Also, when migrating, some branch protection rules may be lost so extra work to recover that is required. More info and details on https://docs.travis-ci.com/user/migrate/open-source-repository-migration/
2. GitHub Actions
3. Circle CI
4. others...

**Comment by SethTisue** [comment]
For now, I would suggest simply flipping the switch to option 1. A more ambitious migration could happen later.

slick is its own org and isn't under super active development, so perhaps travis-ci.com's monthly minutes limit won't be something we'll hit.

**Comment by octonato** [comment]
> slick has its own org and isn't under super active development, so perhaps travis-ci.com's monthly minutes limit won't be something we'll hit.

I think we should go with it for now. 

/cc @szeiger

**Comment by slonopotamus** [comment]
> travis-ci.com's monthly minutes limit won't be something we'll hit.

It isn't _monthly_. It is a one-time free quota. You have to file requests for additional minutes.

**Comment by SethTisue** [comment]
I forgot about this ticket and opened #2175, but in any case, we are on travis-ci.com now, on Lightbend's paid plan.

(If a volunteer wanted to move everything to GitHub Actions, that'd be awesome, but I have no intention of tackling it myself.)

**Comment by SethTisue** [comment]
cc @nafg
