### ISSUE TITLE
Re-enable Windows CI (Appveyor or GitHub Actions or...?)

### ISSUE THREAD

**Issue by SethTisue** [slick/slick#2178]
The repo has an `appveyor.yml` and I can see on old pull requests that it used to run.

I'd be happy to re-enable Appveyor in the repo if a volunteer brings it up to date and makes sure it is green.

Or if someone wants to replace it with a GitHub Actions thing instead, that'd be fine too.

**Comment by SethTisue** [comment]
cc @nafg 

but note that switching to GitHub Actions doesn't necessarily involve including Windows support, initially, I certainly wouldn't oppose getting off Travis-CI. We are still on Travis-CI out of inertia and not for any deeper reason.

**Comment by nafg** [comment]
I was wondering if it was outdated so I created a free OSS appveyor account and ran it on the repo and it passed. https://ci.appveyor.com/project/nafg/slick

So maybe it just needed an active account.

I do want to switch to github actions but for now I think we should make sure appveyor runs on all PRs.

**Comment by SethTisue** [comment]
I've approved the request to install Appveyor here (https://github.com/organizations/slick/settings/installations/16020116)

**Comment by nafg** [comment]
I get a 404 with that link. I see builds in my email but they aren't showing up on PRs on github.com.

**Comment by SethTisue** [comment]
I uninstalled Appveyor from the Slick org, then reinstalled it, and it looks like things might be working now -- I mean to the extent that jobs started when I reopened our two test PRs. Let's see how the jobs do

**Comment by SethTisue** [comment]
hey the AppVeyor build is green at https://github.com/slick/slick/pull/2204 , so maybe can close this now?

**Comment by nafg** [comment]
Great, thanks
