### ISSUE TITLE
Drop Scala 2.11 support on main branch?

### ISSUE THREAD

**Issue by SethTisue** [slick/slick#2182]
I propose we drop 2.11 from the main branch. The more Scala versions, the more of a maintenance burden it is, and we can ill-afford maintenance burdens now that Slick is community-maintained.

If someone still needed some important bugfix on 2.11, they would be free to volunteer to maintain a separate 2.11 branch.

**Comment by hvesalai** [comment]
hear hear

**Comment by SethTisue** [comment]
PR: #2184

**Comment by SethTisue** [comment]
> they would be free to volunteer to maintain a separate 2.11 branch

I noticed yesterday that there is a 3.3.x branch.

**Comment by SethTisue** [comment]
I've publicized this a bit at https://groups.google.com/g/scalaquery/c/JC8-MOIvoic

**Comment by SethTisue** [comment]
done
