### ISSUE TITLE
Update github maintainers team to members that are still on the maintainers team

### ISSUE THREAD

**Issue by SethTisue** [slick/slick#2203]
for security reasons, I'd like to remove from https://github.com/orgs/slick/teams/slick-maintainers anyone who isn't still active (and isn't a Lightbend employee)

@d6y @cvogt @tminglei @radsaggi are you still around/involved/interested at all...?

**Comment by SethTisue** [comment]
oh, and I should do the same with https://github.com/slick/slick/settings/access

@trevorsibanda same question

**Comment by d6y** [comment]
I don’t need access to the repos.

**Comment by trevorsibanda** [comment]
Same as @d6y I don't need access.

**Comment by SethTisue** [comment]
removed all of the above. happy to reinstate anyone who wishes to become involved again.
