### ISSUE TITLE
Slick-Website: Redirect to HTTPS and set HSTS header

### ISSUE THREAD

**Issue by domdorn** [slick/slick#2208]
As there is no way to file an issue in the documentation repository:

Please update the security of the scala-slick.org website. Currently, the website is reachable via http and https. 

The following should be done:
1) redirect all http requests to the equivalent https request. 
2) set the HSTS header, so that browsers cache that this website is supposed to be accessed via https. ( https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security ) 

Afaik this can be done by checking a checkbox "Enforce HTTPS". 
This thread talks about that: 
https://github.community/t/how-to-enable-https-support-on-custom-domains/10351/4

in case the checkbox is not available, github support should be able to resolve the issue quickly: 
https://support.github.com/request

**Comment by SethTisue** [comment]
I'm inquiring internally at Lightbend about this.

**Comment by SethTisue** [comment]
Thanks for bringing this to our attention.

I've checked the HTTPs checkbox at https://github.com/slick/slick.github.com/settings/pages

It says it may take up to 24 hours for everything to update, so I'm leaving this ticket open for now.

**Comment by marcospereira** [comment]
It is already doing the redirect:

```bash
$ curl -I -L http://scala-slick.org
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: https://scala-slick.org/
X-GitHub-Request-Id: 101A:51F1:372359:77FB29:607058D0
Content-Length: 162
Accept-Ranges: bytes
Date: Fri, 09 Apr 2021 13:38:33 GMT
Via: 1.1 varnish
Age: 10
Connection: keep-alive
X-Served-By: cache-yyz4537-YYZ
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1617975514.966865,VS0,VE1
Vary: Accept-Encoding
X-Fastly-Request-ID: 0541f1df23c13f4e3f57734ea85a936e0d781188

HTTP/2 200
server: GitHub.com
content-type: text/html; charset=utf-8
last-modified: Mon, 29 Mar 2021 16:44:44 GMT
access-control-allow-origin: *
etag: "606203fc-23c4"
expires: Fri, 09 Apr 2021 13:48:24 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: D5B0:36A9:3E88C1:7F98A8:607058D0
accept-ranges: bytes
date: Fri, 09 Apr 2021 13:38:33 GMT
via: 1.1 varnish
age: 10
x-served-by: cache-yyz4535-YYZ
x-cache: HIT
x-cache-hits: 1
x-timer: S1617975514.996201,VS0,VE0
vary: Accept-Encoding
x-fastly-request-id: d14063f42f087bd3e4b5c0d0f038014e58747481
content-length: 9156
```

Therefore, I'm closing this. Thanks, @domdorn!

**Comment by domdorn** [comment]
mhm.. unfortunately, not entirely:
```
curl -D - http://scala-slick.org/doc/3.3.0/gettingstarted.html | head -n 30
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: text/html; charset=utf-8
x-origin-cache: HIT
Last-Modified: Wed, 09 Dec 2020 10:48:19 GMT
Access-Control-Allow-Origin: *
ETag: "5fd0ab73-ca04"
expires: Fri, 09 Apr 2021 19:51:36 GMT
Cache-Control: max-age=600
x-proxy-cache: MISS
X-GitHub-Request-Id: 7C04:8078:7E6D60:821DEA:6070ADF0
Content-Length: 51716
Accept-Ranges: bytes
Date: Fri, 09 Apr 2021 19:42:10 GMT
Via: 1.1 varnish
Age: 34
Connection: keep-alive
X-Served-By: cache-vie21628-VIE
X-Cache: HIT
X-Cache-Hits: 1
X-Timer: S1617997331.741398,VS0,VE1
Vary: Accept-Encoding
X-Fastly-Request-ID: 699226e2c8aff04947311b572cf7def8b3941b62

<!DOCTYPE html>
<html class="no-js" lang="eng" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
 64 51716   64 33127    0     0   367k      0 --:--:-- --:--:-- --:--:--  367k
 ```
 it should do a redirect instead of sending the response..

**Comment by SethTisue** [comment]
gah, thanks.

I'll ask again within Lightbend, but our IT folks have their hands pretty full at the moment dealing with the Bintray shutdown, so it might be a matter of weeks rather than days

**Comment by SethTisue** [comment]
In the meantime, if anyone has any insight into how I might be able to fix this myself (I don't actually understand any of this stuff), I'm all ears.

**Comment by domdorn** [comment]
@SethTisue I think you need to fill out this form
https://support.github.com/contact?tags=rr-pages

and provide a sample url 
```
http://scala-slick.org/doc/3.3.0/gettingstarted.html
```
that should be redirected to https

**Comment by SethTisue** [comment]
Thanks. I submitted the following support request just now:

> I have enabled "Enforce HTTPS" at https://github.com/slick/slick.github.com/settings/pages , but I find that although the site's front page http://scala-slick.org is redirected as expected, other pages are not, for example http://scala-slick.org/doc/3.3.0/gettingstarted.html

> (this was reported by a user at https://github.com/slick/slick/issues/2208)

**Comment by SethTisue** [comment]
GitHub support, bless them, pointed out that we hadn't enabled "Enforce HTTPS" at https://github.com/slick/doc/settings/pages

I have now done so, so let's circle back in 24 hours and see if that did the trick.

**Comment by SethTisue** [comment]
Maybe we don't need to wait 24 hours, `curl -D - http://scala-slick.org/doc/3.3.0/gettingstarted.html`  is already returning 301, as hoped

**Comment by domdorn** [comment]
<3 thx a lot!
