### ISSUE TITLE
Support JDK 17

### ISSUE THREAD

**Issue by SethTisue** [slick/slick#2212]
Abandoned PR adding JDK 16 to our CI: https://github.com/slick/slick/pull/2199

A volunteer is needed to investigate the failures and revive the PR.

**Comment by xuwei-k** [comment]
https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-usagenotes-known-issues-limitations.html

> Because Connector/J does not enable connections with TLSv1.2 and higher by default due to compatibility issues, when connecting to servers that restrict connections to use those higher TLS versions, you might encounter com.mysql.cj.exceptions.CJCommunicationsException: javax.net.ssl.SSLHandshakeException: No appropriate protocol (protocol is disabled or cipher suites are inappropriate). You need to enable connections with TLSv1.2 and higher versions using the enabledTLSProtocols connection property. See [Section 6.8, “Connecting Securely Using SSL”](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html) for details.

**Comment by nafg** [comment]
Thanks @xuwei-k 

The linked page gives a more specific usage syntax: https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-using-ssl.html#:~:text=enabledTLSProtocols%3DTLSv1%2CTLSv1.1%2CTLSv1.2

Interestingly, #2214 seems fine without any changes.

Should something be changed anywhere other than the travis test-db conf file?

**Comment by nafg** [comment]
Can someone remind me how to add `enabledTLSProtocols=TLSv1,TLSv1.1,TLSv1.2` to `test-dbs/testkit.travis.conf`? Do I put it as an entry in a `properties { }` block?

**Comment by SethTisue** [comment]
Might as well do 17 instead, since 17 is feature-frozen. It's available via GitHub Actions as `17-ea`

**Comment by nafg** [comment]
Didn't you add it already?

**Comment by SethTisue** [comment]
Ah indeed I did! I can't keep all the repos I work in straight :-)
