### ISSUE TITLE
Let GitHub Actions supersede Travis CI

### ISSUE THREAD

**Issue by nafg** [slick/slick#2224]
When appropriate,

- [x] Make GitHub Actions "required" on PRs
- [x] Make Travis CI not "required" on PRs
- [ ] Delete Travis CI files and refactor accordingly

Incidentally... does that circle.yml file serve any purpose?

**Comment by SethTisue** [comment]
I've done the first two steps.

Perhaps excessively cautious, but I think it might be a good idea to wait a week or two on getting rid of Travis-CI — let's first see if GitHub Actions and Travis-CI disagree about any PRs.

**Comment by nafg** [comment]
Totally agreed, that's why I wrote "When appropriate" ;)

**Comment by nafg** [comment]
Thanks

**Comment by SethTisue** [comment]
> Incidentally... does that circle.yml file serve any purpose?

removed in #2234

**Comment by SethTisue** [comment]
@nafg shall we go ahead with switching off Travis-CI now?

**Comment by SethTisue** [comment]
@nafg ping, okay if I proceed here?

**Comment by nafg** [comment]
Fine by me
