### ISSUE TITLE
SQLServer support for UUID is broken (wrong endianness)

### ISSUE THREAD

**Issue by arixmkii** [slick/slick#2291]
Current SQLServerProfile implementation is using default `UUIDJdbcType` from [here](https://github.com/slick/slick/blob/b39dda861573fae05e82a51cf8df02416f8be45b/slick/src/main/scala/slick/jdbc/JdbcTypesComponent.scala#L435) with slight modifications. This doesn't really work as the bytes are converted the wrong way (which seems to be correct for other DB profiles, but not for SQLServer). It is pretty simple to test this comparing the parsed value and the string representation (if map to `String` instead of `UUID` in schema).

The correct way to [read](https://github.com/microsoft/mssql-jdbc/blob/09d35bfc2338f1fc7c41a958d1e627fa0d6a2b65/src/main/java/com/microsoft/sqlserver/jdbc/Util.java#L703) and [write](https://github.com/microsoft/mssql-jdbc/blob/09d35bfc2338f1fc7c41a958d1e627fa0d6a2b65/src/main/java/com/microsoft/sqlserver/jdbc/Util.java#L669) this data type could be checked in JDBC driver sources. They have dedicated utilities to make it compatible.

The code in question is licensed under MIT. If it is acceptable to contribute the code derived from MIT licensed sources I can try to compose a PR fixing this issue.

**Comment by nafg** [comment]
Hmm, doesn't look like the code is accessible to just call.

@SethTisue can you comment on the license question?

**Comment by SethTisue** [comment]
It's fine to include MIT licensed stuff in an Apache 2 licensed project as long as we're careful to credit it properly.

**Comment by SethTisue** [comment]
Oops oh wow Slick isn't Apache 2 it's BSD. I'm surprised because Lightbend standardized on Apache 2 a long time ago.

It's actually okay to include MIT code in a BSD project, too. But also, I've opened a separate issue about switching to Apache 2, and I'll inquire about it at Lightbend https://github.com/slick/slick/issues/2292

**Comment by nafg** [comment]
@arixmkii do you still plan to?

**Comment by arixmkii** [comment]
#2411 PR created
