### ISSUE TITLE
Change license from BSD to Apache 2?

### ISSUE THREAD

**Issue by SethTisue** [slick/slick#2292]
I'm astonished to realize that Slick isn't already Apache 2 licensed. Lightbend standardized on Apache 2 quite some time ago.

I'll make inquiries about changing the license.

**Comment by hvesalai** [comment]
What is the legal implication?

**Comment by SethTisue** [comment]
I back-burnered this since Lightbend OSS has been busy doing the handoff of Play to Open Collective. But we could come back to it this next year.

@hvesalai @nafg Do either of you actually care one way or the other? If you have a preference one way or the other, is it a mild preference or a strong preference?

**Comment by SethTisue** [comment]
> What is the legal implication?

Heh, well, OSS licensing is a pretty big topic. A few remarks:

* One nice thing about Apache 2 is it that it has language in it that arguably obviates any need for a separate CLA
* Companies sometimes like Apache 2 for its patent clause.

but that hardly exhausts the subject...

**Comment by hvesalai** [comment]
I think we already use so much Apache2 in our project that it really doesn't matter to us if Slick is Apache2 or BSD.

**Comment by nafg** [comment]
I guess I don't know enough to know if I care, but I probably don't

**Comment by SethTisue** [comment]
I asked at Lightbend and nobody seemed concerned either way, and you guys don't seem concerned either, so  🤷
