### ISSUE TITLE
`filterIf`'s filter function parameter isn't compatible with `Rep[Option[Boolean]]` return type

### ISSUE THREAD

**Issue by ciuncan** [slick/slick#2303]
In a use like `.filterIf(someBoolean)(aFilterFunctionCompiledToSQL)`, `aFilterFunctionCompiledToSQL` is only limited to return `Rep[Boolean]`. Unlike `.filterOpts` filter function parameter, we cannot return `Rep[Option[Boolean]]`.  With `.filterOpts`, the context bound of return type of the filter function `T` is given as `CanBeQueryCondition`, this actually enables that. The same can be applied to `.filterIf` in a backwards compatible manner, at least I couldn't see how it could break existing codes.

I'm up for implementation of this, I'll open a PR pretty soon.

**Comment by jdsalchow** [comment]
As a workaround you might use `getOrElse` on the `Rep[Option[Boolean]]` to turn it into a `Rep[Boolean]`

**Comment by ciuncan** [comment]
hi @jdsalchow , thank you for the suggestion. We are currently using some workarounds like you mentioned but it is probably for the better for everyone that `Rep[Option[Boolean]]` is supported out-of-the-box. Feel free to take a look at my PR for this, it was pretty straightforward: https://github.com/slick/slick/pull/2304

**Comment by nafg** [comment]
Closed by #2304
