### ISSUE TITLE
jdbcDriver: tinyint SQL type should be presented as Short instead of Byte #1595

### ISSUE THREAD

**Issue by Bugsource** [slick/slick#2305]
The problem is essentially the same as issue 1595:  [tinyint SQL type should be presented as Short instead of Byte #1595](https://github.com/slick/slick/issues/1595)

**Comment by Bugsource** [comment]
or consider JAVA basic type of Int?

**Comment by nafg** [comment]
Can you submit a PR with a fix and a test?

**Comment by Bugsource** [comment]
This may not be an error. The range of Byte  seems corresponding with tinyint for mysql.
