### ISSUE TITLE
slick not joining when explicitly writing a join query

### ISSUE THREAD

**Issue by Bugsource** [slick/slick#2319]
``` scala
    val query = Foo
      .join(Bar)
      .on(_.fooId === _.id)
      .filter { case (foo, bar) =>
        foo.someId === 666 && bar.status === 1
      }
      .map { case (_, bar) => (bar.id, bar.name) }
      .take(1)
```
This code turns into sql statement as follows:
``` mysql
select x2.`id`, x2.`name` from `Bar` x3, `Foo` x2 
where ((x3.`someId` = 666) and (x2.`status` = 1)) and (x3.`fooId` = x2.`id`) 
limit 1
```
As slick's doc says(https://scala-slick.org/doc/3.1.0/sql-to-slick.html#explicit-inner-joins), the syntax `join` and `on` produce explicit join query. So What is going on here?

**Comment by timgautier** [comment]
I think you're misreading the docs. Slick has two DSLs for joining, the explicit one where you explicitly tell slick to join two tables, as in your example, and the implicit one, where you use a for comprehension. It doesn't mean it's going to write a "join" in the produced SQL query.

**Comment by hvesalai** [comment]
Yes.. the SQL produced by Slick is a join even if it doesn't use the join keyword. You only need the `JOIN` keyword for the outer joins and the natural join.

**Comment by nafg** [comment]
I think this is surprising behavior. Shouldn't users have better control over the SQL produced? On some databases it can affect performance.

**Comment by timgautier** [comment]
It would be very nice if slick produced easier to read queries, but given the functionality of slick, and the current complexity of its code, that's a pretty big ask.
We have some very complex queries in our app that uses slick, but the slick queries in general tend to be efficient. In the rare cases we can't get slick to produce SQL the query optimizer will optimize well, we'll either write the SQL manually or create a view and use that.

**Comment by hvesalai** [comment]
@nafg theoretically it might, but in practice the execution plan will be identical whether or not you use the join keyword in this case.
