### ISSUE TITLE
Query.filterIf is not using the same types as the rest of the methods Query.filterNot, Query.filterOpt, Query.filter etc

### ISSUE THREAD

**Issue by sofoklis** [slick/slick#2415]
**DESCRIPTION: Query.filterIf works only with boolean and is not using the same types as the rest of the methods**

```
def filter[T <: Rep[_]](f: E => T)(implicit wt: CanBeQueryCondition[T]): Query[E, U, C] =
    withFilter(f)

  def filterNot[T <: Rep[_]](f: E => T)(implicit wt: CanBeQueryCondition[T]): Query[E, U, C] =
    filterHelper(f, node => Library.Not.typed(node.nodeType, node) )

  /** Applies the given filter, if the Option value is defined.
    * If the value is None, the filter will not be part of the query. */
  def filterOpt[V, T <: Rep[_] : CanBeQueryCondition](optValue: Option[V])(f: (E, V) => T): Query[E, U, C] =
    optValue.map(v => withFilter(a => f(a, v))).getOrElse(this)

  /** Applies the given filter function, if the boolean parameter `p` evaluates to true. 
    * If not, the filter will not be part of the query. */
  def filterIf(p: Boolean)(f: E => Rep[Boolean]): Query[E, U, C] =
    if (p) withFilter(f) else this

 /** Select all elements of this query which satisfy a predicate. This method
    * is used when desugaring for-comprehensions over queries. There is no
    * reason to call it directly because it is the same as `filter`. */
  def withFilter[T : CanBeQueryCondition](f: E => T) = filterHelper(f, identity)

```

I think we should rewrite filterIf to match the types of the other filter methods and it should work, maybe like this:

```
def filterIf[T <: Rep[_] : CanBeQueryCondition](p: Boolean)(f: E => T): Query[E, U, C] =
    if (p) withFilter(f) else this

```

As a result you cannot compare optional columns, use inSetBind with optional arguments etc.

**STEPS TO REPRODUCE:**

Try to compare any columns with optional arguments for example

**EXPECTED RESULT:**

we should be able to use filterIf() with any argument that can be used in the filter method

**ACTUAL RESULT:**

Does not work with optional columns and gives this error:
: Cannot perform option-mapped operation
[error]       with type: (java.sql.Date, Option[java.sql.Date]) => Boolean
[error]   for base type: (java.sql.Date, java.sql.Date) => Boolean
[error]       .filterIf(startDate.isDefined)(_.endDate >= startDate)

**SETUP:**

Just try to use filterIf with any optional columns

**Comment by nafg** [comment]
This was already done in https://github.com/slick/slick/pull/2304 and should be available in 3.4.0-M1
