### ISSUE TITLE
java.lang.IllegalArgumentException: requirement failed: count cannot be decreased

### ISSUE THREAD

**Issue by lenin122** [slick/slick#2417]
It seems some cases for this error where fixed in https://github.com/slick/slick/issues/1856, so, we are using slick 3.3.2 with play-slick 5.0.0 and seems, we won't receive it, but we do:
![image](https://user-images.githubusercontent.com/8101083/162400441-68fa4026-52d4-4619-9653-cc9a22af0212.png)
![image](https://user-images.githubusercontent.com/8101083/162401153-06128f27-bc6a-4e95-a490-4044b47a73cb.png)

More annoying thing, mostly after that connection pool throws Timeout Exception on getting connection from Hickari pool.

Also, we use newrelic agent 7.6.0 to collect metrics. Without it, slick works faster.

**Comment by akozumpl** [comment]
Hi @lenin122, would it be possible for you to try out with 3.4.0-M1 and confirm you're still seeing this?

**Comment by lenin122** [comment]
> Hi @lenin122, would it be possible for you to try out with 3.4.0-M1 and confirm you're still seeing this?

I think no, unfortunately. First, I should exclude slick from play-slick and add M1 to dependencies, if there will be no problems, after that I should deploy it on prod instance. This is rather bad idea to deploy this replaced package on prod, I assume)

**Comment by lenin122** [comment]
> Hi @lenin122, would it be possible for you to try out with 3.4.0-M1 and confirm you're still seeing this?

Hello!
I had excluded slick from play slick 5.0.0, disabled evictions and added slcik 3.4.0-M1 directly in my projects sbt, and seems issue is fixed. Waiting for release, thank you!

**Comment by akozumpl** [comment]
That sounds good, ping this ticket again if that didn't help in the end.

**Comment by nafg** [comment]
So I guess this should be closed?
