### ISSUE TITLE
update query returns number of selected rows instead of number of affected rows

### ISSUE THREAD

**Issue by aronschmidt** [slick/slick#2426]
**DESCRIPTION:**

When the update method on a filtered TableQuery is called, I expect the result Integer to be the number of affected rows. Instead it seems to be the number of selected rows, no matter if the rows have changed or not. In phpMyAdmin it says the correct number of affected rows. Why is it different in slick?

**STEPS TO REPRODUCE:**

1. `table += Row(1)`
2. `table filter(_.row == 1) update Row(1)`

**EXPECTED RESULT:**

`updateResult == 0`

**ACTUAL RESULT:**

`updateResult == 1`

**SETUP:**

- MySQL 8.0.23-commercial
- mysql-connector-java:8.0.27
- play-slick:5.0.0
- Play Framework 2.8.11
- slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"

**Comment by nafg** [comment]
From https://stackoverflow.com/a/21068016/333643 (the answer, which is really different than the question) it sounds like this is the behavior of the MySQL JDBC driver, but it can be changed by passing it `useAffectedRows=true`.

**Comment by nafg** [comment]
I'm closing this assuming this solves it; if this is not the case feel free to reopen.
