### ISSUE TITLE
Invalid SQL when upserting a record to a PK-only Postgres table

### ISSUE THREAD

**Issue by uharaqo** [slick/slick#2518]
**DESCRIPTION:**

`set` part is missing in generated UPDATE queries when there is no non-PK columns:
```
update "projects" set  where "id"=?;               // PK only
                     ^^
```

It works when there are non-PK columns:
```
update "projects" set "updated_at"=? where "id"=?; // PK+Col
                     ^^^^^^^^^^^^^^^^
```

**STEPS TO REPRODUCE:**

```
class Projects(tag: Tag) extends Table[(String)](tag, "projects") {
  def id = column[String]("id", O.PrimaryKey)
  def * = (id)
}

projects.insertOrUpdate("proj1")
```

**EXPECTED RESULT:**

Issue "insert if not exists" instead of "update if exists, and insert if not exists" if there's no non-PK columns.

**ACTUAL RESULT:**

An error is thrown due to the invalid update statement: `org.postgresql.util.PSQLException: ERROR: syntax error at or near "where"`

This is caused because of the empty `softNames` [at this line](https://github.com/slick/slick/blob/main/slick/src/main/scala/slick/jdbc/PostgresProfile.scala#L217).

**SETUP:**

Slick 3.3.3, `PostgresProfile`

**Comment by jkugiya** [comment]
Maybe, duplicated to #2207

**Comment by nafg** [comment]
Indeed, you are hitting #2207. Add any input there.
