### ISSUE TITLE
Documentation: starter links are broken, fix the doc link is broken too

### ISSUE THREAD

**Issue by benjamin-thomas** [slick/slick#2523]
Hello,

Just wanting to have a quick look at scala/slick this morning so I head to the latest doc:

https://scala-slick.org/doc/3.3.3/gettingstarted.html#quick-introduction

This section looks appealing:

---

To learn the basics of Slick, start with the Hello Slick sample ([github](https://github.com/slick/slick/tree/3.3/samples/hello-slick), [zip](https://example.lightbend.com/v1/download/hello-slick-3.3)). This is the one we are using in this chapter.

---

However both links are broken :(

I seem to find the starter project eventually here: https://github.com/slick/hello-slick

Rather than creating an issue, I think about fixing the links myself and click on the [Edit on GitHub](https://github.com/slick/slick/blob/master/doc/src/gettingstarted.md) link in the documentation header.

However, that link is broken too :sob: 

---

PS: okay, so all links in the Getting Started section are broken

**Comment by benjamin-thomas** [comment]
Update : so I see the github links have been fixed here:

https://scala-slick.org/doc/3.4.0-M1/gettingstarted.html#quick-introduction

However the zip links are still broken and look like they should be removed.

The "Edit on GitHub" is still broken there.

**Comment by nafg** [comment]
A lot has been fixed since then. Is anything broken on https://scala-slick.org/doc/3.4.0-RC3/gettingstarted.html#quick-introduction ?

**Comment by benjamin-thomas** [comment]
One of the first link is still broken:

"To learn the basics of Slick, start with the [Hello Slick sample](https://github.com/slick/samples/hello-slick)" --> 404!

---

Following the doc at `/doc/3.4.0-M1`, the code did run though if that was the question.

If you're still making changes and I may suggest a doc improvement, it would be to replace the `h2` backend with `sqlite` so that the database changes can be observed independently of the code.

Or better yet, just use a `postgresql` or `mysql` backend since it's very easy to spin one up with a docker-compose file these days :)

**Comment by nafg** [comment]
Regarding the backend used in the samples:
1. You can open H2 databases with other tools. To do so simultaneously either run it in server mode or use [automatic mixed mode](https://h2database.com/html/features.html#auto_mixed_mode). H2 itself comes with a [minimal web UI](https://h2database.com/html/tutorial.html#tutorial_starting_h2_console), plus you can use any database tool that supports JDBC. For instance IntelliJ has great support for it.
2. You can contribute any improvement to the docs by opening a PR. Feel free to open one that uses a postgres instance, for instance via testcontainers.org. That said, I think H2 has a big advantage of needing zero setup.

**Comment by nafg** [comment]
> One of the first link is still broken:
> 
> "To learn the basics of Slick, start with the [Hello Slick sample](https://github.com/slick/samples/hello-slick)" --> 404!


Thanks for catching this! It's fixed now at https://scala-slick.org/doc/devel/gettingstarted.html

**Comment by nafg** [comment]
I've also updated https://scala-slick.org/docs/ so that the docs links use URLs that don't need to be kept up to date
