### ISSUE TITLE
slf4j-api update is cumbersome

### ISSUE THREAD

**Issue by martijnhoekstra** [slick/slick#2542]
The update to slf4j-api 2.0 is a bit cumbersome -- it forces the upgrade to all consumers while not using it. The upgrade isn't necessarily trivial, and there is no downside on staying on 1.x for now: projects on slf4j-api 2.0 can use a safer forward override, while the situation where we are now, forcing an override to slf4j-api 1.x is more fragile: if any dependencies start actually usisng 2.0 API's, this would break.

**Comment by nafg** [comment]
I regret including the PR in the final release but the question is whether it's worth immediately releasing 3.4.1 with that reverted. If people think that's the way to go I'm perfectly happy to do it. But maybe it would cause more problems?

**Comment by martijnhoekstra** [comment]
I'm a person and I would welcome it :)

Moving back to 1.x and releasing 3.4.1 with it immediately would be binary breaking only for those people that use the slf4j fluid API introduced in 2.x, and drop in a newer binary slf4j, without trying to rebuild. I think that's worth it.

Next time, I'll proritize running RC's in time to help catch all that.

**Comment by nafg** [comment]
It wouldn't have helped because it got merged after RC

**Comment by nafg** [comment]
Can you expand on the potential issues of having to upgrade?

Anyway if no one objects I can do it a bit later

**Comment by nafg** [comment]
I haven't posted the 3.4.0 announcement yet, on the one hand that means rolling it back is less of an issue, in the other hand fitting it into a single announcement will be more awkward to phrase

**Comment by mkurz** [comment]
Play will not upgrade to slf4j v2 in the current stable 2.8.x branch, only in 2.9, which is still months away.
Therefore for Play it would be better to stay on slf4j v1 in slick for now. There are reports that slf4j v2 isn't compatible with Play at this point: https://github.com/playframework/playframework/issues/11400 - even though a possible fix arrived already: https://github.com/playframework/playframework/pull/11419 - if that fix works people can just upgrade themselves, on their own risk.

So I recommend to stay on v1 in slick for now. (Even if the linked patch makes v2 work nicely with Play, we don't know if any other problems will come up)

**Comment by martijnhoekstra** [comment]
Upgrading to slf4j API 2.0 is breaking for us because the web framework we're using assumes the service discovery mechanisms of slf4j API 1, and doesn't (as far as I can find in the documentation) an way to access the service loading capabilities that slf4j 2.0 relies on.

So the short of it is, switching to slf4j API 2.0 means no application level logging other than to stdout for me for now.

**Comment by martijnhoekstra** [comment]
> I haven't posted the 3.4.0 announcement yet, on the one hand that means rolling it back is less of an issue, in the other hand fitting it into a single announcement will be more awkward to phrase

Can't be as awkward as the deluge of projects that will have to find a way to phrase to their downstreams that because they chose Akka as an internal choice the downstream has nothing to do with, they will now owe Lightband thousands of dollars per year if they want to keep getting updates :trollface: 

Anyway, I feel your plight, but I think a release notification of just 3.4.1 with a footnote saying that 3.4.0 was published but skipped because it contained bigger breaking changes than you were comfortable with shipping in this version sounds completely plausible to me. The great effort that went into getting this release out at all (for which a big thank you is in place) is in no way deminished by a slightly awkward skipped .0 patch version. If that's the only rough around the edges of 3.4.0 that we're going to experience, you've done a pretty fantastic job.

**Comment by nafg** [comment]
3.4.1 is on maven central, please test

**Comment by maratermeshev** [comment]
@nafg 
This dependency:
//https://mvnrepository.com/artifact/com.typesafe.slick/slick
libraryDependencies += "com.typesafe.slick" %% "slick" % "3.4.1"
leads to this error:
```
[error] stack trace is suppressed; run 'last update' for the full output
[error] stack trace is suppressed; run 'last ssExtractDependencies' for the full output
[error] (update) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* com.typesafe.slick:slick_2.13:3.4.1 (pvp) is selected over {3.3.2}
[error] 	    +- my_app:my_app_2.13:1.0                       (depends on 3.4.1)
[error] 	    +- com.typesafe.slick:slick-hikaricp_2.13:3.3.2       (depends on 3.3.2)
[error] 	    +- com.typesafe.play:play-slick_2.13:5.0.2            (depends on 3.3.2)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] (ssExtractDependencies) found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[error]
[error] 	* com.typesafe.slick:slick_2.13:3.4.1 (pvp) is selected over {3.3.2}
[error] 	    +- my_app:my_app_2.13:1.0                       (depends on 3.4.1)
[error] 	    +- com.typesafe.slick:slick-hikaricp_2.13:3.3.2       (depends on 3.3.2)
[error] 	    +- com.typesafe.play:play-slick_2.13:5.0.2            (depends on 3.3.2)
[error]
[error]
[error] this can be overridden using libraryDependencySchemes or evictionErrorLevel
[error] Total time: 4 s, completed Sep 15, 2022 10:44:35 PM
[info] shutting down sbt server
```

This dependency provides no errors:
//https://mvnrepository.com/artifact/com.typesafe.slick/slick
libraryDependencies += "com.typesafe.slick" %% "slick" % "3.+"

Using Java 8

How to make 3.4.1 available for me?

**Comment by nafg** [comment]
If you depend on play-slick then you need to wait for them to release, or else follow the instructions to override given in the error you posted.

**Comment by SethTisue** [comment]
> If that's the only rough around the edges of 3.4.0 that we're going to experience, you've done a pretty fantastic job.

seconded

**Comment by jitsumi** [comment]
Hello

We (my team) just noticed that the 3.4.0 is breaking our logs (because we are using slf4j v1)
3.4.1 is fixing the issue

But i just saw that the dependency was automatically updated again:
https://github.com/slick/slick/pull/2549
https://github.com/slick/slick/pull/2554
https://github.com/slick/slick/pull/2562
https://github.com/slick/slick/pull/2563

should we plan to update to slf4j v2? we are worrying that it may not be that easy (because of some other libs that may require the v1)

**Comment by nafg** [comment]
I was planning 3.5.0 to be more breaking. But if that's an issue I suppose we can be more conservative
