### ISSUE TITLE
How to use plain sql with Postgres profile?

### ISSUE THREAD

**Issue by ygots** [slick/slick#2614]
See the similar question here https://github.com/slick/slick/issues/2083
The given answer can not be applied to the `slick.jdbc.PostgresProfile.api._`
Where one can get these interpolation functions like `sqlu` with the Postgres profile?

**Comment by nafg** [comment]
It works for me, why do you say PostgresProfile doesn't work?

**Comment by nafg** [comment]
You can see here that it compiles: https://github.com/slick/slick-manual-plainsql-postgres-example/actions/runs/3615582509/jobs/6092769773

**Comment by nafg** [comment]
(I forked the repo mentioned in #2083, changed the import to postgres in https://github.com/d6y/slick-manual-plainsql-example/commit/644778d1a493959478333cc69f99ecbb5cdd32b2, and used the default GitHub Actions for Scala.)

**Comment by nafg** [comment]
Please reopen if it's not solved.
