### ISSUE TITLE
Suggestion for upgrade to Scala 3

### ISSUE THREAD

**Issue by djx314** [slick/slick#2615]
About upgrading to scala3, there's some suggestion before when a hero is out.
### We can do something about cross build
Like in scala2, `def *= (i1, i2).mapTo[Model]` is use HList to fix 22 problem, but in scala3 there's no 22 problem. We can use codegen in scala2, that gen
```scala
RepCol(i1, i2, ...)
// to 255 parameters
```
This is a wrapper that just output a HList(or can output Tuple when parameter size is `1 - 22` and processed by `mapTo`), but in scala3, we know that we just provide a
```scala
RepCol(Tuple)
```
is ok. So in slick with scala2, we do this changing can avoid the compatibility issues when the update actually occurs.

And more, we get the model type in a instance of TableA, we just use `type projection`, this is drop in scala3, a method that is compat in scala2 and scala3 is provide a given
```scala
def getModel[T <: Table[_], M](implicit getM: GetModelTypeFromTable.Aux[T, M]): M
```
then we can use `type projection` to gen the `M` in scala2(so you can just still use `type projection` in scala2), and in scala3, it's easy gen `M` use `match types`.

and so on.

A lot of work can do in cross build before a hero is out. On the other hand, these works also guide the upgrade of slick and reduce the burden of heroes. At the same time, it gives users confidence to be compatible with scala3.

Of course, we can provide sufficient test cases for these changes what almost just about type checking.

**Comment by nafg** [comment]
Hi, thanks for your ideas!

1. I don't understand the use case for RepCol(i1...i255). When would someone need to use something like that?
2. Is the second part of what you wrote, about GetModelTypeFromTable, connected to the first part, or is it an unrelated idea?
3. When is using type projection or GetModelTypeFromTable needed?

**Comment by djx314** [comment]
@nafg created a repo <https://github.com/djx314/pre-cross-demo-for-slick> and need some time to write a demo.

**Comment by djx314** [comment]
@nafg finish the example above.

https://github.com/djx314/pre-cross-demo-for-slick/blob/master/src/test/scala-2/demo/slick/TableTest.scala#L66

Use `forTuple` to build the `ProvenShape` can be both compat `Tuple22`, `HList` and `Scala3 Tuple`. Just codegen to 255 parameters that enough for `Scala 2` and it's no need to use codegen in `Scala 3`. since `Scala 3` use this is ok

https://github.com/djx314/pre-cross-demo-for-slick/blob/master/src/main/scala-3/demo/slick/TableForModel.scala#L16

Use `TableForModel.TakeModel` that can get the Model type both in `Scala 2` and `Scala 3`, when `Scala 3` is simply remove the `Type Projection` is ok.

I think that before the emergence of a hero, the slick community can find many solutions that directly reduce the burden of compat like the example above.

**Comment by djx314** [comment]
Compat `Scala 3`(source compat) before upgrade to `Scala 3` is better that compat `Scala 3`(source compat) when upgrading to `Scala 3`.

**Comment by nafg** [comment]
3.5.0-M4 is now on maven central, cross-published for 2.12, 2.13, and 3.2.2!

**Comment by djx314** [comment]
@nafg Got it a minute ago and alreay downloading it from maven central!

**Comment by djx314** [comment]
Close as https://github.com/slick/slick/issues/2177 and will open a new issue if there are new problems.
