### ISSUE TITLE
Sbt hangout if the row final case class didn't match table definition

### ISSUE THREAD

**Issue by tlightsky** [slick/slick#2682]
**DESCRIPTION:**

When I try to add a new filed in the final case class, sbt just hangout, but if I remove it, it can compile
Also report it here: https://github.com/scala/bug/issues/12755

**STEPS TO REPRODUCE:**

clone this repo: https://github.com/tlightsky/test-hangout1

**EXPECTED RESULT:**

It will compile

**ACTUAL RESULT:**

Sbt hangout

**SETUP:**

`sbt compile`

**Comment by nafg** [comment]
Why do you think it's a bug in Slick? Is Slick necessary to reproduce it?
