### ISSUE TITLE
Insert with autoincrement -- please support regular and forced insert

### ISSUE THREAD

**Issue by macias** [slick/slick#27]
Currently SQ supports only (directly) forced insert. However it should be possible to allow insert in both modes.

Table.forceInsert(record) <-- insert new record and pass all fields -- today it is insert
Table.softInsert(record)  <-- insert new record, but pass fields except autoinc

All pieces are in place, you have AutoInc flags so it is possible to rule them out automatically. Currently it is possible to do "soft" insert but it requires each time quite work:
- create and maintain correct projection -- this is redundant
- inserts using tuples instead of class -- using named arguments (for clarity) is not possible

**Comment by polkovnikov-ph** [comment]
I'm in the same situation as @mdedetrich was, and still see no solution for this in a user manual.

How does `slick` determine that the column is autoincrementing? There's a `varchar(32) DEFAULT nextval('sequence')::VARCHAR(32)` column in a wide table in a `postgres` database and `case class` gets generated with `String` field, not an `Option[String]`.

It would be OK to insert into projection as shown in the manual if there were a way to throw out one column, not to list all the other.
