### ISSUE TITLE
Slick 3.2 to 3.4 upgrade breaks inSet with NoSuchMethodError

### ISSUE THREAD

**Issue by MasterDDT** [slick/slick#2874]
**DESCRIPTION:**

I previously was on openjdk8 with slick 3.2.1 and have some code like this:

```
class MySlickTable {
  def name: slick.lifted.Rep[String] = column[String]("name")

tbl.filter(t => t.name.inSet(Set("blah", "foo"))
```

Worked fine, but when I upgraded to openjdk17 + slick 3.4.1, the exact same code now gives this runtime error (compiles fine):

```
java.lang.NoSuchMethodError: 'slick.lifted.Rep slick.lifted.BaseColumnExtensionMethods.inSet(scala.collection.Traversable, slick.lifted.OptionMapper2)'
```

The only API difference I see is the `inSet(a: Traversable[T])(implicit: OptionMapper)` changed to `inSet(a: Iterable[T])(imp...)` but that doesn't seem related.

**STEPS TO REPRODUCE:**

See above

**EXPECTED RESULT:**

I looked over the upgrade notes, dont see anything about `inSet`, so expect this should work.

**ACTUAL RESULT:**

Does not work

**SETUP:**

See above

**Comment by nafg** [comment]
Can you share a reproducible build? I'm pretty sure that error means your runtime classpath is different than your compile-time classpath.

Specifically, the runtime error is that the compiled classfile expects a method taking a Traversable, which is the old API as you say. It sounds like you compiled with the old version on the classpath and are running the classfiles thus produced with the new version on the classpath.
