### ISSUE TITLE
3.5.0 filter === fails with scala3

### ISSUE THREAD

**Issue by rgosi** [slick/slick#2914]
**DESCRIPTION:**
Using 3.5.0 with scala3 filter(_.id === 101) fails

**STEPS TO REPRODUCE:**
Using 'hello-slick' add a this test to TablesSuite.scala:
  test("SQL of Query Suppliers by id") {
    createSchema()
    insertSupplier()

    val findById = suppliers.filter(_.id === 101)
    println(s"findById Sql: ${findById.result.statements.head}")
  }
and add this to build.sbt: ThisBuild / scalaVersion := "3.3.1"

**EXPECTED RESULT:**
produces sql with where condition: ... WHERE "SUP_ID" = 101

**ACTUAL RESULT:**
produces sql with where condition: ... WHERE false

if your replace scalaVersion with 2.13.13 you would get the expected result

**SETUP:**
just use 'hello-slick' and switch scalaVersion from 2 to 3 and filter(_.id === 101) fails

**Comment by agolovenko** [comment]
Upvoting this! I encounter the same issue whenever I use `===`. The only detail I'd like to add is that scalac option must be set to  `-source:3.0` (with `-source:3.0-migration` it works fine):

```java.util.NoSuchElementException: empty result setSome( when invoking statement select "id", "comp_type", "comp_types", "opt_comp_types" from "content"."test_comp_types" where false)```

**Comment by rgosi** [comment]
The "-source:3.0-migration" worked, thanks.
If that is a scala3 issue, and filter <,> works, then it begs the question why not === ?

**Comment by agolovenko** [comment]
No idea TBH. Could this please be fixed?

**Comment by yadavan88** [comment]
Hi,
Based on [this discussion](https://github.com/slick/slick/discussions/2918), I am getting this issue only in the test using ScalaTest. With MUnit, it is working fine. 
Is it the case for others too?

**Comment by nafg** [comment]
Ok that makes perfect sense and rings a bell. ScalaTest also defines a `===` operator. It could be import precedence issues.

**Comment by yadavan88** [comment]
Ok, so I can confirm the issue is due to === being used from ScalaTest instead of Slick. Adding the import `import slick.jdbc.H2Profile.api._` inside the test class works.

```
class SlickApp extends funsuite.AnyFunSuite {
  import SlickTables._
  import slick.jdbc.H2Profile.api._

  test("slick scala 3 upgrade") {
  ....
  db.run(playerTable.filter(_.country === "Swiss").result) // this works as === is used from Slick and not ScalaTest
  ....

  }
}
```

**Comment by jkugiya** [comment]
I am not sure what rule change affected this, but changing the order of imports seems to be the solution.

- This will not work.

```scala
import slick.jdbc.H2Profile.api._
class ExampleTest extends AnyFlatSpec {
  import TableDefinition._
  val suppliers = TableQuery[SupplierTable]

  "it" should "be compiled" in {
    val findById = suppliers.filter(_.id === 101)
    assert(!s"findById Sql: ${findById.result.statements.head}".endsWith("false"))
  }
}
```

- it works

```scala
class ExampleTest extends AnyFlatSpec {
  import TableDefinition._
  import slick.jdbc.H2Profile.api._

  val suppliers = TableQuery[SupplierTable]

  "it" should "be compiled" in {
    val findById = suppliers.filter(_.id === 101)
    assert(!s"findById Sql: ${findById.result.statements.head}".endsWith("false"))
  }
}
```

- this also works

```scala
class ExampleTest extends AnyFlatSpec with slick.jdbc.H2Profile.JdbcAPI {
  import TableDefinition._
  val suppliers = TableQuery[SupplierTable]

  "it" should "be compiled" in {
    val findById = suppliers.filter(_.id === 101)
    assert(!s"findById Sql: ${findById.result.statements.head}".endsWith("false"))
  }
}
```

**Comment by nafg** [comment]
Any reason for this issue to remain open?
