### ISSUE TITLE
Slick allows null characters to be passed to postgres, causing exceptions

### ISSUE THREAD

**Issue by jdrphillips** [slick/slick#2943]
The default mappers for string pass null characters (ie `0x00`) into postgres, which throws exceptions.

The default string mapper for postgres should filter out null characters that are not compatible with postgres.

It is very hard to avoid this issue as everything provided by default "for free" for string in all ecosystems allow `0x00` as a valid character, which means it sails through the system to land in postgres.

I could write my own custom string type mapper which does this filtering, but then I will never be sure which typemapper is being used in any site - my own or slick's.

I could wrap every single string type in a wrapper to filter out the null characters but this is a lot of work - but might be the only solution.

I'nm unaware of a way to use a custom profile to get around this issue but I would love to hear one if one exists

**Comment by nafg** [comment]
PR welcome ;)

**Comment by nafg** [comment]
A PER without a test is OK. But if you want we could do a call

**Comment by jdrphillips** [comment]
https://github.com/slick/slick/pull/2944

No test. At work all week but I will read other PRs in my downtime to try to figure out how tests work!
