### ISSUE TITLE
nightly builds

### ISSUE THREAD

**Issue by szeiger** [slick/slick#352]
_[Migrated from Assembla ticket [99](https://www.assembla.com/spaces/typesafe-slick/tickets/99) - reported by @cvogt on 2013-03-06 15:25:03]_

create and publish nightly builds of Slick and its documentation

**Comment by SethTisue** [comment]
since development is no longer very active, I don't think there's much value in pursuing this. though if someone wanted to volunteer to get us on sbt-ci-release, that would be awesome, that would make it very easy to publish prereleases for folks to test
