### ISSUE TITLE
Feature request: Async interface

### ISSUE THREAD

**Issue by rditerwich** [slick/slick#44]
Especially useful now async drivers are emerging for for example postgresql. Monadic design can be used?

**Comment by johanatan** [comment]
Any ETA on this? Is there a pull request currently in flight for review? If so, which one?

**Comment by cvogt** [comment]
Coming in a few weeks. PR has been merged. Here is how it is going to look like: https://skillsmatter.com/skillscasts/5969-upcoming-in-slick-2-2

**Comment by szeiger** [comment]
Available in 3.0.0-M1
