### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by nafg** [slick/slick#46]
I started working on a Migrations DSL, with G-d's help. I posted the initial code here: https://groups.google.com/d/topic/scalaquery/_Kk_hrkliCM/discussion

**Comment by driverpt** [comment]
Any ETA on this ?

**Comment by cvogt** [comment]
@driverpt There is Scala Forklift https://github.com/lastland/scala-forklift which has been developed for Slick, but is not coupled to Slick. It can be combined with https://github.com/nafg/slick-migration-api

I'd say we just document those and close this? Maybe also create a sample project for using Flyway?

**Comment by cvogt** [comment]
Maybe @lastland would like to contribute the documentation? Can be small and cross reference Forklift's documentation.

**Comment by lastland** [comment]
@cvogt Sure. I will look into this.

**Comment by driverpt** [comment]
@cvogt @lastland ty both. I've been struggling a bit trying to glue things together. I'm a Scala newbie, so please be patient with my ignorance.

**Comment by lastland** [comment]
@driverpt Hi, I'm not familiar with Flyway, but if you would like to give Forklift a try here are a few examples: [Forklift](https://github.com/lastland/scala-forklift/tree/develop/example), [Forklift with Play](https://github.com/lastland/play-slick-forklift-example). Forklift supports migrations written in type-safe queries or plain SQL queries. It's also integrated with the Slick code generator so your code related to data models are automatically maintained.

Beware that Forklift is still somehow new so bugs are possible. You may not want to use it in places where reliability is big concern. 

You can contact me (via [GitHub Issues](https://github.com/lastland/scala-forklift/issues) or [Gitter](https://gitter.im/lastland/scala-forklift)) if you have any questions or have found any problems on Forklift.

**Comment by driverpt** [comment]
@lastland I'm going to give it a try.

I've worked before in a Ruby on Rails project and i admit that the only thing that i loved about RoR was the Migrations API:

Here's an example:

```
class AddPeopleSalary < ActiveRecord::Migration
  def up
    add_column :people, :salary, :integer
    Person.reset_column_information
    Person.all.each do |p|
      p.update_attribute :salary, SalaryCalculator.compute(p)
    end
  end
end
```

This is what i'm trying to achieve with Slick.

**Comment by lastland** [comment]
@driverpt That should be provided by [slick-migration-api](https://github.com/nafg/slick-migration-api). However, I'm not sure if it supports Slick 3. Maybe @nafg can comment on this?

It shouldn't be difficult to support slick-migration-api in Forklift. I will also look into this.

**Comment by nafg** [comment]
There's a PR for Slick 3, unfortunately I haven't reviewed and merged it
yet.

**Comment by cvogt** [comment]
@nafg so it's in the documentation now. Maybe you manage to squeeze out some time to review and merge the PR :)

**Comment by lastland** [comment]
@driverpt Hi, [Scala-Forklift 0.2.3](https://github.com/lastland/scala-forklift/releases/tag/v0.2.3) has been released. Now you can alter tables using slick-migration-api instead of plain SQL queries like this:

```scala
import slick.migration.api.TableMigration
import slick.migration.api.H2Dialect
import com.liyaos.forklift.slick.APIMigration
import datamodel.v2.schema.tables._

object M3 {
  implicit val dialect = new H2Dialect

  MyMigrations.migrations = MyMigrations.migrations :+ APIMigration( 3 )(
    TableMigration(Users).
      renameColumn(_.first, "firstname").
      renameColumn(_.last, "lastname"))
}
```

**Comment by cvogt** [comment]
super awesome :)
