### ISSUE TITLE
[migrations-tool] driver-independence

### ISSUE THREAD

**Issue by szeiger** [slick/slick#464]
*[Migrated from Assembla ticket [265](https://www.assembla.com/spaces/typesafe-slick/tickets/265) - reported by @cvogt on 2013-06-05 10:32:52]*

the migrations tool currently hard codes the h2 driver. It needs to be made driver independent with a configurable database.

https://github.com/cvogt/migrations

**Comment by cvogt** [comment]
all fixed. see migration page in wiki
