### ISSUE TITLE
Support for not quoting table & column names in generated SQL.

### ISSUE THREAD

**Issue by LeifWarner** [slick/slick#47]
When I run FooTable.ddl.create, the SQL CREATE statements have quotes around the table and column names.  With H2 DB, this causes all following queries to be required to also quote those names for them to be recognized.  This messes up queries coming from other sources, e.g. ActiveRecord.  Would it be much work to stop this from being done?  I'm using this to generate the schema to run tests against, and I could either change that behavior here, or get ActiveRecord in Rails to start adding quotes to all table names in the generated SQL.

**Comment by tomeksamcik** [comment]
I have a similar issue with Postgres, in Postgres identifiers can be created as case-insensitive and can be queried case-insensitive as long as they are not double-quoted. Has this been ever added to Slick ?
