### ISSUE TITLE
direct embedding rename .result to .run

### ISSUE THREAD

**Issue by szeiger** [slick/slick#495]
*[Migrated from Assembla ticket [296](https://www.assembla.com/spaces/typesafe-slick/tickets/296) - reported by @cvogt on 2013-07-19 11:09:10]*

**Comment by Sumith1896** [comment]
@szeiger Link broken. Issue needs more description.

**Comment by Sumith1896** [comment]
Oh wait, is Direct Embedding deprecated?

**Comment by cvogt** [comment]
deprecated, yes. closing this

**Comment by Sumith1896** [comment]
So do we close all the direct embedding issues? There seems to be a lot.

**Comment by cvogt** [comment]
I think so. @szeiger?

**Comment by Sumith1896** [comment]
Let me know if we willing closing all such issues. I can help in marking such open ones.

**Comment by cvogt** [comment]
I think they are all tagged

**Comment by Sumith1896** [comment]
Cool. That'll help :)
