### ISSUE TITLE
example how to map HList >22 to case class

### ISSUE THREAD

**Issue by szeiger** [slick/slick#519]
_[Migrated from Assembla ticket [320](https://www.assembla.com/spaces/typesafe-slick/tickets/320) - reported by @cvogt on 2013-10-11 10:00:48]_

People will ask for this. I don't see how we can do it in a type-safe way, but using reflection. Not perfect, but not a huge problem either I think as it would fail rather early anyways in case of a mistake.

**Comment by fommil** [comment]
I actually had, in my personal TODO list, an item to automatically create trivial `GetResult` instances for basic case classes using shapeless (in particular the fancy new 2.1 TypeClass stuff). In light of #1052 I've just scratched it off the list.

**Comment by mdedetrich** [comment]
@fommil , how exactly is #1052 related to this?

**Comment by fommil** [comment]
That's really quite obvious.

**Comment by melrief** [comment]
I tried myself to implement a `Shape` for Shapeless `HList` based on the implementation for Slick's `HList` but I'm stuck on the `Shape` for HCons:

```scala
final class HListShape[Level <: ShapeLevel, M <: HList, U <: HList, P <: HList]
      (val shapes: Seq[Shape[_, _, _, _]])(implicit evidence$1: scala.reflect.ClassTag[U])
      extends MappedProductShape[Level, HList, M, U, P] {
  def buildValue(elems: IndexedSeq[Any]) = elems.foldRight(HNil: HList)(_ :: _)
  def copy(shapes: Seq[Shape[_ <: ShapeLevel, _, _, _]]) = new HListShape(shapes)
  override def getElement(value: HList, idx: Int): Any = value match {
    case HNil => throw new ArrayIndexOutOfBoundsException(idx)
    case head :: tail => if (idx == 1) head else this.getElement(tail, idx-1)
  }
  override def classTag: ClassManifest[U] = evidence$1
}

implicit def hnilShape[Level <: ShapeLevel] = new HListShape[Level, HNil.type, HNil.type, HNil.type](Nil)

implicit def hconsShape[Level <: ShapeLevel, M1, M2 <: HList, U1, U2 <: HList, P1, P2 <: HList]
      (implicit s1: Shape[_ <: Level, M1, U1, P1], s2: HListShape[_ <: Level, M2, U2, P2]) = {
    new HListShape[Level, M1 :: M2, U1 :: U2, P1 :: P2](s1 +: s2.shapes)
```

now the `Shape` of `HNil` can be obtained with  `(HNil).shaped` and seems correct but the `Shape` of `HCons` gives compilation error:

```scala
> (1 :: HNil).shaped
Error:(55, 23) No matching Shape found.
Slick does not know how to map the given types.
Possible causes: T in Table[T] does not match your * projection. Or you use an unsupported type in a Query (e.g. scala List).
  Required level: scala.slick.lifted.FlatShapeLevel
     Source type: shapeless.::[Int,shapeless.HNil]
   Unpacked type: U
     Packed type: Any
  println((1 :: HNil).shaped)
                      ^
```

Not sure why the implicit def for `HCons` doesn't work, any idea?

**Comment by kheraud** [comment]
Is there any summary somewhere of the best approach to use slick with a table with more than 22 columns ? ("People will ask for this ":)) .
Some examples deal with nested case class, others with HList which seams hard to convert to case class.
What is the right way to do it (perennial with slick 3.x roadmap) ?

**Comment by mdedetrich** [comment]
@kheraud The method I described at http://stackoverflow.com/questions/24978042/slick-2-10-rc1-scala-2-11-x-bypassing-22-arity-limit-with-case-class-heteroge/24982618#24982618 is the method I use (and still use with Slick` 3.0, although I believe there was some deprecated imports)

I don't think there is an alternative method, there is an issue lying around somewhere regarding shapeless integration, but it would essentially be doing the same. Until `Scala`'s 22 tuple arity limit gets addressed, that is the only solution (as far as I am aware)

**Comment by nafg** [comment]
I would say nested case classes, or nested tuples.
With Slick, at least 3, you can combine and map MappedProjections. Here's
some code I have:

case class OrderAll(basic: OrderBasic, ...)

val basicProjection = basicFields <>(OrderBasic.tupled, OrderBasic.unapply)
*...*

def all = (basicProjection, ...).shaped <> (
  { case (basic, ...) => OrderAll(basic, ...) },
  (oa: OrderAll) => Some((oa.basic, ...))
)



So you can have a tuple containing a MappedProjection as well as other
tuples, and then <> it further. So it's no big deal to do nested case
classes or nested tuples.

**Comment by kheraud** [comment]
Thanks, I will keep on using @mdedetrich solution with no nesting at all (as Scala 2.11 fixed the case class limit of 22 params).

**Comment by cvogt** [comment]
@szeiger do you see what's wrong with @melrief's shapeless try up there?

**Comment by mdedetrich** [comment]
@cvogt Is `shapeless` integration via a plugin still on the gameplan, and if so, when?

**Comment by milessabin** [comment]
There's a first cut at @szeiger's option (2) in this [SO answer](http://stackoverflow.com/a/31882401/146737) and the linked [github project](https://github.com/underscoreio/slickless).

**Comment by deusaquilus** [comment]
Based on @szeiger 's HListCaseClassShape I tried creating a HListCaseClassShape using Slick's HList. I really don't want to depend on scalaz unless there's absolutely no other choice.

```scala
class HListCaseClassShape[P <: Product, LiftedList, LiftedCaseClass <: P, PlainList, PlainCaseClass <: P](
       mapLifted: LiftedList => LiftedCaseClass, mapPlain: PlainList => PlainCaseClass)(
       implicit columnShapes: Shape[FlatShapeLevel, LiftedList, PlainList, LiftedList], classTag: ClassTag[PlainCaseClass])
  extends MappedScalaProductShape[FlatShapeLevel, P, LiftedCaseClass, PlainCaseClass, LiftedCaseClass] {
  val shapes = columnShapes.asInstanceOf[HListShape[_,_,_,_]].shapes
  override def toMapped(v: Any) = {
    val folded = v.asInstanceOf[Product].productIterator.foldRight(HNil: HList)(_ :: _)
    folded.asInstanceOf[PlainList]
  }
  def buildValue(elems: IndexedSeq[Any]) = {
    val list = elems.foldRight(HNil: HList)(_ :: _)
    mapLifted(list.asInstanceOf[LiftedList])
  }
  def copy(s: Seq[Shape[_ <: ShapeLevel, _, _, _]]) = new HListCaseClassShape(mapLifted, mapPlain) { override val shapes = s }
}
```  

Then I tested it out like this:
```scala
case class LiftedB(data1: Rep[String], data2: Rep[String], data3: Rep[String], data4: Rep[String], data5: Rep[String], data6: Rep[String], data7: Rep[String], data8: Rep[String], data9: Rep[String], data10: Rep[String], data11: Rep[String], data12: Rep[String], data13: Rep[String], data14: Rep[String], data15: Rep[String], data16: Rep[String], data17: Rep[String], data18: Rep[String], data19: Rep[String], data20: Rep[String], data21: Rep[String], data22: Rep[String], data23: Rep[String], data24: Rep[String], data25: Rep[String])
case class B(data1: String, data2: String, data3: String, data4: String, data5: String, data6: String, data7: String, data8: String, data9: String, data10: String, data11: String, data12: String, data13: String, data14: String, data15: String, data16: String, data17: String, data18: String, data19: String, data20: String, data21: String, data22: String, data23: String, data24: String, data25: String )

type DirectConsList = HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HCons[String, HNil]]]]]]]]]]]]]]]]]]]]]]]]]
type LiftedConsList = HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HCons[Rep[String], HNil]]]]]]]]]]]]]]]]]]]]]]]]]

implicit object BShape extends HListCaseClassShape[
  Product,
  LiftedConsList,
  LiftedB,
  DirectConsList,
  B](toLifted, toDirect)

def toLifted(list: LiftedConsList) = {
  list match {
    case data1 :: data2 :: data3 :: data4 :: data5 :: data6 :: data7 :: data8 :: data9 :: data10 :: data11 :: data12 :: data13 :: data14 :: data15 :: data16 :: data17 :: data18 :: data19 :: data20 :: data21 :: data22 :: data23 :: data24 :: data25 :: HNil => {
      LiftedB(data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21, data22, data23, data24, data25 )
    }
    case _ => throw new Exception("malformed HList")
  }
}

def toDirect(list:DirectConsList) = {
  list match {
    case data1 :: data2 :: data3 :: data4 :: data5 :: data6 :: data7 :: data8 :: data9 :: data10 :: data11 :: data12 :: data13 :: data14 :: data15 :: data16 :: data17 :: data18 :: data19 :: data20 :: data21 :: data22 :: data23 :: data24 :: data25 :: HNil => {
      B(data1, data2, data3, data4, data5, data6, data7, data8, data9, data10, data11, data12, data13, data14, data15, data16, data17, data18, data19, data20, data21, data22, data23, data24, data25 )
    }
    case _ => throw new Exception("malformed HList")
  }
}

```

Sadly, to no avail. I'm getting exceptions in the type conversion (also posted [here](http://stackoverflow.com/questions/40543310/trying-to-make-a-hcons-list-caseclassshape)):
```
Exception in thread "main" java.lang.ClassCastException: slick.collection.heterogeneous.HCons cannot be cast to com.example.CaseClassShapeQueryExample$B
  at com.example.CaseClassShapeQueryExample$$anonfun$2.apply(CaseClassShapeQueryExample.scala:106)
  at slick.backend.DatabasePublisher$$anon$3$$anonfun$onNext$1.apply(DatabasePublisher.scala:48)
  at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
```

Anyone have any idea what I'm doing wrong? Will Stefan come to the rescue?

**Comment by milessabin** [comment]
@deusaquilus you should probably take a look at [slickless](https://github.com/underscoreio/slickless).

**Comment by deusaquilus** [comment]
Same question about slickless then. How can I have automatic mapping to B/LiftedB with the slickless `mappedWith` without having to create a `Table` object and `*` operator? (i.e. using some sort of implicit shape or conversion)

**Comment by milessabin** [comment]
@deusaquilus I suggest asking [here](https://gitter.im/underscoreio/slickless).

**Comment by deusaquilus** [comment]
Okay, it looks like all I was missing was `mapPlain(folded.asInstanceOf[PlainList])`, the approach above works! For anyone who needs to use the monomorphic CaseClassShape that has greater then 22 tuple arity please refer to the gist here: [HListCaseClassShape](https://gist.github.com/deusaquilus/5b52b82598c534ca09119efcf0acbc50).

**Comment by deusaquilus** [comment]
I'm actually surprised this isn't a more typical use case. Has anyone ever had the need to use a monomorphic CaseClassShape with more then 22 fields?

**Comment by nafg** [comment]
You can compose projections, so you can just nest case classes and build up
their projections.

**Comment by deusaquilus** [comment]
True that, but you don't always get the luxury if these objects need to be fed to upstream systems. In the latter case you end up having to write unruly conversion layers between the nested and flattened objects which introduces lots of incidental complexity. My application actually uses both approaches (i.e. nested and flattened) in different places as is appropriate.
