### ISSUE TITLE
JdbcProfile has no TypeInfo for type scala.slick.driver.JdbcTypesComponent$MappedJdbcType$$anon$1/INTEGER

### ISSUE THREAD

**Issue by cvogt** [slick/slick#540]
happens since #534 

https://github.com/slick/slick/tree/tmp/typeinfo-issue

> test

[error] Test scala.slick.test.jdbc.GeneratedCodeTest.customTypingTest failed: scala.slick.SlickException: JdbcProfile has no TypeInfo for type scala.slick.driver.JdbcTypesComponent$MappedJdbcType$$anon$1/INTEGER
    [error]     at scala.slick.driver.JdbcTypesComponent$class.typeInfoFor(JdbcTypesComponent.scala:127)
    [error]     at scala.slick.driver.H2Driver$.typeInfoFor(H2Driver.scala:61)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$MappingCompiler$class.createColumnConverter(JdbcMappingCompilerComponent.scala:18)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.createColumnConverter(JdbcMappingCompilerComponent.scala:49)
    [error]     at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$class.compileMapping(RelationalProfile.scala:213)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.compileMapping(JdbcMappingCompilerComponent.scala:49)
    [error]     at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$$anonfun$compileMapping$1.apply(RelationalProfile.scala:218)
    [error]     at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$$anonfun$compileMapping$1.apply(RelationalProfile.scala:218)
    [error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    [error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    [error]     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    [error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    [error]     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    [error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    [error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    [error]     at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    [error]     at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$class.compileMapping(RelationalProfile.scala:218)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.compileMapping(JdbcMappingCompilerComponent.scala:49)
    [error]     at scala.slick.profile.RelationalMappingCompilerComponent$MappingCompiler$class.compileMapping(RelationalProfile.scala:222)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.compileMapping(JdbcMappingCompilerComponent.scala:49)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.createMapping(JdbcMappingCompilerComponent.scala:50)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.createMapping(JdbcMappingCompilerComponent.scala:49)
    [error]     at scala.slick.compiler.InsertCompiler$$anonfun$apply$1.apply(InsertCompiler.scala:55)
    [error]     at scala.slick.compiler.InsertCompiler$$anonfun$apply$1.apply(InsertCompiler.scala:17)
    [error]     at scala.slick.compiler.CompilerState.map(QueryCompiler.scala:144)
    [error]     at scala.slick.compiler.InsertCompiler$class.apply(InsertCompiler.scala:17)
    [error]     at scala.slick.jdbc.JdbcMappingCompilerComponent$JdbcInsertCompiler.apply(JdbcMappingCompilerComponent.scala:49)
    [error]     at scala.slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:55)
    [error]     at scala.slick.compiler.QueryCompiler$$anonfun$runPhase$1.apply(QueryCompiler.scala:54)
    [error]     at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
    [error]     at scala.slick.ast.SymbolNamer.use(Symbol.scala:101)
    [error]     at scala.slick.compiler.QueryCompiler.runPhase(QueryCompiler.scala:54)
    [error]     at scala.slick.compiler.QueryCompiler$$anonfun$run$2.apply(QueryCompiler.scala:46)
    [error]     at scala.slick.compiler.QueryCompiler$$anonfun$run$2.apply(QueryCompiler.scala:46)
    [error]     at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    [error]     at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:144)
    [error]     at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    [error]     at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    [error]     at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
    [error]     at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
    [error]     at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:144)
    [error]     at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:105)
    [error]     at scala.slick.compiler.QueryCompiler.run(QueryCompiler.scala:46)
    [error]     at scala.slick.compiler.QueryCompiler.run(QueryCompiler.scala:41)
    [error]     at scala.slick.profile.BasicProfile$Implicits$class.queryToInsertInvoker(BasicProfile.scala:53)
    [error]     at scala.slick.driver.JdbcProfile$$anon$1.queryToInsertInvoker(JdbcProfile.scala:25)
    [error]     at scala.slick.test.jdbc.GeneratedCodeTest$$anonfun$customTypingTest$1.apply(GeneratedCodeTest.scala:201)
    [error]     at scala.slick.test.jdbc.GeneratedCodeTest$$anonfun$customTypingTest$1.apply(GeneratedCodeTest.scala:197)
    [error]     at scala.slick.backend.DatabaseComponent$DatabaseDef$class.withSession(DatabaseComponent.scala:31)
    [error]     at scala.slick.jdbc.JdbcBackend$DatabaseFactoryDef$$anon$4.withSession(JdbcBackend.scala:61)
    [error]     at scala.slick.test.jdbc.GeneratedCodeTest.customTypingTest(GeneratedCodeTest.scala:197)
    [error]     ...

**Comment by szeiger** [comment]
It looks like this should be fixed. In master, the match is on `case tmd: JdbcType[_] => tmd` where `JdbcType` is defined outside of the driver cake.
