### ISSUE TITLE
Allow to replace SQL used by invoker/executor

### ISSUE THREAD

**Issue by cvogt** [slick/slick#585]
For supporting unknown SQL query operations one workaround is replacing the query used by the invoker for a different one which returns identically shaped results.

Here is an implementation for Slick 1.0.1 https://gist.github.com/cvogt/8054159

Here is a motivating ML thread
https://groups.google.com/d/msg/scalaquery/4O1Wr4EK-W4/b7FCudlia2YJ

**Comment by szeiger** [comment]
Fixing for new 3.0 API only, see #1007
