### ISSUE TITLE
Introduce single and singleOption to Invoker

### ISSUE THREAD

**Issue by ijuma** [slick/slick#71]
The behaviour should be:
- single when exactly one result is expected. An exception is thrown otherwise.
- singleOption when zero or one result are expected. An exception is thrown otherwise.

The advantage of using these methods instead of first and firstOption is that if the expected invariant is broken due to an incorrect query or data issue, things fail fast.

@szeiger  said the following on IRC:

"Yeah, that would be useful to have in Invoker. I'm not sure how to go forward with it for the new Executor model though."
"In any case, Invokers won't go away. We still need them for Plain SQL queries even if the Scala embeddings move to a different model"
"Yeah, just set the fetch size to 2, read the first result and then check if there's a second one. It just needs some boilerplate."

**Comment by szeiger** [comment]
This could be implemented for Actions instead.
