### ISSUE TITLE
remove overloads

### ISSUE THREAD

**Issue by cvogt** [slick/slick#743]
Let's try to remove or at least reduce method overloading. I just gave a wrongly typed value to `.insert` and got an overloading error because it is overloaded to take a value or a query. Lets call the query one `.insertQuery` or `.insertFrom` or turn it around and give a query an `.insertInto` member which takes the target query.

**Comment by szeiger** [comment]
The new Action API has separate methods `+=`, `insertExpr` and `insert` (for Query and CompiledQuery)
