### ISSUE TITLE
Statically prevent running groups

### ISSUE THREAD

**Issue by cvogt** [slick/slick#754]
In FirstExample of  slick-example, adding
```
val q: Map[String, Int] = coffees.groupBy(_.name).map { case (n, c) => (n, c.first._2)}.toMap
```
leads to
`No type for symbol s2 found in Col1.`

`.first` tries to execute a group, which probably doesn't make sense. Maybe we can catch this statically or throw an exception (it is probably detectable from the tree).

**Comment by szeiger** [comment]
This shouldn't compile any more with the new API in 3.0. The equivalent of `first` gives you an `Action` for which there is no Shape.
