### ISSUE TITLE
AutoInc colums are always primary keys

### ISSUE THREAD

**Issue by OlivierBlanvillain** [slick/slick#763]
Hello, I have a small issue when trying to use an auto-incremented colum as part of a compound primary key. It looks like both

```
def id = column[Long]("ID", O.AutoInc)
```

and

```
def id = column[Long]("ID", O.AutoInc, O.PrimaryKey)
```

generate the same DDL, with ID as a primary key. Adding a compound primary key, `def pk = primaryKey("pk", (id, updatedAt))`, leads to the following error:

```
We got the following error: Attempt to define a second primary key; SQL statement: alter table "Author" add constraint "pk" primary key("ID","updatedat") [90017-172] [ERROR:90017, SQLSTATE:90017], while trying to run this SQL script:
create table "Author" ("ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL,"updatedat" TIMESTAMP NOT NULL,"updatedby" VARCHAR NOT NULL, ...);
alter table "Author" add constraint "pk" primary key("ID","updatedat");
```

This is with H2, `"com.typesafe.slick" %% "slick" % "2.0.0"` and `"com.typesafe.play" %% "play-slick" % "0.6.0.1"`. If needed, here are links to the [project repo](https://github.com/SlickChair/SlickChair/tree/3b6e3acaed44b3da2f6d664d475f4a04d4b67433), the [table definitions](https://github.com/SlickChair/SlickChair/blob/3b6e3acaed44b3da2f6d664d475f4a04d4b67433/app/models/Tables.scala#L20) and the [generated DDL](https://github.com/SlickChair/SlickChair/blob/3b6e3acaed44b3da2f6d664d475f4a04d4b67433/conf/evolutions/default/1.sql#L6).

**Comment by hanfeisun** [comment]
+1 the same issue..

It seems currently the only solution is to modify the generated SQL code, it would be great if this bug could be fixed..

**Comment by curreli** [comment]
+1, can this be released?
