### ISSUE TITLE
Support for WHERE NOT EXISTS

### ISSUE THREAD

**Issue by nremond** [slick/slick#800]
It would be nice to be able to do some conditional inserts.

For example, if we have the following table:

```
    +----------+----------+
    | user_id  | store_id |
    +----------+----------+
    |    39    |    8     |
    |    8     |    39    |
    |    5     |    11    |
    +----------+----------+
```

I would like to be able to run the following query:

```
INSERT INTO favorite_store (user_id, store_id) VALUES (39, 8)
WHERE NOT EXISTS 
    (SELECT * FROM favorite_store WHERE user_id = 39 AND store_id = 8)
```

**Comment by avalon12** [comment]
+1, I'd like to see this in the DSL very much!

**Comment by nikkatalnikov** [comment]
any progress on this issue?

**Comment by hvesalai** [comment]
It's in the feature ideas box, so it is waiting for community contributions. If you would like to work on it, it is up for grabs.

**Comment by sebastianrozyczka** [comment]
@nremond Very old thread, but this is now supported by the slick API, so the issue can be closed so as not to confuse anyone :)
