### ISSUE TITLE
support setFetchSize / set jdbc statement batch size

### ISSUE THREAD

**Issue by cvogt** [slick/slick#809]
https://groups.google.com/d/msgid/scalaquery/53765C93.20705%40typesafe.com?utm_medium=email&utm_source=footer
> There is currently no easy way to change the page size in Slick (but you could hack into the driver similar to https://github.com/slick/slick/blob/76efe03d39cf3922dfd2eb62a5330f3e643d9b57/src/sphinx/code/SqlToScala.scala#L143-166 in order to set the page size of the PreparedStatement

Let's make it a feature

**Comment by hvesalai** [comment]
The default behavior of postgresql is to fetch everything. This means that `.iterator` will fetch everything and OOM on big tables.

**Comment by cvogt** [comment]
closed in favor of #1038, which will likely fix this in Slick 3.0.0

**Comment by szeiger** [comment]
Reopening. This warrants special support, you shouldn't have to drop down to JDBC.

**Comment by cvogt** [comment]
+1

**Comment by hvesalai** [comment]
Just to make sure it get's noted: besides fetchSize != 0, autocommit must be turned off for postgres to actually do batching. See #1038 for our code.

**Comment by szeiger** [comment]
@hvesalai I think the transaction should be done in user code (just wrap it in `.transactionally`). We could do it automatically in PostgresDriver but that would mean we'd either have to universally add a `Transaction` effect to `withStatementParameters` or have PostgresDriver silently drop that effectin the return type.

**Comment by hvesalai** [comment]
Yeah, definitely transaction controlled by user code. I just mean that there's a gotcha here. If you are not in a transaction, postgres will silently return you everything at once. Our code asserts that autocommit is turned off so that the developer can notice and fix the issue.

**Comment by matanster** [comment]
Do you happen to know whether this auspicious PR would also work for MySQL?
It is a little vague in the docs whether MySQL respects fetch size values other than zero..
