### ISSUE TITLE
Monadic Actions / Transactions

### ISSUE THREAD

**Issue by cvogt** [slick/slick#827]
Monadic transaction api for better composability

review monadic style in:

https://gist.github.com/cvogt/4707c3f938a2e984cc11

https://github.com/tpolecat/tiny-world/blob/master/src/test/scala/org/tpolecat/tiny/world/example/slick/FirstExampleMinimal.scala

**Comment by szeiger** [comment]
Available in 3.0.0-M1

**Comment by aloiscochard** [comment]
I'm sadly not using Slick anymore at my new job, but I'll surely find an excuse to bring it it and give that a try ;)

Great stuff @szeiger and @cvogt, ty!
