### ISSUE TITLE
Feature Request: Support for "SELECT ... FOR UPDATE"

### ISSUE THREAD

**Issue by hvesalai** [slick/slick#92]
Row level locking is supported by most datebases. The usual syntax to lock a row is to do a SELECT ... FOR UPDATE query in the beginning of the transaction.

This mechanism is supported at least by the following databases (some I know from experience and the rest I checked with quick googling)

- Derby/JavaDB
- H2
- HSQLDB/HyperSQL
- Microsoft SQL Server
- MySQL
- PostgreSQL
- Oracle

Not support (and not needed) by SQLite since it allows no concurrent access anyway. (http://www.sqlite.org/cvstrac/wiki?p=UnsupportedSql)

Workaround and discussion: https://groups.google.com/forum/#!msg/scalaquery/exYF_FSQBmc/WK9pmm7ilkoJ

**Comment by msarti** [comment]
+1

**Comment by neurozen** [comment]
:+1 please

**Comment by DStranger** [comment]
+1

**Comment by tomdcc** [comment]
+1

**Comment by neurozen** [comment]
+1

**Comment by bomgar** [comment]
+1

**Comment by savulchik** [comment]
+1

**Comment by Schweigi** [comment]
+1

**Comment by bad79s** [comment]
+1

**Comment by yzbr** [comment]
+1

**Comment by bartekkalinka** [comment]
+1

**Comment by adamw** [comment]
+1

**Comment by curreli** [comment]
+1

**Comment by narma** [comment]
+100500

**Comment by yuanl1** [comment]
+1

**Comment by vdumitrescu** [comment]
+1

**Comment by hepin1989** [comment]
+1

**Comment by adamretter** [comment]
+1

**Comment by realzeus** [comment]
+1

**Comment by raimohanska** [comment]
+1

**Comment by anzecesar** [comment]
+1

**Comment by fractal** [comment]
how many +1s does a ticket need to get to be considered high priority?

Can we create a CommunityHighPriority tag?

**Comment by cvogt** [comment]
I would consider it high priority. We do have an "UPVOTED" tag for this purpose, which I assigned a while back. Slick is open source and hopefully somebody will step up to tackle this. We are currently in the process of expanding the group of core maintainers, which will hopefully make this easier.

**Comment by smootoo** [comment]
I've submitted a PR for this https://github.com/slick/slick/pull/1454
Re: +1 people, let me know if this isn't going to cover your use-case and I'll see what I can do.

**Comment by cvogt** [comment]
fixed in #1454

**Comment by rikiya-yamamoto** [comment]
PostgreSQL support,
Not yet?

**Comment by smootoo** [comment]
The PR that implements this for all backends that support it (including postgres) has been merged to master. So it's available in the latest milestone release https://github.com/slick/slick/releases/tag/3.2.0-M1
