### ISSUE TITLE
Use Shapeless HList instead of Slick's HList

### ISSUE THREAD

**Issue by mdedetrich** [slick/slick#943]
Long story short, this is to address the issue that is described here 

http://stackoverflow.com/questions/24978042/slick-2-10-rc1-scala-2-11-x-bypassing-22-arity-limit-with-case-class-heteroge

The main point being, is that Slick's HList implementation, although adequate for the basic operations (mapping a table to a HList, and updating a select number of fields through the HList), it falls short in other areas, such as mapping a HList to a case class (needed if you want to represent a table with > 22 columns as a case class)

What would the various pros/cons be in regards to using shapeless `HList` implementation instead of slicks? When using the shapeless implementation of HList, we can do stuff like this, for example

```scala
def gen = Generic[SomeCaseClass]
(field1 ::
field2 ::
field3 ::
HNil).shaped <>
      ({case x => gen.from(x)}, {someCaseClass => Option(gen.to(x))})
```

Or maybe an even shorter version
```scala
def gen = Generic[SomeCaseClass]
(field1 ::
field2 ::
field3 ::
HNil) <> (gen.from _, gen.to _)
```

We can also do stuff like map tables to records, (records are to case classes what HLists are to tuples)

There are other advantages, which includes a lot of very nice generic functions that come with using shapeless, which are absent in slick's implementation

For more info on what Shapeless can do, you can have a look here https://github.com/milessabin/shapeless/wiki/Feature-overview:-shapeless-2.0.0
Any thoughts in regards to this?

**Comment by szeiger** [comment]
Closing as wontfix. This should be done as a separate project.

**Comment by cvogt** [comment]
I may give this a shot some day.

**Comment by cvogt** [comment]
Agree, that this should be an extension to Slick, not part of Slick itself. But let's still track it here for now.

**Comment by callicles** [comment]
Just found that: https://github.com/underscoreio/slickless

**Comment by d6y** [comment]
Closing, now that there is a library available.

**Comment by cvogt** [comment]
@d6y should we add this library to the docs somewhere?

**Comment by d6y** [comment]
@cvogt yes, good idea: https://github.com/slick/slick.github.com/pull/24
