### ISSUE TITLE
Option columns do not generate correct MySQL statements

### ISSUE THREAD

**Issue by pathikrit** [slick/slick#947]
`def listChildren(parentId: Option[Int]) = Nodes.filter.(_.parentId === parentId).list()`

The above generates `select * from nodes where parentId = null` when `parentId` is `None` which is invalid SQL. It should generate `select * from nodes where parentId is null` instead for `None`s because null comparison is always null which evaluates to false in MySQL

**Comment by romanwozniak** [comment]
Does anyone know how to accomplish such behaviour in slick 3.x.x? 
I mean `OptionalColumnExtension ` implicit.

I was trying to do something like:
```scala
implicit class OptionColumnExtensions[T](left: Rep[Option[T]])(implicit tt: TypedType[T], om: OptionMapper2[T, T, Boolean, Option[T], T, Option[Boolean]]) {
  def =?=(right: Option[T]) = {
    right.map(left === _).getOrElse(left.isEmpty.?)
  }
}
```
But this results in 
```
[error] ../Tables.scala:358: value === is not a member of Tables.this.driver.api.Rep[Option[T]]
[error]         right.map(c === _).getOrElse(c.isEmpty.?)
[error]                     ^
```
When I try to specify `T` type explicitly (for example `Long`), this works as expected.

**Comment by d6y** [comment]
I think methods like === are defined for BasedTypedType. Changing to
(implicit tt: BaseTypedType[T]) should get you somewhere.

I don't know if you need that OptionMapper2 - but then again, I don't
really know what it does!

Regards
Richard

**Comment by romanwozniak** [comment]
@d6y This helped, thanks a lot!

**Comment by cvogt** [comment]
@romanwozniak can you paste the version you ended up with here :)?

**Comment by romanwozniak** [comment]
@cvogt
```scala
implicit class OptionColumnExtensions[T](left: Rep[Option[T]])(implicit tt: BaseTypedType[T]){
  def =?=(right: Option[T]) = {
    right.map(left === _).getOrElse(left.isEmpty.?)
  }
}
```
