### ISSUE TITLE
Not able to apply filter based on functions of DateTime class

### ISSUE THREAD

**Issue by anuragrk** [slick/slick#968]
case class Test(id: Option[Int],dob: Option[DateTime])

object TestDetails extends Table[[Test]] ("test_details") {
  def id = column[[Int]]("id", O.PrimaryKey, O.AutoInc)
 def dob = column[[Option[[DateTime]]("dob")
}
I want to apply a filter on dob with dayOfMonth()
val query = Query(TestDetails) filter ( td => (td.dob.get is DateTime.now.dayOfMonth()))

Basically its not allowing to access me td.dob.get.dayOfMonth() in the filter.
Though am able to achieve this when I query the table first and iterate over it and check the dob.get.dayOfMonth ==  DateTime.now.dayOfMonth()

Ideally same should be achieved while applying the filter itself.

Thanks for the suggestions!

**Comment by szeiger** [comment]
Can't really do anything better here.
