### ISSUE TITLE
codegen too large VARCHAR in mysql

### ISSUE THREAD

**Issue by cvogt** [slick/slick#975]
https://groups.google.com/d/msgid/scalaquery/76eea22f-9470-4be8-ba19-f07b06812670%40googlegroups.com?utm_medium=email&utm_source=footer

**Comment by szeiger** [comment]
The same occurs in PostgreSQL but the solution will probably be different because we not generate unconstrained text columns by default in Postgres (where, unlike in MySQL, VARCHAR can be unconstrained and is identical to TEXT)

**Comment by szeiger** [comment]
On second thought, since we do have an explicit `O.Length` column option, the default should always be unconstrained size if the database has a suitable type. I'll try that to see how much it breaks...
