### ISSUE TITLE
Update Scala version to 2.11.2

### ISSUE THREAD

**Issue by falconepl** [slick/slick#980]
Could you publish Slick 2.1.0 against Scala 2.11.2? There was a significant bug fix introduced in that version - [SI-8675](https://issues.scala-lang.org/browse/SI-8675).

It seems that I'm currently affected by this bug - a similar to the one described [here](https://groups.google.com/forum/#!topic/scala-internals/wOiDhoE6MME) by Phil Rice. In short, it looks like this:

    [error]   Unknown type: <error>, <error> [class scala.reflect.internal.Types$ErrorType$, class scala.reflect.internal.Types$ErrorType$] TypeRef? false

Both my application and a library that it uses ([Unicorn](https://github.com/VirtusLab/unicorn)) have been build against Scala 2.11.2. It's only Unicorn that uses Slick 2.1.0 that depends on Scala 2.11.1, so it seems to be a kind of a suspect for now.

**Comment by szeiger** [comment]
Master is on 2.11.4 now.
