### ISSUE TITLE
Codegen does not support postgres UUID datatype

### ISSUE THREAD

**Issue by ShaneDelmore** [slick/slick#982]
When trying to use codegen on a simple table with one column, id of type UUID the generated case class  has  datatype of string as shown below.

    val id: Column[String] = column[String]("Id", O.PrimaryKey, O.Length(2147483647,varying=false))

I attempted to override the mapping to explicitely change the type to UUID using what I could piece together from the documentation examples:

    override def Table = new Table(_) {
      table =>
      override def Column = new Column(_) {
        column =>
        override def rawType = model.tpe match {
          case "String" => model.options.find(_.isInstanceOf[ColumnOption.DBType])
            .map(_.asInstanceOf[ColumnOption.DBType].dbType).map({
            case "uuid" => "UUID"
            case _ => "String"
          }).getOrElse("String")
          case _ => super.rawType
        }
      }
    }

After which I still ended up with something closer but it has the length set incorrectly:
```
val id: Column[UUID] = column[UUID]("Id", O.PrimaryKey, O.Length(2147483647,varying=false))
```

**Comment by szeiger** [comment]
Fixed by #989, right?

**Comment by nmartynenko** [comment]
@szeiger I'm afraid, no.

There seems no possibility to test PG code generation.

I mean, it's easy to add a feature, but hard to test.

I asked you about tests [here](https://github.com/slick/slick/pull/989#issuecomment-59015966), but you might have missed it.

If you could give me direction, how I need to write a test for that, I could fix that.

Thanks in advance.

Cheers, Nick.

**Comment by szeiger** [comment]
@nmartynenko What's still missing? You did add tests in #989 and you added them in the places I would have suggested (CodegenTest/CodegenRoundtripTest).

**Comment by nmartynenko** [comment]
Hi @szeiger.

Please check #1058 PR. Hope that helps.

Cheers, Nick.
