### ISSUE TITLE
Got "comprehension not supported on update" error message, but was using a single table

### ISSUE THREAD

**Issue by ArturSoler** [slick/slick#984]
I got the following error message when performing an update similar to this one:

``` scala
  MyTable.
    filter(someCondition).
    sortBy(_.someField.desc).
    take(1).
    map(_.anotherField).
    update(Some(DateTime.now))
```

The exact error is: `scala.slick.SlickException: A query for an UPDATE statement must resolve to a comprehension with a single table -- Unsupported shape: Comprehension`

I'm using Slick 2.1.0.

**Comment by szeiger** [comment]
Does it work on 3.2.0-M2? This could be an instance of the bug I fixed in https://github.com/slick/slick/pull/1649.

**Comment by ArturSoler** [comment]
Can't check again, sorry. Closing issue.

**Comment by tlewowski** [comment]
I have the same issue on 3.2.1 - indeed, removing `take` fixed the problem with "comprehension not supported on update"

**Comment by art-solopov** [comment]
I'm having the same issue on 3.6.0. And also removing `take` removed the issue.

Full error message:

```
slick.SlickException: A query for an UPDATE statement must resolve to a comprehension with a single table -- Unsupported shape: Comprehension s2, Some(Apply Function =), None, ConstArray(), None, None, Some(LiteralNode 1 (volatileHint=false)), None, false
```
